// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ADDRESS
    {
        public ADDRESS()
        {
            AU_ADDRESS = new HashSet<AU_ADDRESS>();
        }

        public int ID_ADDRSS { get; set; }
        public short ID_CNTY_STATE { get; set; }
        public int? ID_MMBR { get; set; }
        public int? ID_EMPLYMNT { get; set; }
        public int? ID_PRVDR_NAME { get; set; }
        public decimal ID_REF_ADDRSS_TYPE { get; set; }
        public string AD_STREET1 { get; set; }
        public string AD_STREET2 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
        public string AD_ZIP_4 { get; set; }

        public virtual REF_COUNTY_STATE ID_CNTY_STATENavigation { get; set; }
        public virtual EMPLOYMENT ID_EMPLYMNTNavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual REF_PROVIDER_NAME ID_PRVDR_NAMENavigation { get; set; }
        public virtual REF_ADDRESS_TYPE ID_REF_ADDRSS_TYPENavigation { get; set; }
        public virtual ICollection<AU_ADDRESS> AU_ADDRESS { get; set; }
    }
}