// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ARCHIVE_MIGRANTWORKER
    {
        public int ID_MIGRANTWORKER { get; set; }
        public int? ID_NEWMBR { get; set; }
    }
}