// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ARCHIVE_VOLUNTARYQUIT
    {
        public int ID_VOLUNTARYQUIT { get; set; }
        public int? ID_NEWMBR { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_PHONE_NUMBER { get; set; }
        public string QUIT_REASON { get; set; }
        public string QUIT_DATE { get; set; }
    }
}