// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ARCHIVE_DEPENDENT_CARE
    {
        public int ID_DEPENDENTCARE { get; set; }
        public int ID_NEWMBR { get; set; }
        public decimal? AMOUNT { get; set; }
        public string PAY_FREQUENCY { get; set; }
        public string SITTER_NAME { get; set; }
        public string SIITER_PHONE { get; set; }
    }
}