// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ARCHIVE_LIQUIDRESOURCE
    {
        public int ID_LIQUIDRSC { get; set; }
        public int? ID_NEWMBR { get; set; }
        public string TYPE_LR { get; set; }
        public decimal? AMOUNT_LR { get; set; }
        public string ADD_INFO_1 { get; set; }
        public string ADD_INFO_2 { get; set; }
        public string ADD_INFO_3 { get; set; }
        public string ADD_INFO_4 { get; set; }
    }
}