// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ARCHIVE_SHELTER_EXP
    {
        public int ID_SHELTER_EXP { get; set; }
        public int? ID_NEWMBR { get; set; }
        public string SHELTER_PAY_TYPE { get; set; }
        public string SHELTER_TYPE { get; set; }
        public decimal? RENT_MORTGAGE_AMOUNT { get; set; }
        public decimal? LOT_RENT { get; set; }
        public string LOT_PAY_FREQUENCY { get; set; }
        public decimal? AMT_PROP_TAX { get; set; }
        public decimal? AMT_INSRNC { get; set; }
        public string INSRNC_PAY_FREQUENCY { get; set; }
    }
}