// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ARCHIVE_MEMBERS
    {
        public int ID_NEWMBR { get; set; }
        public int ID_NEWCASE { get; set; }
        public int? DEPENDENT_NMBR { get; set; }
        public string FL_HOH { get; set; }
        public string FL_INVALID_MEMBER { get; set; }
        public string CD_INVALID_MEMBER { get; set; }
        public string DHR_APPLICATION_ID { get; set; }
        public int? DHR_PERSON_ID { get; set; }
        public string DHR_RELATIONSHIP { get; set; }
        public string DHR_ETHNICITY { get; set; }
        public string DHR_USCITIZEN { get; set; }
        public string DHR_MEMBER_SSN { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public string DHR_DOB { get; set; }
        public string DHR_SEX { get; set; }
        public string DHR_RACE { get; set; }
        public string SCI_DEPNUM { get; set; }
        public string SCI_SSN { get; set; }
        public string SCI_VERIND { get; set; }
        public string SCI_DEPNAM { get; set; }
        public string SCI_SEX { get; set; }
        public string SCI_RACE { get; set; }
        public string SCI_DOB { get; set; }
        public string SCI_PACASE { get; set; }
        public string SCI_ELIG { get; set; }
        public string SCI_ERRMSG { get; set; }
    }
}