// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ASPStateTempApplications
    {
        public int AppId { get; set; }
        public string AppName { get; set; }
    }
}