// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class AU_NACLOG
    {
        public int ID_NMBR { get; set; }
        public string ID_USER { get; set; }
        public DateTime DT_RECORD { get; set; }
        public string NO_CASE { get; set; }
        public int? ID_MMBR { get; set; }
        public int? ID_NMBR_LOGIN { get; set; }
        public string SRCH_SSN { get; set; }
        public string FL_NAC_MATCH { get; set; }
        public DateTime? DT_NAC_MATCH { get; set; }
        public string LEX_ID_SCORE { get; set; }
        public string MATCH_CD { get; set; }
        public string SRCH_BENE_MM { get; set; }
        public string DT_APPLD { get; set; }
        public string CD_NAC_AUDIT { get; set; }
        public string fullName { get; set; }
        public short? ID_REF_CERT_ELIG { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
    }
}