// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class AU_PUBLIC_HEALTH
    {
        public int PH_ID { get; set; }
        public DateTime? PH_DT_CREATED { get; set; }
        public string PH_QueryStatus { get; set; }
        public string PH_FullName { get; set; }
        public string PH_DateofBirth { get; set; }
        public string PH_ELEIndicator { get; set; }
        public string PH_EarnedIncome { get; set; }
        public string PH_Employment { get; set; }
        public string PH_Unearned_Income { get; set; }
    }
}