// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class AU_SPECIAL_REOPEN
    {
        public int ID_AUDIT_SPECIAL_REOPEN { get; set; }
        /// <summary>
        /// (getdate())
        /// </summary>
        public DateTime ID_DATE_CREATED { get; set; }
        public int ID_CASE_NUMBER { get; set; }
        public decimal NO_CASE { get; set; }
        public string ID_USER { get; set; }
        public int ID_NMBR_LOGIN { get; set; }
        /// <summary>
        /// &apos;&apos;
        /// </summary>
        public string APPLICATION_DATE { get; set; }
        /// <summary>
        /// &apos;&apos;
        /// </summary>
        public string CERT_FROM { get; set; }
        public string CERT_TO { get; set; }
        public string START_ISS { get; set; }
        public string TRANSACTION_CD { get; set; }
        public string CLOSURE_CD { get; set; }
        public string SPECIAL_REOPEN_TYPE { get; set; }
        public string SCI_MSG { get; set; }
        public string FL_SUCCESS { get; set; }
    }
}