// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class AU_VOTER_POPUP
    {
        public int ID_AU_VOTER_POPUP { get; set; }
        public string NO_CASE { get; set; }
        public DateTime? DT_CREATED { get; set; }
        public string ID_USER { get; set; }
        public int? ID_NMBR_LOGIN { get; set; }
    }
}