// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class CASE
    {
        public CASE()
        {
            AR_RPRSNTTV = new HashSet<AR_RPRSNTTV>();
            AU_CASE = new HashSet<AU_CASE>();
            COVERED_ITEMS = new HashSet<COVERED_ITEMS>();
            MEAL_OTHER = new HashSet<MEAL_OTHER>();
            MEMBER = new HashSet<MEMBER>();
            REPORTING = new HashSet<REPORTING>();
            RESTORATION = new HashSet<RESTORATION>();
            UPDATE_NOTICE_TYPE = new HashSet<UPDATE_NOTICE_TYPE>();
            WAIVE_ADVERSE_ACTION = new HashSet<WAIVE_ADVERSE_ACTION>();
            WORKER_REMINDER = new HashSet<WORKER_REMINDER>();
        }

        /// <summary>
        /// Unique Identity Field for the Case table
        /// </summary>
        public int ID_CASE_NMBR { get; set; }
        /// <summary>
        /// Contains the Unique Identifier from the REF_COUNTY_STATE table for the CD_CNTY associated with this Case
        /// </summary>
        public short ID_CNTY_STATE { get; set; }
        /// <summary>
        /// The 2 digit county code that is used in RESIDING CO on SCI_II
        /// </summary>
        public decimal? CD_CTY_RESIDING { get; set; }
        /// <summary>
        /// Single digit Household Type from Chapter 8 Sect 801 Automation Manual (Values 1,2,3,4,5)
        /// </summary>
        public decimal? CD_HH_TYPE { get; set; }
        /// <summary>
        /// 1 = Authorized Representative, 2 = Responsible HH Member, 3= Head of Household
        /// </summary>
        public string CD_INTRVWEE_DSGNTN { get; set; }
        /// <summary>
        /// 1 = In Office, 2 = Telephone Interview
        /// </summary>
        public string CD_MTHD_INTRVW { get; set; }
        /// <summary>
        /// Values are 1 through 9 from Chapter 8 Section 801, Automation Manual
        /// </summary>
        public decimal? CD_PRCSSN_STNDRD { get; set; }
        /// <summary>
        /// Tracking Office can be 01,02,03, or 04.  Most are 02.  Large counties may have up to 4.  This is the county office responsible for the case.
        /// </summary>
        public decimal? CD_TRCKNG_OFFC { get; set; }
        /// <summary>
        /// Effective Date/Time an adverse action will be initiated (Automation Manual page 8-12)
        /// </summary>
        public DateTime? DT_ADVRS_ACTN { get; set; }
        /// <summary>
        /// Date/Time application officially entered ento the system
        /// </summary>
        public DateTime? DT_APPLD { get; set; }
        /// <summary>
        /// Date/Time an Appointment was entered for SCI_II (normally not used)
        /// </summary>
        public DateTime? DT_APPNTMNT { get; set; }
        /// <summary>
        /// Date/Time of Award Approval action (or denial)
        /// </summary>
        public DateTime? DT_APPRVL { get; set; }
        /// <summary>
        /// Not currently used
        /// </summary>
        public DateTime? DT_EXPRTN { get; set; }
        /// <summary>
        /// This is the date any verification required for Case action was received.
        /// </summary>
        public DateTime? DT_RCVD_VRFCTN { get; set; }
        /// <summary>
        /// This is the date specified that any verification required for Case action is required.
        /// </summary>
        public DateTime? DT_RQRD_VRCTN { get; set; }
        /// <summary>
        /// At this time, the special due date is no longer required.
        /// </summary>
        public DateTime? DT_SPCL_DUE { get; set; }
        /// <summary>
        /// The Head of Household EMAIL address when available and provided
        /// </summary>
        public string EM_HOH { get; set; }
        /// <summary>
        /// Set to &quot;y&quot; if COLA message is displayed for the first time
        /// </summary>
        public string FL_ADVRS_WV { get; set; }
        /// <summary>
        /// Authorized Representative form is signed if &quot;Y&quot;.  Asked in the Interviewee module of OACIS.
        /// </summary>
        public string FL_AR_FORM_SGND { get; set; }
        /// <summary>
        /// If it is a one member household and the member is disqualified, a &quot;N&quot; will mean there is no need to continue the interview.
        /// </summary>
        public string FL_CNTNUE_FA_SCRN { get; set; }
        /// <summary>
        /// Voluntary Quit module:  If it is a one member household and the member is disqualified, a &quot;N&quot; will mean there is no need to continue the interview.
        /// </summary>
        public string FL_CNTNUE_VOLQUIT_SCRN { get; set; }
        /// <summary>
        /// Not Currently Used
        /// </summary>
        public string FL_EBT_ENGLSH { get; set; }
        /// <summary>
        /// Not currently used.
        /// </summary>
        public string FL_EMPLYD { get; set; }
        /// <summary>
        /// Not currently used.
        /// </summary>
        public string FL_EXPCT_STRT_WRK { get; set; }
        /// <summary>
        /// Not Currently used
        /// </summary>
        public string FL_EXPCT_VAC_HOL_BNUS_PAY { get; set; }
        /// <summary>
        /// Interviewee module:  If the household compasition is considered questionable by the worker, this flag is set to &quot;Y&quot;
        /// </summary>
        public string FL_HH_CMPSTN_QSTNBL { get; set; }
        /// <summary>
        /// Interviewee module:  If the head of  household is homeless, this flag is set to &quot;Y&quot;
        /// </summary>
        public string FL_HH_HMLS { get; set; }
        /// <summary>
        /// Unearned Income Module: Flag is set to &quot;Y&quot; or &quot;N&quot; depending on questions answered in this module.
        /// </summary>
        public string FL_JOBS_CHILD_SNCTN { get; set; }
        /// <summary>
        /// Award/Deny Module:  This flag is set to &quot;Y&quot; if the applicant states he/she needs a new EBT card
        /// </summary>
        public string FL_NEW_EBT_CARD { get; set; }
        /// <summary>
        /// Flag set to indicate a member is the case is on strike 
        /// </summary>
        public string FL_ON_STRK { get; set; }
        /// <summary>
        /// Flag set to indicate only one  member is in the household 
        /// </summary>
        public string FL_ONE_PRSN_HH { get; set; }
        /// <summary>
        /// Flag set to indicate pay for Child Support as a non-resident in household 
        /// </summary>
        public string FL_PAY_CS_NON_RSDNT { get; set; }
        /// <summary>
        /// Flag set to indicate pay for Dependent Child Babysitting  in household
        /// </summary>
        public string FL_PAY_DC_BABYSIT { get; set; }
        /// <summary>
        /// Flag set to indicate pay for Dependent Child Bill for a non-resident  in household
        /// </summary>
        public string FL_PAY_DC_BILL_NONHH { get; set; }
        /// <summary>
        /// Flag set to indicate pay for room and meal  for a resident  in household
        /// </summary>
        public string FL_PAY_ROOM_MEAL { get; set; }
        /// <summary>
        /// Flag set to indicate questionable residency for a member in the household
        /// </summary>
        public string FL_RSDNCY_QSTNBL { get; set; }
        /// <summary>
        /// Flag set to indicate if case has a worker terminated member in the household
        /// </summary>
        public string FL_WRK_TRMNTD { get; set; }
        /// <summary>
        /// SSN of the Food Assistant worker modifying the case
        /// </summary>
        public string ID_WRKR_SSN { get; set; }
        /// <summary>
        /// References the verification type of the authorized representative
        /// </summary>
        public short? ID_VRFCTN_ATHRZD_RPRSNTTV { get; set; }
        /// <summary>
        /// References the verification type of the head of household in the Inteview module
        /// </summary>
        public short? ID_VRFCTN_HH { get; set; }
        /// <summary>
        /// References the verification type of the household composition in the interview module
        /// </summary>
        public short? ID_VRFCTN_HH_CMPSTN { get; set; }
        /// <summary>
        /// References the verification type of the head of household  household residency in the interview module
        /// </summary>
        public short? ID_VRFCTN_HH_RSDNCY { get; set; }
        /// <summary>
        /// References the verification type of the interviewee in the interview module
        /// </summary>
        public short? ID_VRFCTN_INTRVWEE { get; set; }
        /// <summary>
        /// References the verification type of the household residency in the interview module
        /// </summary>
        public short? ID_VRFCTN_RSDNCY { get; set; }
        /// <summary>
        /// This is the actual CASE NUMBER for the household assigned by SCI_II
        /// </summary>
        public decimal NO_CASE { get; set; }
        /// <summary>
        /// The check digit assigned the case number from SCI_II
        /// </summary>
        public decimal? NO_CASE_CHCKDGT { get; set; }
        /// <summary>
        /// This field will hold the household telephone number if provided
        /// </summary>
        public string NO_HOME_TEL { get; set; }
        /// <summary>
        /// This is the worker number obtained from the security file
        /// </summary>
        public string NO_WRKR_NMBR { get; set; }
        /// <summary>
        /// The direction to the applicants home that was intered in the contact screen
        /// </summary>
        public string TX_HOME_DRCTNS { get; set; }
        /// <summary>
        /// This is the answer given ((Y)es) or ((N)o) to the lifeline question in the interviewee module
        /// </summary>
        public string FL_LIFELINE { get; set; }
        /// <summary>
        /// If &quot;Y&quot;, this case is to be processed as a &quot;battered woman&quot; case
        /// </summary>
        public string FL_BTRW { get; set; }
        /// <summary>
        /// This Flag is set to &quot;Y&quot; if the case has been sent to the Public Service Commission
        /// </summary>
        public string FL_PSC { get; set; }
        /// <summary>
        /// Text added to the case to document authorized representative verification
        /// </summary>
        public string TX_VRFCTN_ATHRZD_RPRSNTTV { get; set; }
        /// <summary>
        /// Additional verification text for head of household added in the interview module if nececssary
        /// </summary>
        public string TX_VRFCTN_HH { get; set; }
        /// <summary>
        /// Additional verification text for household compostion added in the interview module if nececssary
        /// </summary>
        public string TX_VRFCTN_HH_CMPSTN { get; set; }
        /// <summary>
        /// Additional verification text for household residency added in the interview module if nececssary
        /// </summary>
        public string TX_VRFCTN_HH_RSDNCY { get; set; }
        /// <summary>
        /// Additional verification text for interview verification  added in the interview module if nececssary
        /// </summary>
        public string TX_VRFCTN_INTRVWEE { get; set; }
        /// <summary>
        /// Additional verification text for residency verification added in the interview module if nececssary
        /// </summary>
        public string TX_VRFCTN_RSDNCY { get; set; }
        /// <summary>
        /// This flag is set to &apos;Y&apos; if the case was a special reopen
        /// </summary>
        public string FL_SPECIAL_REOPEN { get; set; }
        /// <summary>
        /// The 2 digit county code of the case&apos;s residing county
        /// </summary>
        public decimal? CD_OFF_RESIDING { get; set; }
        /// <summary>
        /// If the case is a &quot;disaster case&quot;, this field contains the reference to the appropriate disaster
        /// </summary>
        public int? ID_DISASTER { get; set; }
        /// <summary>
        /// When a case is created, this field is created and will not be modified
        /// </summary>
        public DateTime? DT_RECORD_CREATED { get; set; }
        /// <summary>
        /// Each head of household is asked if they want to be registered to vote.  This field is either &quot;Y&quot; or &quot;N&quot;
        /// </summary>
        public string VOTER_ANS { get; set; }
        /// <summary>
        /// This field contains the answer given by the case as to whether they want to be registered to vote.
        /// </summary>
        public string VOTER_TXT { get; set; }
        /// <summary>
        /// A system generated PIN for this case that will be used to tie the case to the myDHR application
        /// </summary>
        public string MYDHR_PIN { get; set; }
        /// <summary>
        /// If the case HH or authorized representative changes their mind about the voting answer, the date of change is recorded here
        /// </summary>
        public DateTime? DT_VOTER_MOD { get; set; }
        public Guid? MYDHR_USERID { get; set; }
        public DateTime? MYDHR_LINKDATE { get; set; }
        public string ALT_OFFICE_NO { get; set; }

        public virtual REF_COUNTY_STATE ID_CNTY_STATENavigation { get; set; }
        public virtual CASE_STATUS CASE_STATUS { get; set; }
        public virtual ICollection<AR_RPRSNTTV> AR_RPRSNTTV { get; set; }
        public virtual ICollection<AU_CASE> AU_CASE { get; set; }
        public virtual ICollection<COVERED_ITEMS> COVERED_ITEMS { get; set; }
        public virtual ICollection<MEAL_OTHER> MEAL_OTHER { get; set; }
        public virtual ICollection<MEMBER> MEMBER { get; set; }
        public virtual ICollection<REPORTING> REPORTING { get; set; }
        public virtual ICollection<RESTORATION> RESTORATION { get; set; }
        public virtual ICollection<UPDATE_NOTICE_TYPE> UPDATE_NOTICE_TYPE { get; set; }
        public virtual ICollection<WAIVE_ADVERSE_ACTION> WAIVE_ADVERSE_ACTION { get; set; }
        public virtual ICollection<WORKER_REMINDER> WORKER_REMINDER { get; set; }
        public virtual REF_COUNTY_STATE REF_COUNTY_STATE { get; set; }
    }
}