// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class CASE_WORKFLOW
    {
        public decimal NO_CASE { get; set; }
        public string CD_REF_MODULE { get; set; }
        public string FL_INTRVW { get; set; }
        public string FL_CMPLTD { get; set; }
        public DateTime DT_CRTD { get; set; }
        public DateTime DT_MDFD { get; set; }
    }
}