// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class CASE_NOTES_TEST
    {
        public int ID_CASE_NOTE { get; set; }
        public int ID_MMBR { get; set; }
        public short ID_CASE_CTGRY { get; set; }
        public DateTime? DT_CASE_NOTE { get; set; }
        public DateTime? DT_CRTD { get; set; }
        public DateTime? DT_MDFD { get; set; }
        public string NM_CRTD { get; set; }
        public string NM_MDFD { get; set; }
        public string TX_CASE_NOTE_DSCR { get; set; }
        public string CD_RJCTN_CLSR_SYNC { get; set; }
    }
}