// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class CASE_STATUS
    {
        public int ID_CASE_NMBR { get; set; }
        public decimal ID_REF_CASE_STATUS_TYPE { get; set; }
        public short? ID_SPCL_REOPEN_RSN { get; set; }
        public string CD_PAST_DUE_RSN { get; set; }
        public string CD_RJCTN_CLSR { get; set; }
        public string CD_DENIAL { get; set; }
        public string CD_TRMNTN { get; set; }
        public decimal? AM_ALLTMNT { get; set; }
        public decimal? AM_AWRD_ALLTMNT { get; set; }
        public decimal? AM_PEND_ALLTMNT { get; set; }
        public decimal? AM_RCPMNT { get; set; }
        public string CD_ADVRS_GUARD { get; set; }
        public string CD_ALLTMNT_TYPE { get; set; }
        public DateTime? DT_CASE_STTS { get; set; }
        public DateTime? DT_CERT_END { get; set; }
        public DateTime? DT_CERT_STRT { get; set; }
        public DateTime? DT_STRT_ISSNC { get; set; }
        public string TX_PND_RSN { get; set; }
        public string FL_SPECIAL_REOPEN { get; set; }
        public DateTime? DT_LATEST_CLOSURE { get; set; }
        public string CD_ISS_TYPE { get; set; }
        public string CD_EXPEDITE { get; set; }

        public virtual REF_RJCTN_DNL_TERM CD_ { get; set; }
        public virtual REF_PAST_DUE_RSN CD_PAST_DUE_RSNNavigation { get; set; }
        public virtual CASE ID_CASE_NMBRNavigation { get; set; }
        public virtual REF_CASE_STATUS_TYPE REF_CASE_STATUS_TYPE { get; set; }
        public virtual REF_SPCL_REOPEN_RSN ID_SPCL_REOPEN_RSNNavigation { get; set; }
    }
}