// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class CASE_BUDDY
    {
        public int ID_CASE { get; set; }
        public string CASE_LAST_NAME { get; set; }
        public string CASE_FIRST_NAME { get; set; }
        public string CASE_MIDDLE_INITIAL { get; set; }
        public string CASE_BENEFIT_MONTH { get; set; }
        public string CASE_BENEFIT_TYPE { get; set; }
        public string CLIENT_LAST_NAME { get; set; }
        public string CLIENT_FIRST_NAME { get; set; }
        public string CLIENT_MIDDLE_INITIAL { get; set; }
        public string CLIENT_GENDER { get; set; }
        public string CLIENT_SSN { get; set; }
        public string CLIENT_DOB { get; set; }
        public string CLIENT_ELIGIBLE_INDICATOR { get; set; }
        public string STATE_ABBREVIATION { get; set; }
        public string CLIENT_SSN_VERIFICATION_FLAG { get; set; }
        public string CASE_PHYSICAL_ADDRESS_STREET1 { get; set; }
        public string CASE_PHYSICAL_ADDRESS_STREET2 { get; set; }
        public string CASE_PHYSICAL_ADDRESS_CITY { get; set; }
        public string CASE_PHYSICAL_ADDRESS_STATE { get; set; }
        public string CASE_PHYSICAL_ADDRESS_ZIP { get; set; }
        public string CASE_MAILING_ADDRESS_STREET1 { get; set; }
        public string CASE_MAILING_ADDRESS_STREET2 { get; set; }
        public string CASE_MAILING_ADDRESS_CITY { get; set; }
        public string CASE_MAILING_ADDRESS_STATE { get; set; }
        public string CASE_MAILING_ADDRESS_ZIP { get; set; }
    }
}