// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class chk_OACIS_OilSpillCasesResult
    {
        public decimal NO_CASE { get; set; }
        public decimal? NO_CASE_CHCKDGT { get; set; }
        public string MEMBER_NAME { get; set; }
        public DateTime? DT_APPRVL { get; set; }
    }
}
