// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Chk_INSRNC_PRVDR_CNTResult
    {
        public int? Mnthcnt { get; set; }
    }
}
