// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Chk_StatusResult
    {
        public string descr { get; set; }
        public string cntydescription { get; set; }
        public int? TotalCnt { get; set; }
    }
}
