// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class COVERED_ITEMS
    {
        public int ID_CVRD_ITEMS { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string FL_SGND_SUD { get; set; }
        public string FL_UNDRSTNDS_GOOD { get; set; }
        public string FL_UNDRSTNDS_LMTD { get; set; }
        public string FL_UNDRSTNDS_POOR { get; set; }
        public string FL_UNDRSTNDS_NOT_CPBL { get; set; }
        public string TX_UNDRSTNDS_WHY { get; set; }
        public string FL_DSCSSD_PRMPTNSS { get; set; }
        public string FL_DSCSSD_VRBLE_ISSNC { get; set; }
        public string FL_DSCSSD_ISS_HOURS { get; set; }
        public string FL_DSCSSD_CHNG_RPRTNG_RQRMNTS { get; set; }
        public string FL_DSCSSD_CHNG_RPRT_GVN { get; set; }
        public string FL_DSCSSD_ATHRZD_RPRSNTTV { get; set; }
        public string FL_DSCSSD_ELGBL_FOODS { get; set; }
        public string FL_DSCSSD_CVL_RGHTS { get; set; }
        public string FL_DSCSSD_RIGHTS_RSPNSBLTS { get; set; }
        public string FL_DSCSSD_WORK_RGSTRTN { get; set; }
        public string FL_DSCSSD_VLNTRY_QUIT { get; set; }
        public string FL_DSCSSD_SEMI_ANNL_RPRTNG { get; set; }
        public string FL_DSCSSD_VNDR_PYMNT_RMBRSMNT { get; set; }
        public string FL_DSCSSD_FA_VIDEO { get; set; }
        public string FL_DSCSSD_DSGNTD_HH { get; set; }
        public string FL_DSCSSD_CLNT_WTHDRWL { get; set; }
        public string FL_DSCSSD_VRFCTN_PSTPN { get; set; }
        public string TX_DSCSSD_OTHR { get; set; }
        public string FL_DSCSSD_EXPNS_VRFCTNS { get; set; }
        public string TX_SRGiven { get; set; }

        public virtual CASE ID_CASE_NMBRNavigation { get; set; }
    }
}