// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class CS_DPNDNTS
    {
        public int ID_CS_DPNDNTS { get; set; }
        public int? ID_DPNDNT { get; set; }
        public int ID_CS_AMNT { get; set; }
        public int? ID_MMBR { get; set; }

        public virtual CS_AMOUNT ID_CS_AMNTNavigation { get; set; }
        public virtual OUTSIDE_DEPENDENT ID_DPNDNTNavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
    }
}