// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class CS_PAYER_RECIPIENT
    {
        public CS_PAYER_RECIPIENT()
        {
            COURT_ORDERED_AMOUNT = new HashSet<COURT_ORDERED_AMOUNT>();
            CS_AMOUNT = new HashSet<CS_AMOUNT>();
        }

        public int ID_CS_PAYER_RCPNT { get; set; }
        public int ID_OBLGTN_RSN { get; set; }
        public string FL_PAYER { get; set; }
        public string NM_PAYER_RCPNT_LST { get; set; }
        public string NM_PAYER_RCPNT_FRST { get; set; }
        public string NM_PAYER_RCPNT_MDL { get; set; }
        public string NM_PAYER_RCPNT_SFX { get; set; }

        public virtual ICollection<COURT_ORDERED_AMOUNT> COURT_ORDERED_AMOUNT { get; set; }
        public virtual ICollection<CS_AMOUNT> CS_AMOUNT { get; set; }
    }
}