// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class dba_SearchCachedPlansResult
    {
        public string SQL { get; set; }
        public string cacheobjtype { get; set; }
        public string objtype { get; set; }
        public string DatabaseName { get; set; }
        [Column("Plan usage")]
        public int Planusage { get; set; }
        public string query_plan { get; set; }
    }
}
