// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class DEPENDENT_CARE_OTHER_PAYER
    {
        public DEPENDENT_CARE_OTHER_PAYER()
        {
            UNEARNED_INCOME = new HashSet<UNEARNED_INCOME>();
        }

        public short ID_DC_OTHR_PAY { get; set; }
        public int ID_DPNDNT_CARE { get; set; }
        public int ID_MMBR { get; set; }
        public decimal? AM_DC_OTHR_PAY { get; set; }
        public DateTime? DT_DC_OTHR_PAYER { get; set; }
        public string FL_DC_PAY_MMBR { get; set; }
        public decimal? ID_FRQNCY_DC_OTHR_PAYER { get; set; }
        public short? ID_VRFCTN_DC_OTHR_PAYER { get; set; }
        public string TX_VRFCTN_DC_OTHR_PAYER { get; set; }

        public virtual DEPENDENT_CARE ID_DPNDNT_CARENavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual ICollection<UNEARNED_INCOME> UNEARNED_INCOME { get; set; }
    }
}