// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class DEPENDENT_CARE
    {
        public DEPENDENT_CARE()
        {
            AU_DEPENDENT_CARE = new HashSet<AU_DEPENDENT_CARE>();
            DEPENDENT_CARE_OTHER_PAYER = new HashSet<DEPENDENT_CARE_OTHER_PAYER>();
        }

        public int ID_DPNDNT_CARE { get; set; }
        public int? ID_DPNDNT { get; set; }
        public int? ID_MMBR { get; set; }
        public int? ID_MMBR1 { get; set; }
        public int ID_PRVDR_NAME { get; set; }
        public decimal? AM_DPNDNT_CARE_EXPNS { get; set; }
        public decimal? AM_PAID { get; set; }
        public decimal? AM_PAID_MNTHLY { get; set; }
        public string FL_ASSSTD_BY_OTHR { get; set; }
        public decimal? ID_FRQNCY_DC_EXPNS { get; set; }
        public decimal? ID_FRQNCY_DC_PAID { get; set; }
        public short? ID_VRFCTN_DC { get; set; }
        public string CD_MONTH { get; set; }
        public string FL_OUTSIDE_DEP_PYMNT { get; set; }
        public string TX_VRFCTN_DC { get; set; }

        public virtual OUTSIDE_DEPENDENT ID_DPNDNTNavigation { get; set; }
        public virtual MEMBER ID_MMBR1Navigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual REF_PROVIDER_NAME ID_PRVDR_NAMENavigation { get; set; }
        public virtual ICollection<AU_DEPENDENT_CARE> AU_DEPENDENT_CARE { get; set; }
        public virtual ICollection<DEPENDENT_CARE_OTHER_PAYER> DEPENDENT_CARE_OTHER_PAYER { get; set; }
    }
}