// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class DISASTER_COUNTIES
    {
        public int ID_DISASTER_CNTY { get; set; }
        public int ID_DISASTER { get; set; }
        public string CD_CNTY { get; set; }
    }
}