// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class DISASTER
    {
        public int ID_DISASTER { get; set; }
        public string NM_DISASTER { get; set; }
        public DateTime? DT_DISASTER_BEGIN { get; set; }
        public DateTime? DT_DISASTER_END { get; set; }
        public string TX_DISASTER_DESC { get; set; }
        public string FL_CANCELLED { get; set; }
    }
}