// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class EMPLOYER
    {
        public int ID_EMPLOYER { get; set; }
        public decimal? CD_CNTY { get; set; }
        public string NM_EMPLYR { get; set; }
        public string NO_EMPLYR_PHONE { get; set; }
        public string AD_STREET1 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
    }
}