// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Expense_Proration_CRResult
    {
        public Nullable<int> ID_CASE_NMBR { get; set; }
        public Nullable<int> PAYING_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string CD_CASE_CRTD { get; set; }
        public string CD_MONTH { get; set; }
        public decimal BILLED_AMNT { get; set; }
        public decimal PAID_AMNT { get; set; }
        public decimal PRRTD_1 { get; set; }
        public decimal PRRTD_2 { get; set; }
        public Nullable<int> SH_1 { get; set; }
        public Nullable<int> SH_2 { get; set; }
        public Nullable<int> PT_1 { get; set; }
        public Nullable<int> PT_2 { get; set; }
        public Nullable<int> PI_1 { get; set; }
        public Nullable<int> PI_2 { get; set; }
        public Nullable<int> PO_1 { get; set; }
        public Nullable<int> PO_2 { get; set; }
        public string CD_VRFCTN_DETAIL_DSCR { get; set; }
    }
}
