// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class FORM_APPOINTMENT
    {
        public string NO_CASE { get; set; }
        public string FL_OFFICE { get; set; }
        public DateTime? DT_OFF_IVIEW { get; set; }
        public DateTime? DT_TELE_IVIEW { get; set; }
        public string TXT_WRKR_NOTES { get; set; }
        public string ALT_OFFICE_NO { get; set; }
    }
}