// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_VERIFICATIONS_FASTATResult
    {
        public int ID_MMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public int? ID_VRFCTN_ALIEN_STTS { get; set; }
        public string FLGALIEN { get; set; }
        public int? FAVER { get; set; }
        public int FAID { get; set; }
        public string FLGLSTMNTH { get; set; }
        public int? ID_VRFCTN_STUDENT { get; set; }
        public int ID_STDNT { get; set; }
        public string TXTDETAIL { get; set; }
    }
}
