// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_UTILITY_TYPEResult
    {
        public int ID_UTLTY_TYPE { get; set; }
        public string CD_UTLTY_TYPE { get; set; }
    }
}
