// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_VERIFICATION_SUBTYPE_resourcesResult
    {
        public decimal ID_REF_VRFCTN_SUBTYPE { get; set; }
        public decimal ID_REF_VRFCTN_TYPE { get; set; }
        public string CD_REF_VRFCTN_SUBTYPE { get; set; }
    }
}
