// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_TFP_LIMITResult
    {
        public decimal ID_REF_TFP_LIMIT { get; set; }
        public decimal? AM_TFP_LIMIT { get; set; }
        public decimal? NO_HH_SIZE { get; set; }
    }
}
