// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_FDRL_MLGE_RTResult
    {
        public short ID_REF_FDRL_MLG_RATE { get; set; }
        public decimal? AM_FDRL_MLG_RATE { get; set; }
        public DateTime? DT_EFFCTV { get; set; }
    }
}
