// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SANCTION_TYPE_TransResResult
    {
        public short ID_REF_SNCTN_TYPE { get; set; }
        public string CD_SNCTN_TYPE { get; set; }
    }
}
