// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class get_REGISTER_APP_TO_SCIIIResult
    {
        public int ID_NEWCASE { get; set; }
        public string ID_USER { get; set; }
        public string NO_CASE { get; set; }
        public string NO_CASE_CHCKDGT { get; set; }
        public string COUNTY_SUBMIT { get; set; }
        public string COUNTY_OFFICE { get; set; }
        public string CD_SOURCE { get; set; }
        public string CD_LANGUAGE { get; set; }
        public string DHR_APPLICATION_TYPE { get; set; }
        public string DHR_SIGNED_DATE { get; set; }
        public string ALL_MAILING_ADDR1 { get; set; }
        public string ALL_MAILING_ADDR2 { get; set; }
        public string ALL_MAILING_CITY { get; set; }
        public string ALL_MAILING_STATE { get; set; }
        public string ALL_MAILING_ZIP { get; set; }
        public string ALL_MAILING_ZIP4 { get; set; }
        public string ALL_AUTH_REP_FIRST_NAME { get; set; }
        public string ALL_AUTH_REP_MIDDLE_NAME { get; set; }
        public string ALL_AUTH_REP_LAST_NAME { get; set; }
        public string AR_NAME { get; set; }
        public string ALL_EBT_REP_FIRST_NAME { get; set; }
        public string ALL_EBT_REP_MIDDLE_NAME { get; set; }
        public string ALL_EBT_REP_LAST_NAME { get; set; }
        public string EBT_NAME { get; set; }
        public int? DHR_HOH_PERSON_ID { get; set; }
        public int? DHR_APPLICANT_PERSON_ID { get; set; }
        public int? ALL_HOH_ID { get; set; }
        public int? NBR_IN_HH { get; set; }
        public string SCI_RCTYOFF { get; set; }
        public string SCI_SPECDT { get; set; }
        public string SCI_APPSTS { get; set; }
        public string SCI_PROSTD { get; set; }
        public string SCI_HHTYP { get; set; }
        public string SCI_HOMELS { get; set; }
        public string SCI_WORKER { get; set; }
        public string SCI_APTDT { get; set; }
        public string SCI_BATTER { get; set; }
        public string SCI_DENY { get; set; }
        public string SCI_APTYPE { get; set; }
        public string SCI_EXPDT { get; set; }
        public string SCI_PASS { get; set; }
        public string SCI_ERROR_MSG { get; set; }
        public int? SCI_NBR_IN_HH { get; set; }
        public string ALL_RESIDENCE_COUNTY { get; set; }
        public string ALL_RESIDENCE_OFFICE { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
