// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REGISTER_UTILITYEXPENSE_ByID_NEWCASEResult
    {
        public int ID_NEWMBR { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public decimal? PHONE_AMOUNT { get; set; }
        public decimal? ELECTRICITY_AMOUNT { get; set; }
        public decimal? GAS_AMOUNT { get; set; }
        public decimal? OIL_AMOUNT { get; set; }
        public decimal? WATER { get; set; }
        public decimal? GARBAGE_AMOUNT { get; set; }
        public string AIR_CONDITIONING { get; set; }
        public string LHEAP_PAYMENT { get; set; }
        public string LHEAP_ANTICIPATED { get; set; }
    }
}
