// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_TRIPResult
    {
        public int ID_TRIPS { get; set; }
        public int ID_PRVDR_NAME { get; set; }
        public decimal? AM_FLAT_FEE { get; set; }
        public decimal? AM_PAY_MILES_MNTHLY { get; set; }
        public string FL_DRVS_SELF { get; set; }
        public string FL_PAY_FLAT_FEE { get; set; }
        public string FL_PAY_PER_MILE { get; set; }
        public short? ID_VRFCTN_TRIP { get; set; }
        public decimal? NO_MILES_PER_MNTH { get; set; }
    }
}
