// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_VERIFICATIONS_RSCRResult
    {
        public short ID_RSRC { get; set; }
        public short ID_RSRC_CODE { get; set; }
        public short? ID_VRFCTN_RSRC { get; set; }
        public string CD_MONTH { get; set; }
        public int ID_MMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public string TX_VRFCTN_RSRC { get; set; }
    }
}
