// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MMBRS_NOT_IN_SCI_II_BYCASENOResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public short ID_RACE_CODE { get; set; }
        public short ID_REF_CERT_ELIG { get; set; }
        public short ID_WORK_CODE { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
        public short? ID_WORK_CODE_MNTH2 { get; set; }
        public string CD_CASE_CRTD { get; set; }
        public decimal? CD_EDCTN_LVL { get; set; }
        public string CD_SEX { get; set; }
        public DateTime? DT_BRTH { get; set; }
        public string FL_ABAWD { get; set; }
        public string FL_CLOSE_RLTN { get; set; }
        public string CD_CNVCTD_FLN { get; set; }
        public string FL_CTGRCLLY_ELGBL { get; set; }
        public string FL_CRRNT_FS_CRTFD { get; set; }
        public string FL_DHR_EMPL { get; set; }
        public string CD_DSQLFD_PRTCPNT { get; set; }
        public string FL_ELGBL_ALIEN { get; set; }
        public string CD_FLEEING_VLTR { get; set; }
        public string FL_FRMR_HH_MMBR { get; set; }
        public string CD_FRDLNT_MSRPRSNTTN { get; set; }
        public string FL_GIVE_FA_MONEY { get; set; }
        public string FL_GROUP_HOME { get; set; }
        public string FL_HOH { get; set; }
        public string FL_IN_SCHOOL { get; set; }
        public string FL_MGRNT_SSNL { get; set; }
        public string FL_NON_MMBR { get; set; }
        public string FL_NON_MMBR_RSDNT { get; set; }
        public string FL_PAYS_BILLS { get; set; }
        public string FL_PAYS_MEAL { get; set; }
        public string FL_PAYS_ROOM { get; set; }
        public string FL_PRNTL_GDNC { get; set; }
        public string FL_PRCHS_PRPRS { get; set; }
        public string CD_QLTY_SLLNG { get; set; }
        public string FL_RM { get; set; }
        public string CD_RSDNT_TRTMNT { get; set; }
        public string FL_SNCTN { get; set; }
        public string CD_STMPS_MISUSE { get; set; }
        public string FL_US_CTZN { get; set; }
        public string FL_WRK_RGSTRTN_EXMPT { get; set; }
        public string FL_WRKNG { get; set; }
        public short? ID_VRFCTN_ALIEN_STTS { get; set; }
        public short? ID_VRFCTN_EXPDT { get; set; }
        public string NO_SSN { get; set; }
        public string NO_CELLPHONE { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public string AGE { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
