// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_CASE_STATUSResult
    {
        public int ID_CASE_NMBR { get; set; }
        public decimal ID_REF_CASE_STATUS_TYPE { get; set; }
        public decimal? AM_ALLTMNT { get; set; }
        public decimal? AM_AWRD_ALLTMNT { get; set; }
        public decimal? AM_PEND_ALLTMNT { get; set; }
        public string CD_ADVRS_GUARD { get; set; }
        public string CD_ALLTMNT_TYPE { get; set; }
        public short? ID_SPCL_REOPEN_RSN { get; set; }
        public string CD_PAST_DUE_RSN { get; set; }
        public string CD_RJCTN_CLSR { get; set; }
        public string CD_DENIAL { get; set; }
        public string CD_TRMNTN { get; set; }
        public DateTime? DT_CASE_STTS { get; set; }
        public DateTime? DT_CERT_END { get; set; }
        public DateTime? DT_CERT_STRT { get; set; }
        public DateTime? DT_STRT_ISSNC { get; set; }
        public string TX_PND_RSN { get; set; }
        public decimal? AM_RCPMNT { get; set; }
        public string CD_ISS_TYPE { get; set; }
        public string CD_EXPEDITE { get; set; }
        //public decimal ID_REF_CASE_STATUS_TYPE { get; set; }
        public string CD_CASE_STTS_TYPE { get; set; }
        public string TX_CASE_STTS_DSCR { get; set; }
    }
}
