// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SHLTR_NOTESResult
    {
        public short ID_REF_SHLTR_OTHR { get; set; }
        public string TX_SHLTR_OTHR { get; set; }
    }
}
