// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_DPNDNT_RECORD_OTHERResult
    {
        public short ID_DC_OTHR_PAY { get; set; }
    }
}
