// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SumPropertyExpenseResult
    {
        public decimal? SHELTER_EXP_SUM { get; set; }
        public short ID_SHLTR_EXPNS_TYPE { get; set; }
        public string CD_SHLTR_EXPNS_TYPE { get; set; }
        public string EXP_TYPE { get; set; }
    }
}
