// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_IEVS_TRAKResult
    {
        public string ID_SSN_IEVS { get; set; }
        public string CD_SSN_VRFY { get; set; }
    }
}
