// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_CASE_NOTES_SYNCResult
    {
        public int ID_CASE_NOTE { get; set; }
        public int ID_MMBR { get; set; }
        public DateTime? DT_CASE_NOTE { get; set; }
        public string CD_RJCTN_CLSR_SYNC { get; set; }
        public string CD_RJCTN_DESC { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public decimal NO_CASE { get; set; }
    }
}
