// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_Form879_ByNoCaseResult
    {
        public string NO_CASE { get; set; }
        public DateTime? DT_STAMPS_END { get; set; }
        public string FL_BENEFITS { get; set; }
        public string FL_INTERVIEW { get; set; }
        public string FL_NOTIFY { get; set; }
        public DateTime? DT_BENEFITS { get; set; }
        public DateTime? DT_INTERVIEW { get; set; }
        public string FL_OFF { get; set; }
    }
}
