// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_VRFCTNS_UNEARNResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public int? TABLE_ID { get; set; }
        public string UNERND_CAT { get; set; }
        public string CD_MONTH { get; set; }
        public string UI_TYPE { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public string TXT_DTL_CASE { get; set; }
    }
}
