// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_CASEVOTE_INFOResult
    {
        public string VOTER_ANS { get; set; }
        public string VOTER_TXT { get; set; }
    }
}
