// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_COUNTY_STATEResult
    {
        public short ID_CNTY_STATE { get; set; }
        public string ID_REF_STATE { get; set; }
        public decimal? CD_CNTY { get; set; }
        public string CD_CNTY_DSCR { get; set; }
    }
}
