// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_WORKREGCODE_MEMBERResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public short ID_WORK_CODE { get; set; }
        //public short ID_WORK_CODE { get; set; }
        public string CD_WORK { get; set; }
    }
}
