// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_VERIFICATIONS_INSRNCResult
    {
        public short? ID_VRFCTN_INSRNC { get; set; }
        public int ID_INSRNC { get; set; }
        public int ID_MMBR { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
