// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_VRFCTNS_REF_RSRCResult
    {
        public string TX_RSRC_DSCR { get; set; }
        public string CD_RSRC_CODE { get; set; }
    }
}
