// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_GRAND_TTL_MDCL_EXP_IntBudSumPrintResult
    {
        public decimal MED_EXP_M1 { get; set; }
        public int TOT_MEALS_M1 { get; set; }
        public decimal MED_EXP_M2 { get; set; }
        public int TOT_MEALS_M2 { get; set; }
    }
}
