// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_UNEARN_INC_INC_SUMResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string FL_HOH { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public int? ID_CS_AMNT { get; set; }
        public short? ID_DC_OTHR_PAY { get; set; }
        public short? ID_INSRNC_OTHR_PAYER { get; set; }
        public short? ID_ME_OTHR_PAYER { get; set; }
        public int? ID_REF_UNERND_SUBTYPE { get; set; }
        public short? ID_SHLTR_EXPNS_OTHR_PAYER { get; set; }
        public short? ID_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public decimal? AM_UNERND_MNTHLY { get; set; }
        public decimal? AM_UNERND_VALUE2 { get; set; }
        public string CD_MONTH { get; set; }
        public decimal? AM_UNERND_VALUE1 { get; set; }
    }
}
