// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_OACIS_MODULEResult
    {
        public string CD_MODULE_PRED { get; set; }
        public string CD_REF_MODULE { get; set; }
        public string TX_REF_MODULE { get; set; }
        public string CD_MODULE_ORDER { get; set; }
        public string CD_MODULE_NEXT { get; set; }
        public string CD_MODULE_LCTN { get; set; }
    }
}
