// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_VRFCTM_CASE_CRYSTLRPRTResult
    {
        public int ID_CASE_NMBR { get; set; }
        public short ID_CNTY_STATE { get; set; }
        public decimal? CD_TRCKNG_OFFC { get; set; }
        public DateTime? DT_APPNTMNT { get; set; }
        public DateTime? DT_RQRD_VRCTN { get; set; }
        public string FL_AR_FORM_SGND { get; set; }
        public string FL_HH_HMLS { get; set; }
        public decimal NO_CASE { get; set; }
        public string NO_HOME_TEL { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        public int ID_MMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public int ID_ADDRSS { get; set; }
        public string AD_STREET1 { get; set; }
        public string AD_STREET2 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
        public string AD_ZIP_4 { get; set; }
    }
}
