// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_PIV_MMBR_RLTNResult
    {
        public short ID_RLTN { get; set; }
        public int ID_MMBR1 { get; set; }
        public int ID_MMBR2 { get; set; }
        public string FL_NRST_RLTN { get; set; }
    }
}
