// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_INSTRUCTIONSResult
    {
        public short ID_INSTRCTN { get; set; }
        public string CD_INSTRCTN_TYPE { get; set; }
        public string TX_INSTRCTN_TYPE { get; set; }
    }
}
