// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_PROVIDER_NAMEResult
    {
        public int ID_PRVDR_NAME { get; set; }
        public short ID_PRVDR_TYPE { get; set; }
        public string NM_PRVDR { get; set; }
    }
}
