// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_UTLTY_EXP_ALL_IDCASEResult
    {
        public int ID_UTLTY_EXPNS { get; set; }
        public int ID_MMBR1 { get; set; }
        public int? ID_MMBR2 { get; set; }
        public decimal? ID_UTLTY_DDCTN { get; set; }
        public int ID_UTLTY_TYPE { get; set; }
        public decimal? AM_ACTL_UTLTY_AVG { get; set; }
        public decimal? AM_UTLTY_EXPNS { get; set; }
        public decimal? AM_UTLTY_EXPNS_MNTHLY { get; set; }
        public decimal? AM_UTLTY_EXPNS_TTL_ALLWBL { get; set; }
        public string CD_MONTH { get; set; }
        public DateTime? DT_LIHEAP_RCVD { get; set; }
        public string FL_AC_BLLD { get; set; }
        public string FL_ASSSTD_BY_OTHR { get; set; }
        public string FL_BUA { get; set; }
        public string FL_HTNG_BLLD { get; set; }
        public string FL_LIHEAP { get; set; }
        public string FL_NM_OUTSIDE_HH_UE { get; set; }
        public string FL_PHONE_STNDRD { get; set; }
        public string FL_SUA_ELGBL { get; set; }
        public string FL_UTLTY_PASSTHRU { get; set; }
        public decimal? ID_FRQNCY_UTLTY_EXPNS { get; set; }
        public short? ID_VRFCTN_UTLTY_EXPNS { get; set; }
        public string TX_VRFCTN_UTLTY_EXPNS { get; set; }
        public short? IDUEOP { get; set; }
        public int? IDUE { get; set; }
        public decimal? AM_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public DateTime? DT_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public string FL_ALLPART_PAY_UTLTY_EXPNS { get; set; }
        public string FL_OUTSIDE_RSDNT_UE { get; set; }
        public string FL_UTLTY_PAY_MMBR { get; set; }
        public decimal? ID_FRQNCY_UTLTY_EXPNS_OP { get; set; }
        public short? ID_VRFCTN_UTLTY_EXPNS_OP { get; set; }
        public string TX_VRFCTN_UTLTY_EXPNS_OP { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public short? UIIDUEOP { get; set; }
        public int? ID_REF_UNERND_SUBTYPE { get; set; }
        public decimal? AM_UNERND_MNTHLY { get; set; }
        public DateTime? DT_RCVD { get; set; }
        public string TX_VRFCTN_UNERND_INCM { get; set; }
        public int? ID_CASE_NMBR { get; set; }
        public short? ID_REF_CERT_ELIG { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
