// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_CASE_NOTESResult
    {
        public int ID_CASE_NOTE { get; set; }
        public int ID_MMBR { get; set; }
        public short ID_CASE_CTGRY { get; set; }
        public DateTime? DT_CRTD { get; set; }
        public DateTime? DT_CASE_NOTE { get; set; }
        public DateTime? DT_MDFD { get; set; }
        public string NM_CRTD { get; set; }
        public string NM_MDFD { get; set; }
        public string TX_CASE_NOTE_DSCR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
        public decimal NO_CASE { get; set; }
        public string CtgryDsc { get; set; }
    }
}
