// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_EARN_INC_VRFCTNSResult
    {
        public int ID_MMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public int ID_EMPLYMNT { get; set; }
        public decimal ID_INCM_TYPE { get; set; }
        public int? ID_VRFCTN_EMPLYMNT { get; set; }
        public string NM_EMPLYR { get; set; }
        public int STRIKEID { get; set; }
        public int? STRIKEVRF { get; set; }
        public string TXTDETAIL { get; set; }
    }
}
