// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SHLTR_EXP_ALL_IDMMBRResult
    {
        public int ID_SHLTR_EXPNS { get; set; }
        public int ID_MMBR1 { get; set; }
        public int? ID_MMBR2 { get; set; }
        public short ID_OWNRSHP { get; set; }
        public short ID_SHLTR_DWELLNG_TYPE { get; set; }
        public short ID_SHLTR_EXPNS_TYPE { get; set; }
        public decimal? AM_ACTL_SHLTR_EXPNS { get; set; }
        public decimal? AM_SHLTR_EXPNS_MNTHLY { get; set; }
        public string CD_MONTH { get; set; }
        public string FL_ASSSTD_BY_OTHR { get; set; }
        public string FL_NM_OUTSIDE_HH { get; set; }
        public string FL_SHLTR_PASSTHRU { get; set; }
        public decimal? ID_FRQNCY_SHLTR_EXPNS { get; set; }
        public short? ID_VRFCTN_SHLTR_EXPNS { get; set; }
        public string TX_VRFCTN_SHLTR_EXPNS { get; set; }
        public short? SOIDSEOP { get; set; }
        public int? SOIDSE { get; set; }
        public decimal? AM_SHLTR_EXPNS_OTHR_PAYER { get; set; }
        public DateTime? DT_SHLTR_EXPNS_OTHR_PAYER { get; set; }
        public string FL_OUTSIDE_RSDNT { get; set; }
        public string FL_SHLTR_EXPNS_PAY_MMBR { get; set; }
        public decimal? ID_FRQNCY_SHLTR_EXPNS_OP { get; set; }
        public short? ID_VRFCTN_SHLTR_EXPNS_OP { get; set; }
        public string TX_VRFCTN_SHLTR_EXPNS_OP { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public int? ID_REF_UNERND_SUBTYPE { get; set; }
        public short? UIIDSEOP { get; set; }
        public decimal? AM_UNERND_MNTHLY { get; set; }
        public string UECD { get; set; }
        public DateTime? DT_RCVD { get; set; }
        public decimal? ID_FRQNCY_RECPT { get; set; }
        public short? ID_VRFCTN_UNERND_INCM { get; set; }
        public string TX_VRFCTN_UNERND_INCM { get; set; }
        public short? ID_REF_SHLTR_OTHR { get; set; }
        public int? SNIDSE { get; set; }
        public string TX_SHLTR_OTHR { get; set; }
        public int? ID_CASE_NMBR { get; set; }
        public short? ID_REF_CERT_ELIG { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
