// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SumUnearnedIncomeData_VAResult
    {
        public int ID_MMBR { get; set; }
        public decimal? TOTAL_VA_INC_AMNT { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
