// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_PROVIDER_TYPEResult
    {
        public short ID_PRVDR_TYPE { get; set; }
        public string CD_PRVDR_TYPE { get; set; }
        public string TX_PRVDR_DSCR { get; set; }
    }
}
