// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_ALL_VRFCTNS_CRYSTLRPTResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public string VRFCTN_TYPE { get; set; }
        public string VRFCN_INFO { get; set; }
        public string TXT_DETAIL { get; set; }
    }
}
