// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_ISSUANCE_HDR_byCASENOResult
    {
        public string CASENO { get; set; }
        public string ACDTE { get; set; }
        public string COUNTY { get; set; }
        public string ADMIN_1 { get; set; }
        public string NAME { get; set; }
        public string ADDR { get; set; }
        public string HHTYP { get; set; }
    }
}
