// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_ApplicationsFromInternet_ByDateRangeCtyResult
    {
        public string County { get; set; }
        public int? Number { get; set; }
    }
}
