// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REGISTER_VOLUNTARYQUIT_ByID_NEWCASEResult
    {
        public int ID_NEWMBR { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public int ID_VOLUNTARYQUIT { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_PHONE_NUMBER { get; set; }
        public string QUIT_REASON { get; set; }
        public string QUIT_DATE { get; set; }
    }
}
