// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_CASE_CTGRY_BYDSCRResult
    {
        public short ID_CASE_CTGRY { get; set; }
    }
}
