// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_OACICS_ERRORS_BYIDUSerResult
    {
        public int ID_ERROR { get; set; }
        public string CD_REF_MODULE { get; set; }
        public string ID_USER { get; set; }
        public DateTime? DT_ERROR { get; set; }
        public string TX_ERROR { get; set; }
        public string TX_TARGET { get; set; }
    }
}
