// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MMBR_NM_ONBILLResult
    {
        public int ID_MMBR { get; set; }
        public short ID_REF_CERT_ELIG { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
