// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_UTLTY_RECORD_OTHERResult
    {
        public short ID_UTLTY_EXPNS_OTHR_PAYER { get; set; }
    }
}
