// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SumUtilitiesResult
    {
        public decimal? UTILITY_SUM { get; set; }
        public decimal? ID_UTLTY_DDCTN { get; set; }
        public decimal? AM_UTLTY_DDCTN { get; set; }
        public string CD_UTLTY_DDCTN { get; set; }
    }
}
