// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_GRAND_TTL_MED_INSRNC_EXP_AwdDnyResult
    {
        public decimal? TTL_MNTHLY_INSRNC_EXPNSE { get; set; }
    }
}
