// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_Meals_Allowance_CRResult
    {
        public int? ID_CASE_NMBR { get; set; }
        public int MONTH1_TTL { get; set; }
        public int MONTH2_TTL { get; set; }
        public decimal? AM_TFP_LIMIT { get; set; }
    }
}
