// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REGISTER_ROOMERBOARDER_ByNOCASEResult
    {
        public int ID_NEWMBR { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public int ID_ROOMERORBOARDER { get; set; }
        public decimal? AMOUNT_PAID { get; set; }
        public string PAY_FREQUENCY { get; set; }
        public short? MEALS_PROVIDED { get; set; }
    }
}
