// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_VRFCTNS_UNERN_BY_IDCASEResult
    {
        public int ID_MMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public int? EMPVER { get; set; }
        public int? ID_EMPLYMNT { get; set; }
        public string FL_SELF_EMPLYD { get; set; }
        public string FL_TTL_RPRSNTTV_PAY { get; set; }
        public short? UNEARNVER { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public short? ID_VRFCTN_CS_AMNT { get; set; }
        public int? ID_CS_AMNT { get; set; }
        public short? ID_VRFCTN_DC_OTHR_PAYER { get; set; }
        public short? ID_DC_OTHR_PAY { get; set; }
        public short? ID_VRFCTN_INSRNC_OTHR_PAYER { get; set; }
        public short? ID_INSRNC_OTHR_PAYER { get; set; }
        public short? ID_VRFCTN_ME_OTHR_PAYER { get; set; }
        public short? ID_ME_OTHR_PAYER { get; set; }
        public short? ID_VRFCTN_SHLTR_EXPNS_OP { get; set; }
        public short? ID_SHLTR_EXPNS_OTHR_PAYER { get; set; }
        public short? ID_VRFCTN_UTLTY_EXPNS_OP { get; set; }
        public short? ID_UTLTY_EXPNS_OTHR_PAYER { get; set; }
    }
}
