// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_DependentsbyIdMmbr_09012009Result
    {
        public int ID_DPNDNT { get; set; }
        public int ID_MMBR { get; set; }
        public string NM_DPNDNT_LST { get; set; }
        public string NM_DPNDNT_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
        public string OUTSIDE_DPNDNT { get; set; }
    }
}
