// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_ID_NEWMBR_BY_IDNEWCASEResult
    {
        public int ID_NEWMBR { get; set; }
        public int? DEPENDENT_NMBR { get; set; }
    }
}
