// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_UTILITY_EXPENSE_OTHER_PAYERResult
    {
        public short ID_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public int ID_UTLTY_EXPNS { get; set; }
        public int ID_MMBR { get; set; }
        public decimal? AM_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public DateTime? DT_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public string FL_ALLPART_PAY_UTLTY_EXPNS { get; set; }
        public string FL_UTLTY_PAY_MMBR { get; set; }
        public decimal? ID_FRQNCY_UTLTY_EXPNS_OP { get; set; }
        public short? ID_VRFCTN_UTLTY_EXPNS_OP { get; set; }
    }
}
