// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REG_CASE_DENIALResult
    {
        public string ApplicationID { get; set; }
        public string NO_CASE { get; set; }
        public string NO_CASE_CHCKDGT { get; set; }
        public string CD_CNTY { get; set; }
        public string CD_OFF { get; set; }
        public string SSN { get; set; }
        public string DEP_NM_MMBR_LST { get; set; }
        public string DEP_NM_MMBR_FRST { get; set; }
        public string DEP_NM_MMBR_MDL { get; set; }
        public string DEP_NM_MMBR_SFX { get; set; }
        public string MEMBER_NAME { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
        public string AD_ZIP_4 { get; set; }
        public string WORKER { get; set; }
    }
}
