// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_AU_FORMS_OACIS_bytypeResult
    {
        public string CD_FORM { get; set; }
        public DateTime? DT_CREATED { get; set; }
        public DateTime? DT_MODIFIED { get; set; }
        public DateTime? DT_PRINTED { get; set; }
        public DateTime? DT_ADDI { get; set; }
    }
}
