// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_ALL_HLDYSResult
    {
        public short ID_HLDY_DATES { get; set; }
        public DateTime? DT_HLDY { get; set; }
        public string TX_HLDY_DSCR { get; set; }
    }
}
