// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_EMPLYMNT_TOTLS_BYIDCASENOResult
    {
        public int ID_MMBR { get; set; }
        public string ENAME { get; set; }
        public int? ECASE { get; set; }
        public decimal? THISMONTH { get; set; }
        public decimal? NEXTMONTH { get; set; }
    }
}
