// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_SANCTION_REASON_ResourcesResult
    {
        public decimal ID_REF_SNCTN_RSN { get; set; }
        public short ID_REF_SNCTN_TYPE { get; set; }
        public string TX_SNCTN_RSN { get; set; }
        public string CD_SNCTN_TYPE { get; set; }
    }
}
