// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MDCL_PRVDRS_BY_EXPNSTYPE_AND_MMBRResult
    {
        public int ID_PRVDR_NAME { get; set; }
        public string NM_PRVDR { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
