// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REGISTER_LIQUIDRESOURCE_ByID_NEWCASEResult
    {
        public int ID_NEWMBR { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public string TYPE_LR { get; set; }
        public decimal? AMOUNT_LR { get; set; }
        public string ADD_INFO_1 { get; set; }
        public string ADD_INFO_2 { get; set; }
        public string ADD_INFO_3 { get; set; }
        public string ADD_INFO_4 { get; set; }
    }
}
