// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_WAIVE_ADVERSE_ACTIONResult
    {
        public short ID_REF_WAIVE_ADVRS_ACTN { get; set; }
        public string CD_WAIVE_ADVRS_ACTN_RSN { get; set; }
        public string TX_ADVRS_ACTN_DSCR { get; set; }
    }
}
