// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MDCL_RX_AVG_MNTHLYResult
    {
        public decimal? MNTHLY_AVG { get; set; }
    }
}
