// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_CS_DPNDNTSResult
    {
        public int ID_CS_DPNDNTS { get; set; }
        public int? ID_DPNDNT { get; set; }
        public int ID_CS_AMNT { get; set; }
        public int? ID_MMBR { get; set; }
    }
}
