// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_FormAPPT_ByNoCaseResult
    {
        public string NO_CASE { get; set; }
        public string FL_OFFICE { get; set; }
        public DateTime? DT_OFF_IVIEW { get; set; }
        public DateTime? DT_TELE_IVIEW { get; set; }
        public string TXT_WRKR_NOTES { get; set; }
    }
}
