// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_EXCESS_RESOURCE_LIMITResult
    {
        public short ID_EXCSS_RSRC_LIMIT { get; set; }
        public string AM_MIN_EXCSS_RSRC_LIMIT { get; set; }
        public string AM_MAX_EXCSS_RSRC_LIMIT { get; set; }
        public string NO_MNTHS_DSQLFCTN { get; set; }
    }
}
