// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MMBR_MED_SUMMARYResult
    {
        public int ID_MMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public decimal? TTL_MNTHLY_EXPNSE { get; set; }
    }
}
