// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_STUDENT_CDMTH2Result
    {
        public int ID_STDNT { get; set; }
        public string CD_MONTH { get; set; }
    }
}
