// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GET_MMBR_CNTY_ADD_REGResult
    {
        public short? ID_CNTY_ADDRESS { get; set; }
        public string CntyAdd1 { get; set; }
        public string CntyAdd2 { get; set; }
        public string CntyZip { get; set; }
        public string CntyZip4 { get; set; }
        public string CntyCty { get; set; }
        public string NO_OFFICE_PHONE { get; set; }
        public string NO_OFFICE_FAX { get; set; }
        public string CD_CNTY_DSCR { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public string MEMBER_NAME { get; set; }
        public int? ID_ADDRSS { get; set; }
        public short? ID_CNTY_STATE { get; set; }
        public decimal? ID_REF_ADDRSS_TYPE { get; set; }
        public string AD_STREET1 { get; set; }
        public string AD_STREET2 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
        public string AD_ZIP_4 { get; set; }
        public string NO_HOME_TEL { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        public string DHR_HOME_PHONE_NUMBER { get; set; }
        public string DHR_WORK_PHONE_NUMBER { get; set; }
        public string DHR_MESSAGE_PHONE_NUMBER { get; set; }
        public string DHR_CELL_NUMBER { get; set; }
        public string FL_OFFICEINT { get; set; }
        public string DATE_NOMA { get; set; }
        public string TX_APPT_NOTES { get; set; }
        public string DT_CASE_APPTDATETIME { get; set; }
        public string APPTDATETIME { get; set; }
        public string SCI_DUEDT { get; set; }
        public string SCI_PROSTD { get; set; }
        public string SCI_APPDT { get; set; }
        public string ALT_OFFICE_NO { get; set; }
    }
}
