// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SECUREResult
    {
        public string ID_USER { get; set; }
        public string CD_ROLE { get; set; }
        public string FL_ACTIVE { get; set; }
        public string FL_SUPERVISOR { get; set; }
        public string CD_CNTY { get; set; }
        public string NM_FULL_NAME { get; set; }
        public string ID_PAYROLL { get; set; }
        public string TX_COMMENT { get; set; }
        public string FL_NEWUSER { get; set; }
        public string CD_PSSWRD { get; set; }
        public string CD_WRKR_NMBR { get; set; }
        public string FL_TEST { get; set; }
        public DateTime? DT_PSSWRD { get; set; }
        public string FL_WF { get; set; }
        public string FL_ADDI { get; set; }
        public string FL_DSNAP { get; set; }
    }
}
