// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_UNEARNED_PAYERResult
    {
        public int ID_UNERND_PAYER { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public short ID_REF_UNERND_PAYER_TYPE { get; set; }
        public string NM_UNERND_PAYER { get; set; }
    }
}
