// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REGISTER_SOU_ID_NEWCASEResult
    {
        public int ID_NEWMBR { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public string Q1 { get; set; }
        public string Q2 { get; set; }
        public string Q3 { get; set; }
        public string Q4 { get; set; }
        public string Q5 { get; set; }
        public string Q6 { get; set; }
        public string Q7 { get; set; }
        public string Q8 { get; set; }
        public string Q9 { get; set; }
        public string Q10 { get; set; }
        public string Q11 { get; set; }
        public string Q12 { get; set; }
        public string Q13 { get; set; }
        public string Q14 { get; set; }
        public string Q15 { get; set; }
        public string Q16 { get; set; }
        public string Q17 { get; set; }
        public string Q18 { get; set; }
    }
}
