// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_Form657_ByNoCaseResult
    {
        public decimal NO_CASE { get; set; }
        public string NO_TELEPHONE { get; set; }
        public DateTime? DT_NOTICE { get; set; }
        public DateTime? DT_FS_END { get; set; }
        public decimal? AM_FS_RCVD_MNTH_ONE { get; set; }
        public decimal? AM_FS_RCVD_MNTH_TWO { get; set; }
        public DateTime? DT_CERT_FROM { get; set; }
        public DateTime? DT_CERT_END { get; set; }
        public DateTime? DT_FS_REAPPLY { get; set; }
        public decimal? AM_BENE_CHNGE_FROM { get; set; }
        public decimal? AM_BENE_CHNGE_TO { get; set; }
        public DateTime? DT_BENE_EFFT { get; set; }
        public DateTime? DT_FS_BENE_STOP { get; set; }
        public DateTime? DT_FS_LAST_BENE { get; set; }
        public string TXT_FS_INFO_NEEDED { get; set; }
        public string TXT_FC_OTHR_ACT { get; set; }
        public string TXT_DEP_POLICY { get; set; }
        public string TXT_ACT_BECAUSE { get; set; }
        public string FL_FS_APPRV { get; set; }
        public string FL_FS_BENE { get; set; }
        public string FL_BENE_STOP { get; set; }
        public string FL_BENE_INFO { get; set; }
        public string FL_OTHR_ACT { get; set; }
        public string FL_ACT_BECAUSE { get; set; }
        public string FL_DEPT_POLICY { get; set; }
        public string FL_REV_ACT { get; set; }
    }
}
