// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GET_REG_CASE_APPTS_DENIALResult
    {
        public string NO_CASE { get; set; }
        public string NO_CASE_CHCKDGT { get; set; }
        public string COUNTY_OFFICE { get; set; }
        public string CD_REGISTRATION_STATUS { get; set; }
        public string DHR_SIGNED_DATE { get; set; }
        public string SCI_WORKER { get; set; }
        public string FL_HOH { get; set; }
        public string DHR_MEMBER_SSN { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
