// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_NO_OF_MEALS_LIMITResult
    {
        public decimal? AM_TFP_LIMIT { get; set; }
    }
}
