// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_INACTIVE_SCIIIResult
    {
        public string ID_SSN { get; set; }
        public decimal? CD_CHCK_DIGIT { get; set; }
        public decimal? CD_CNTY_SCIII { get; set; }
        public decimal? NO_INACTV_CASE { get; set; }
    }
}
