// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_INSRNC_PAYERResult
    {
        public decimal ID_INSRNC_PAYER { get; set; }
        public string CD_PAYER_DSCR { get; set; }
    }
}
