// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_ISSUANCE_byCASENOResult
    {
        public string ISS_CASENO { get; set; }
        public string ISS_ACDTE { get; set; }
        public string ISS_COUNTY { get; set; }
        public string ISS_ADMIN { get; set; }
        public string ISS_NAME { get; set; }
        public string ISS_ADDR { get; set; }
        public string ISS_HHTYP { get; set; }
        public string ISS_ACTON { get; set; }
        public string ISS_STID { get; set; }
        public string ISS_ISSTP { get; set; }
        public string ISS_IAMT { get; set; }
        public string ISS_RSTAT { get; set; }
        public string ISS_RECAT { get; set; }
        public string ISS_AMT { get; set; }
    }
}
