// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REGISTER_DEPENDENT_CARE_ByID_NEWCASEResult
    {
        public int ID_NEWMBR { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public int ID_DEPENDENTCARE { get; set; }
        public decimal? AMOUNT { get; set; }
        public string PAY_FREQUENCY { get; set; }
        public string SITTER_NAME { get; set; }
        public string SIITER_PHONE { get; set; }
    }
}
