// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_RESOURCE_TYPEResult
    {
        public short ID_RSRC_CODE { get; set; }
        public string TX_RSRC_DSCR { get; set; }
        public string CD_RSRC_CODE { get; set; }
    }
}
