// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MEAL_OTHERResult
    {
        public short ID_MEAL_OTHER { get; set; }
        public int? ID_CASE_NMBR { get; set; }
        public string NM_MEAL_OTHR_LST { get; set; }
        public string NM_MEAL_OTHR_FRST { get; set; }
        public string NM_MEAL_OTHR_MDL { get; set; }
        public string NM_MEAL_OTHR_SFX { get; set; }
        public string CD_MONTH { get; set; }
        public string CD_MONTH_TRANSLATED { get; set; }
    }
}
