// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_Registration_Form_MembersResult
    {
        public int ID_NEWCASE { get; set; }
        public string SCI_DEPNUM { get; set; }
        public string SCI_SSN { get; set; }
        public string SCI_DEPNAM { get; set; }
        public string SCI_SEX { get; set; }
        public string SCI_RACE { get; set; }
        public string SCI_DOB { get; set; }
        public string SCI_PACASE { get; set; }
        public string SCI_ELIG { get; set; }
    }
}
