// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_UTLTY_CDMTHResult
    {
        public int ID_UTLTY_EXPNS { get; set; }
        public int ID_MMBR1 { get; set; }
        public decimal? ID_UTLTY_DDCTN { get; set; }
        public int ID_UTLTY_TYPE { get; set; }
        public string CD_MONTH { get; set; }
        public int? ID_CASE_NMBR { get; set; }
    }
}
