// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_VER_DETAILBYIDResult
    {
        public decimal ID_REF_VRFCTN_SUBTYPE { get; set; }
        public string CD_VRFCTN_DETAIL_DSCR { get; set; }
    }
}
