// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REPORTINGResult
    {
        public int ID_RPRTNG { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string CD_RPRTNG_RQRMNT { get; set; }
        public DateTime? DT_RPRTNG { get; set; }
        public string TX_RPRTNG_RQRMNT_DSCR { get; set; }
    }
}
