// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_VERIFICATIONS_CASEResult
    {
        public int ID_CASE_NMBR { get; set; }
        public short? ID_VRFCTN_ATHRZD_RPRSNTTV { get; set; }
        public short? ID_VRFCTN_HH { get; set; }
        public short? ID_VRFCTN_HH_CMPSTN { get; set; }
        public short? ID_VRFCTN_HH_RSDNCY { get; set; }
        public short? TX_VRFCTN_HH { get; set; }
        public string TX_VRFCTN_HH_CMPSTN { get; set; }
        public string TX_VRFCTN_INTRVWEE { get; set; }
        public string TX_VRFCTN_RSDNCY { get; set; }
    }
}
