// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_RX_MEDL_EXP_ONGOINGResult
    {
        public int ID_ME_ONGOING { get; set; }
        public decimal? AM_MNTHLY_ONGOING { get; set; }
        public DateTime? DT_TRNSCTN { get; set; }
        public decimal? NO_OF_MNTHS { get; set; }
    }
}
