// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_VERIFICATION_DETAIL_PENDINGResult
    {
        public short ID_VRFCTN_DETAIL { get; set; }
    }
}
