// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_Registration_FormResult
    {
        public int ID_NEWCASE { get; set; }
        public string ID_USER { get; set; }
        public string NO_CASE { get; set; }
        public string SCI_CHKDGT { get; set; }
        public string SCI_CTYOFF { get; set; }
        public string SCI_TRANDT { get; set; }
        public string SCI_DUEDT { get; set; }
        public string SCI_NAME { get; set; }
        public string MEMBER_NAME { get; set; }
        public string SCI_RCTYOFF { get; set; }
        public string CD_LANGUAGE { get; set; }
        public string SCI_ADDR1 { get; set; }
        public string SCI_ADDR2 { get; set; }
        public string SCI_CITY { get; set; }
        public string SCI_ZIP5 { get; set; }
        public string SCI_ZIP4 { get; set; }
        public string SCI_SPECDT { get; set; }
        public string SCI_APPSTS { get; set; }
        public string SCI_APPDT { get; set; }
        public string SCI_PROSTD { get; set; }
        public string SCI_HHTYP { get; set; }
        public string SCI_HOMELS { get; set; }
        public string SCI_WORKER { get; set; }
        public string SCI_APTDT { get; set; }
        public string SCI_OFFICE { get; set; }
        public string SCI_BATTER { get; set; }
        public string SCI_DENY { get; set; }
        public string SCI_APTYPE { get; set; }
        public string SCI_EXPDT { get; set; }
        public string SCI_PASS { get; set; }
        public string SCI_AUTH1 { get; set; }
        public string SCI_AUTH2 { get; set; }
        public int? SCI_NBR_IN_HH { get; set; }
        public string SCI_ERROR_MSG { get; set; }
        public int? ID_DISASTER { get; set; }
        public string DHR_APPLICATION_TYPE { get; set; }
    }
}
