// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_NOTICE_TYPEResult
    {
        public short ID_REF_NTC_TYPE { get; set; }
        public string CD_REF_NTC_TYPE { get; set; }
        public string TX_REF_NTC_DSCR { get; set; }
    }
}
