// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_UTILITY_DESCRResult
    {
        public decimal ID_UTLTY_DDCTN { get; set; }
        public decimal? AM_UTLTY_DDCTN { get; set; }
        public string UTLTY_DESCR { get; set; }
    }
}
