// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REGISTER_CHILD_SUPPORT_ByID_NEWCASEResult
    {
        public int ID_NEWMBR { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public int ID_CHILD_SUPPORT { get; set; }
        public string PAIDTO_FULLNAME { get; set; }
        public decimal? PAID_AMOUNT { get; set; }
        public string PAY_FREQUENCY { get; set; }
        public string CHILDREN { get; set; }
    }
}
