// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_PIV_COURT_ORDERResult
    {
        public int ID_DPNDNT { get; set; }
        public int ID_CRT_ORDRD_AMNT { get; set; }
    }
}
