// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GET_CASE_ACTIONResult
    {
        public int? ID_CASE_NMBR { get; set; }
        public string TXT_ACTION { get; set; }
        public string TXT_REASON { get; set; }
    }
}
