// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GET_CASE_ALT_OFFICE_NOResult
    {
        public decimal NO_CASE { get; set; }
        public string ALT_OFFICE_NO { get; set; }
    }
}
