// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GET_CASE_STATUS_REG_BY_NO_CASEResult
    {
        public int ID_NEWCASE { get; set; }
        public string NO_CASE { get; set; }
        public string NO_CASE_CHCKDGT { get; set; }
        public string COUNTY_OFFICE { get; set; }
        public DateTime? DT_REGISTRATION_MODIFIED { get; set; }
        public DateTime? DT_CASE_APPTDATETIME { get; set; }
        public string DATE_REGISTRATION { get; set; }
        public string DATE_NOMA { get; set; }
        public string DATE_OACIS_INTERVIEW { get; set; }
        public string DATE_VERIFICATION_PENDING { get; set; }
        public string DATE_AWARD { get; set; }
        public string DATE_DENY { get; set; }
        public string DATE_DELETION { get; set; }
        public string DATE_ERROR { get; set; }
        public string FL_EXPEDITED { get; set; }
        public string FL_APPTMADE { get; set; }
        public string DHR_APPLICATION_TYPE { get; set; }
        public string DHR_SIGNED_DATE { get; set; }
        public string SCI_WORKER { get; set; }
        public string FL_HOH { get; set; }
        public string DHR_MEMBER_SSN { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string MEMBER_NAME { get; set; }
        public DateTime? DT_RQRD_VRCTN { get; set; }
        public string CD_MTHD_INTRVW { get; set; }
    }
}
