// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_DUPLICATE_MEMBERSResult
    {
        public int ID_CASE_NMBR { get; set; }
        public decimal NO_CASE { get; set; }
        public decimal? NO_CASE_CHCKDGT { get; set; }
        public string TX_CASE_STTS_DSCR { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public DateTime? DT_BRTH { get; set; }
        public string NO_SSN { get; set; }
        public string CD_SEX { get; set; }
        public decimal? CD_RACE { get; set; }
    }
}
