// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_INTERVIEWEE_INFOResult
    {
        public string CD_INTRVWEE_DSGNTN { get; set; }
        public string CD_MTHD_INTRVW { get; set; }
        public string FL_AR_FORM_SGND { get; set; }
        public string FL_CNTNUE_FA_SCRN { get; set; }
        public string FL_HH_CMPSTN_QSTNBL { get; set; }
        public string FL_HH_HMLS { get; set; }
        public short? ID_VRFCTN_HH { get; set; }
        public short? ID_VRFCTN_HH_CMPSTN { get; set; }
        public short? ID_VRFCTN_HH_RSDNCY { get; set; }
        public short? ID_VRFCTN_INTRVWEE { get; set; }
        public string FL_LIFELINE { get; set; }
        public string TX_VRFCTN_ATHRZD_RPRSNTTV { get; set; }
        public string TX_VRFCTN_HH { get; set; }
        public string TX_VRFCTN_HH_CMPSTN { get; set; }
        public string TX_VRFCTN_HH_RSDNCY { get; set; }
        public string TX_VRFCTN_INTRVWEE { get; set; }
        public string TX_VRFCTN_RSDNCY { get; set; }
    }
}
