// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REGISTER_ADDRESS_COMPAREResult
    {
        public string NO_CASE { get; set; }
        public string AD_STREET1 { get; set; }
        public string ALL_MAILING_ADDR1 { get; set; }
        public string ALL_MAILING_CITY { get; set; }
        public string ALL_MAILING_COUNTY { get; set; }
        public string ALL_MAILING_STATE { get; set; }
        public string ALL_MAILING_ZIP { get; set; }
        public string ALL_MAILING_ZIP4 { get; set; }
    }
}
