// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SELF_EMP_INC_SUMResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string FL_HOH { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
        public int? ID_EMPLYMNT { get; set; }
        public decimal? ID_INCM_TYPE { get; set; }
        public decimal? AM_ERND_SELF_EMPLYMNT_INCM { get; set; }
        public decimal? AM_ERND_SELF_EMPLYMNT_INCM2 { get; set; }
        public decimal? AM_UNERND_SELF_EMPLYMNT_INCM { get; set; }
        public decimal? AM_UNERND_SELF_EMPLYMNT_INCM2 { get; set; }
        public string NM_EMPLYR { get; set; }
    }
}
