// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_ByCase_AU_SemiAnnual_RptResult
    {
        public DateTime? ID_DATE_CREATED { get; set; }
        public string ID_CASE_NUMBER { get; set; }
        public decimal? NO_CASE { get; set; }
        public string ID_USER { get; set; }
        public int? ID_NMBR_LOGIN { get; set; }
        public string FL_REPL_FRM_AUTH { get; set; }
        public string CD_SR_INCOMP_STAT { get; set; }
        public DateTime? DT_SR_INCOMP_DT { get; set; }
        public string CD_SR_COMP_STAT { get; set; }
        public DateTime? DT_SR_COMP { get; set; }
        public DateTime? DT_REPL_FRM { get; set; }
        public DateTime? DT_FRM_RCVD { get; set; }
        public string SCI_MSG { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        public decimal? CD_TRCKNG_OFFC { get; set; }
        public string NM_HOH { get; set; }
        public string SR_CODE { get; set; }
    }
}
