// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_RmMealFlag_CASEResult
    {
        public string FL_PAY_ROOM_MEAL { get; set; }
    }
}
