// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_DENIALS_TERM_MNTH_BY_FAWResult
    {
        public DateTime? DT_APPLD { get; set; }
        public decimal NO_CASE { get; set; }
        public DateTime? DT_CASE_STTS { get; set; }
        public string FL_HOH { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public string MEMBER_NAME { get; set; }
        public string NM_FULL_NAME { get; set; }
        public string CD_CNTY_DSCR { get; set; }
        public string CD_CASE_STTS_TYPE { get; set; }
        public string TX_RJCTN_DNL_TERM { get; set; }
    }
}
