// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_DPNDNT_CARE_EXP_ALL_IDCASEResult
    {
        public int ID_DPNDNT_CARE { get; set; }
        public int? ID_DPNDNT { get; set; }
        public int? ID_MMBR { get; set; }
        public int? CHILD { get; set; }
        public int ID_PRVDR_NAME { get; set; }
        public decimal? AM_DPNDNT_CARE_EXPNS { get; set; }
        public decimal? AM_PAID { get; set; }
        public decimal? AM_PAID_MNTHLY { get; set; }
        public string FL_ASSSTD_BY_OTHR { get; set; }
        public decimal? ID_FRQNCY_DC_EXPNS { get; set; }
        public decimal? ID_FRQNCY_DC_PAID { get; set; }
        public short? ID_VRFCTN_DC { get; set; }
        public string CD_MONTH { get; set; }
        public string FL_OUTSIDE_DEP_PYMNT { get; set; }
        public short? DOIDDCOP { get; set; }
        public int? DOIDDC { get; set; }
        public decimal? AM_DC_OTHR_PAY { get; set; }
        public DateTime? DT_DC_OTHR_PAYER { get; set; }
        public string FL_DC_PAY_MMBR { get; set; }
        public decimal? ID_FRQNCY_DC_OTHR_PAYER { get; set; }
        public short? ID_VRFCTN_DC_OTHR_PAYER { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public short? UIIDDCOP { get; set; }
        public int? ID_REF_UNERND_SUBTYPE { get; set; }
        public decimal? AM_UNERND_MNTHLY { get; set; }
        public DateTime? DT_RCVD { get; set; }
        public int? ID_CASE_NMBR { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
