// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_UTLTY_RECORDBResult
    {
        public int ID_UTLTY_EXPNS { get; set; }
        public decimal? ID_UTLTY_DDCTN { get; set; }
        public string CD_MONTH { get; set; }
    }
}
