// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class get_REGISTER_APPLICATION_ByID_NEWCASEResult
    {
        public int ID_NEWCASE { get; set; }
        public string ID_USER { get; set; }
        public string NO_CASE { get; set; }
        public string NO_CASE_CHCKDGT { get; set; }
        public string COUNTY_SUBMIT { get; set; }
        public string COUNTY_OFFICE { get; set; }
        public DateTime? DT_REGISTRATION_CREATIED { get; set; }
        public DateTime? DT_REGISTRATION_MODIFIED { get; set; }
        public DateTime? DT_CASE_APPTDATETIME { get; set; }
        public string DATE_REGISTRATION { get; set; }
        public string DATE_NOMA { get; set; }
        public string DATE_OACIS_INTERVIEW { get; set; }
        public string DATE_VERIFICATION_PENDING { get; set; }
        public string DATE_AWARD { get; set; }
        public string DATE_DENY { get; set; }
        public string DATE_DELETION { get; set; }
        public string DATE_ERROR { get; set; }
        public string FL_ACTIVE { get; set; }
        public string FL_REGISTRATION_COMPLETE { get; set; }
        public string FL_EXPEDITED { get; set; }
        public string FL_APPTMADE { get; set; }
        public string FL_OFFICEINT { get; set; }
        public string CD_SOURCE { get; set; }
        public string CD_LANGUAGE { get; set; }
        public string CD_REGISTRATION_STATUS { get; set; }
        public string CD_REGISTRATION_STATUS_SENT { get; set; }
        public DateTime? DT_REGISTRATION_STATUS { get; set; }
        public DateTime? DT_REGISTRATION_STATUS_SENT { get; set; }
        public string DHR_APPLICATION_ID { get; set; }
        public string DHR_APPLICATION_TYPE { get; set; }
        public string DHR_START_DATE { get; set; }
        public string DHR_SIGNED_DATE { get; set; }
        public string DHR_SUBMIT_TO_COUNTY_OFFICE { get; set; }
        public string ALL_MAILING_ADDR1 { get; set; }
        public string ALL_MAILING_ADDR2 { get; set; }
        public string ALL_MAILING_CITY { get; set; }
        public string ALL_MAILING_STATE { get; set; }
        public string ALL_MAILING_ZIP { get; set; }
        public string ALL_MAILING_ZIP4 { get; set; }
        public string ALL_MAILING_COUNTY { get; set; }
        public string ALL_RESIDENCE_ADDR1 { get; set; }
        public string ALL_RESIDENCE_ADDR2 { get; set; }
        public string ALL_RESIDENCE_CITY { get; set; }
        public string ALL_RESIDENCE_STATE { get; set; }
        public string ALL_RESIDENCE_ZIP { get; set; }
        public string ALL_RESIDENCE_ZIP4 { get; set; }
        public string DHR_HOME_PHONE_NUMBER { get; set; }
        public string DHR_WORK_PHONE_NUMBER { get; set; }
        public string DHR_MESSAGE_PHONE_NUMBER { get; set; }
        public string DHR_CELL_NUMBER { get; set; }
        public string DHR_EMAIL_ADDRESS { get; set; }
        public string ALL_AUTH_REP_FIRST_NAME { get; set; }
        public string ALL_AUTH_REP_MIDDLE_NAME { get; set; }
        public string ALL_AUTH_REP_LAST_NAME { get; set; }
        public string ALL_AUTH_REP_PHONE_NUMBER { get; set; }
        public string ALL_EBT_REP_FIRST_NAME { get; set; }
        public string ALL_EBT_REP_MIDDLE_NAME { get; set; }
        public string ALL_EBT_REP_LAST_NAME { get; set; }
        public string ALL_EBT_REP_PHONE_NUMBER { get; set; }
        public int? DHR_HOH_PERSON_ID { get; set; }
        public int? DHR_APPLICANT_PERSON_ID { get; set; }
        public int? ALL_HOH_ID { get; set; }
        public int? NUMBER_OF_APPTS { get; set; }
        public string TEXT_REGISTRATION_COMMENTS { get; set; }
        public int? NBR_IN_HH { get; set; }
        public string SCI_CASENO { get; set; }
        public string SCI_CHKDGT { get; set; }
        public string SCI_CTYOFF { get; set; }
        public string SCI_TRANDT { get; set; }
        public string SCI_DUEDT { get; set; }
        public string SCI_NAME { get; set; }
        public string SCI_ADDR1 { get; set; }
        public string SCI_RCTYOFF { get; set; }
        public string SCI_ADDR2 { get; set; }
        public string SCI_CITY { get; set; }
        public string SCI_ZIP5 { get; set; }
        public string SCI_ZIP4 { get; set; }
        public string SCI_SPECDT { get; set; }
        public string SCI_APPSTS { get; set; }
        public string SCI_APPDT { get; set; }
        public string SCI_PROSTD { get; set; }
        public string SCI_HHTYP { get; set; }
        public string SCI_HOMELS { get; set; }
        public string SCI_WORKER { get; set; }
        public string SCI_OFFICE { get; set; }
        public string SCI_APTDT { get; set; }
        public string SCI_BATTER { get; set; }
        public string SCI_DENY { get; set; }
        public string SCI_APTYPE { get; set; }
        public string SCI_EXPDT { get; set; }
        public string SCI_PASS { get; set; }
        public string SCI_AUTH1 { get; set; }
        public string SCI_AUTH2 { get; set; }
        public string SCI_ERROR_MSG { get; set; }
        public int? SCI_NBR_IN_HH { get; set; }
        public string MYDHR_USERID { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public string MEMBER_NAME { get; set; }
        public string ORIG_ADDRESS { get; set; }
        public string FL_PHN_INTRVW { get; set; }
        public string APPLICANT { get; set; }
    }
}
