// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_COURT_ORDERED_TYPEResult
    {
        public decimal ID_CRT_ORDRD { get; set; }
        public string CD_CRT_ORDRD { get; set; }
        public string TX_CRT_ORDRD_DSCR { get; set; }
    }
}
