// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_ADDI_InfoResult
    {
        public string NM_LAST { get; set; }
        public string NM_FIRST { get; set; }
        public string DT_DOB { get; set; }
        public string NO_SSN { get; set; }
        public string TX_CNTY { get; set; }
        public string TX_STTS { get; set; }
    }
}
