// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_SECURITY_MAINResult
    {
        public string ID_PAYROLL { get; set; }
        public string NM_FULL_NAME { get; set; }
        public string NAMESSN { get; set; }
    }
}
