// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GET_MAILING_ADDRSS_IDResult
    {
        public int ID_ADDRSS { get; set; }
        public int ID_MMBR { get; set; }
        public string FL_HOH { get; set; }
    }
}
