// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_INSURANCEResult
    {
        public int ID_INSRNC { get; set; }
        public decimal ID_INSRNC_PAYER { get; set; }
        public decimal? AM_PREMIUM { get; set; }
        public decimal? AM_PREMIUM_MNTHLY { get; set; }
        public decimal? AM_TTL_PREMIUM_PAID { get; set; }
        public DateTime? DT_PREMIUM_PAID { get; set; }
        public decimal? ID_FRQNCY_PREMIUM { get; set; }
        public decimal? NO_HH_MMBR { get; set; }
    }
}
