// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MNTHLY_STTS_RPTResult
    {
        public string CD_CNTY_DSCR { get; set; }
        public int? FROM_DT_CASES { get; set; }
        public int? TO_DATE_CASES { get; set; }
        public int? COUNT_CASES { get; set; }
    }
}
