// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_DAILY_AWARD_DENIALSResult
    {
        public decimal? CD_TRCKNG_OFFC { get; set; }
        public DateTime? DT_APPLD { get; set; }
        public DateTime? DT_APPRVL { get; set; }
        public decimal NO_CASE { get; set; }
        public string CD_RJCTN_CLSR { get; set; }
        public decimal? AM_ALLTMNT { get; set; }
        public decimal? AM_AWRD_ALLTMNT { get; set; }
        public string CD_ALLTMNT_TYPE { get; set; }
        public DateTime? DT_CASE_STTS { get; set; }
        public string FL_HOH { get; set; }
        public string NO_SSN { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public string MEMBER_NAME { get; set; }
        public string NM_FULL_NAME { get; set; }
        public int? ID_RSTRTN { get; set; }
        public decimal? AM_RSTRTN { get; set; }
        public DateTime? DT_RSTRTN { get; set; }
        public decimal? CD_CNTY { get; set; }
        public string CD_CNTY_DSCR { get; set; }
        public string CD_CASE_STTS_TYPE { get; set; }
        public string TX_RJCTN_DNL_TERM { get; set; }
        public int? HH_MEM_CNT { get; set; }
    }
}
