// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_RESORATION_REASON_TYPEResult
    {
        public decimal ID_RSTRTN_RSN { get; set; }
        public string CD_RSTRTN_RSN { get; set; }
        public string TX_RSTRTN_RSN_DSCR { get; set; }
    }
}
