// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_MEDICAL_LIMITResult
    {
        public decimal ID_MDCL_LMT { get; set; }
        public decimal? AM_MDCL_LIMIT { get; set; }
        public string CD_MDCL_DSCR { get; set; }
    }
}
