// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_WORKER_REMINDERSResult
    {
        public int ID_WRKR_RMNDR { get; set; }
        public string NO_CASE { get; set; }
        public DateTime? DT_RMNDR { get; set; }
        public string FL_ADVRS_ACTN_RMNDR { get; set; }
        public string TX_RMNDR_SBJCT { get; set; }
        public string TX_RMNDR_DSCR { get; set; }
        public string FULL_NAME { get; set; }
    }
}
