// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_Shelter_RECORDB_IDResult
    {
        public int ID_SHLTR_EXPNS { get; set; }
        public string CD_MONTH { get; set; }
    }
}
