// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_Daily_STTS_RPTResult
    {
        public string CD_CNTY { get; set; }
        public DateTime DT_STTS_DATE { get; set; }
        public int? NO_ADD_MMBR { get; set; }
        public int? NO_APP_REQ { get; set; }
        public int? NO_DECLINE { get; set; }
        public int? NO_OPEN { get; set; }
        public int? NO_CLOSED { get; set; }
        public int? NO_NEW_CASE { get; set; }
        public int? NO_REOPENED { get; set; }
        public int? NO_RECRTF { get; set; }
        public int? NO_RECRTFD_PROC6 { get; set; }
        public int? NO_PEND { get; set; }
        public int? NO_WD_BY_APPLCNT { get; set; }
        public int? NO_EXPD { get; set; }
        public int? NO_EXPD_PSTPN_VRFC { get; set; }
        public int? NO_TERM { get; set; }
        public int? NO_PEND_ADVRS_ACTN { get; set; }
        public int? NO_UNKN { get; set; }
        public int? NO_NMBR_OF_CASES { get; set; }
    }
}
