// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_EARNINC_INC_SUM_BY_IDMMBRResult
    {
        public int ID_CASE_NMBR { get; set; }
        public short ID_CNTY_STATE { get; set; }
        public decimal? CD_TRCKNG_OFFC { get; set; }
        public decimal NO_CASE { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        public int? ID_MMBR { get; set; }
        public string FL_HOH { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
        public int? ID_EMPLYMNT { get; set; }
        public decimal? ID_INCM_TYPE { get; set; }
        public decimal? AM_INCM_MNTHLY { get; set; }
        public decimal? AM_TTL_INCM_NXT_MNTH { get; set; }
        public decimal? AM_TTL_INCM_PRVS_MNTH { get; set; }
        public string NM_EMPLYR { get; set; }
    }
}
