// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MEDICAL_NOTESResult
    {
        public string colA { get; set; }
        public string colB { get; set; }
        public string colC { get; set; }
        public int colD { get; set; }
    }
}
