// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_SECURITYResult
    {
        public int ID_SCRTY { get; set; }
        public string ID_PYRLL { get; set; }
        public string CD_CNTY_SCRTY { get; set; }
        public string CD_PSSWRD { get; set; }
        public string CD_ROLE { get; set; }
        public string NM_FULL_NAME { get; set; }
        public string ID_USER { get; set; }
        public string FL_ADMIN { get; set; }
        public string FL_REGISTRATION { get; set; }
        public string FL_APPOINTMENTS { get; set; }
        public string FL_APP_STATUS { get; set; }
        public string FL_CASE_NOTES { get; set; }
        public string FL_SR_UPDATES { get; set; }
        public string FL_TRIAL_BUDGET { get; set; }
        public string FL_REPORTS { get; set; }
        public string CD_FiscalYear { get; set; }
        public string FL_ISSUANCE { get; set; }
        public string FL_DSNAP { get; set; }
    }
}
