// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_REF_RJCTN_DNL_TERMResult
    {
        public string CD_RJCTN_CLSR { get; set; }
        public string CDDENIAL { get; set; }
        public string CD_TRMNTN { get; set; }
        public string TX_RJCTN_DNL_TERM { get; set; }
        public string TXT_RJC_DNL_TER { get; set; }
    }
}
