// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_STRIKE_CDMTH1Result
    {
        public int ID_STRKR { get; set; }
        public string CD_MONTH { get; set; }
    }
}
