// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_MYDHRAPPS_byID_NEWCASEResult
    {
        public int ID_NEWCASE { get; set; }
        public string NO_CASE { get; set; }
        public string NO_CASE_CHCKDGT { get; set; }
        public string DATE_REGISTRATION { get; set; }
        public string DATE_AWARD { get; set; }
        public string DATE_DENY { get; set; }
    }
}
