// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_GRAND_TTL_MED_INSRNC_EXP_IntBudSumPrintResult
    {
        public decimal INS_EXP_M1 { get; set; }
        public decimal INS_EXP_M2 { get; set; }
    }
}
