// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GET_MMBR_CNTY_ADDRS_F879Result
    {
        public short? ID_CNTY_ADDRESS { get; set; }
        public string CntyAdd1 { get; set; }
        public string CntyAdd2 { get; set; }
        public string CntyZip { get; set; }
        public string CntyZip4 { get; set; }
        public string CntyCty { get; set; }
        public string NO_OFFICE_PHONE { get; set; }
        public string NO_OFFICE_FAX { get; set; }
        public string CD_CNTY_DSCR { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public string MEMBER_NAME { get; set; }
        public int? ID_ADDRSS { get; set; }
        public short? ID_CNTY_STATE { get; set; }
        public decimal? ID_REF_ADDRSS_TYPE { get; set; }
        public string WHOLE_ADDRESS { get; set; }
        public string CT_ST_ZIP { get; set; }
        public string AD_STREET1 { get; set; }
        public string AD_STREET2 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
        public string AD_ZIP_4 { get; set; }
        public string NO_HOME_TEL { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        public string DT_STAMPS_END { get; set; }
        public string FL_BENEFITS { get; set; }
        public string FL_INTERVIEW { get; set; }
        public string FL_NOTIFY { get; set; }
        public string DT_BENEFITS { get; set; }
        public string DT_INTERVIEW { get; set; }
        public string INTERVIEW_TIME { get; set; }
        public string FL_OFF { get; set; }
    }
}
