// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Get_OILINFOResult
    {
        [Column("CASE #")]
        public decimal CASE { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string Status { get; set; }
        public string Approved { get; set; }
        public string Race { get; set; }
    }
}
