// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GET_UNEARNED_ID_STRIKEResult
    {
        public int ID_UNERND_INCM { get; set; }
        public int ID_REF_UNERND_SUBTYPE { get; set; }
        public string CD_MONTH { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
