// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetAllEmployersResult
    {
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
    }
}
