// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetAllCases_ADVERSE_ACTION_REMINDERSResult
    {
        public DateTime? DT_RMNDR { get; set; }
        public string TX_RMNDR_SBJCT { get; set; }
        public string TX_RMNDR_DSCR { get; set; }
    }
}
