// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIDMmbr_EmploymentType6Result
    {
        public int ID_EMPLYMNT { get; set; }
        public decimal ID_INCM_TYPE { get; set; }
    }
}
