// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByID_MMBR_ALIEN_STATUSResult
    {
        public int ID_ALIEN_STATUS { get; set; }
        public int ID_MMBR { get; set; }
        public string CD_ALIEN_RGSTRTN { get; set; }
        public string FL_QA_LPR { get; set; }
        public string FL_QA_SCTN_208 { get; set; }
        public string FL_QA_SCTN_207 { get; set; }
        public string FL_QA_SCTN_212 { get; set; }
        public string FL_QA_SCTN_241 { get; set; }
        public string FL_QA_SCTN_203 { get; set; }
        public string FL_QA_SCTN_501 { get; set; }
        public string FL_QA_SCTN_204 { get; set; }
        public string FL_FS_SCTN_207 { get; set; }
        public string FL_FS_SCTN_208 { get; set; }
        public string FL_FS_SCTN_241 { get; set; }
        public string FL_FS_SCTN_501 { get; set; }
        public string FL_FS_SCTN_584 { get; set; }
        public string FL_QAIND_LPR { get; set; }
        public string FL_QAIND_MLTRY_CNNCTN { get; set; }
        public string FL_QAIND_US__18 { get; set; }
        public string FL_QAIND_US_BNFTS { get; set; }
        public string FL_QAIND_US___65 { get; set; }
        public string FL_QAIND_US_QA__5 { get; set; }
        public string FL_NONQAIND_HMONG { get; set; }
        public string FL_NONQAIND_LAO { get; set; }
        public string FL_NONQAIND_AMRCN_INDIAN { get; set; }
        public string FL_NONQAIND_ACT25_USC450 { get; set; }
        public string FL_NONQAIND_ST_REGIS { get; set; }
        public string FL_NONQAIND_MICMAC { get; set; }
        public string FL_NONQAIND_ABENAKI { get; set; }
        public string FL_NONQAIND_KICKAPOO { get; set; }
    }
}
