// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdUnerndIncm_TANF_MMBR_INCLUDEDResult
    {
        public int ID_TANF_MMBR_INCLD { get; set; }
        public int ID_UNERND_INCM { get; set; }
        public int ID_MMBR { get; set; }
    }
}
