// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIDNEWCASE_REG_CASEResult
    {
        public int ID_NEWCASE { get; set; }
        public string FL_OLD { get; set; }
        public string FL_LOCAL { get; set; }
        public string ApplicationID { get; set; }
        public string ID_USER { get; set; }
        public string CASEENTRYDT { get; set; }
        public string CASEMODDT { get; set; }
        public string NO_CASE { get; set; }
        public string NO_CASE_CHCKDGT { get; set; }
        public string CD_CNTY { get; set; }
        public string CD_OFF { get; set; }
        public string TRANDT { get; set; }
        public string DUEDT { get; set; }
        public string RCTYOFF { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
        public string AD_ZIP_4 { get; set; }
        public string SPECDT { get; set; }
        public string APPSTS { get; set; }
        public string APPDT { get; set; }
        public string PROSTD { get; set; }
        public string HHTYP { get; set; }
        public string HOMELS { get; set; }
        public string WORKER { get; set; }
        public string EXPDT { get; set; }
        public string PASS { get; set; }
        public string AUTH1 { get; set; }
        public string AUTH2 { get; set; }
        public string HNBR { get; set; }
        public string FLBTR { get; set; }
        public string SCIERRMSG { get; set; }
        public string REG_DT { get; set; }
        public string ERROR_DT { get; set; }
        public string DEL_DT { get; set; }
        public int? NBR_APPTS { get; set; }
        public string FL_APPTMADE { get; set; }
        public DateTime? CASE_APPTDATETIME { get; set; }
        public string NOMA_DT { get; set; }
        public string OACIS_INT_DT { get; set; }
        public string VERIFICATION_PEND_DT { get; set; }
        public string AWARD_DT { get; set; }
        public string DENY_DT { get; set; }
        public string CD_REGISTRATION_STATUS { get; set; }
        public string CD_REGISTRATION_STATUS_SENT { get; set; }
        public string DT_LAST_CD_STATUS_SENT { get; set; }
        public string TX_REGISTRATION_COMMENT { get; set; }
        public string FL_REGISTRATION_COMPLETE { get; set; }
        public string CD_LANGUAGE { get; set; }
        public string FL_EXPEDITED { get; set; }
    }
}
