// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetbyIdCaseNmbr_DISASTERResult
    {
        public int? ID_DISASTER { get; set; }
        public string NM_DISASTER { get; set; }
        public DateTime? DT_DISASTER_BEGIN { get; set; }
        public DateTime? DT_DISASTER_END { get; set; }
        public string TX_DISASTER_DESC { get; set; }
        public string FL_CANCELLED { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public decimal NO_CASE { get; set; }
    }
}
