// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByCdRefAddrssType_REF_ADDRESS_TYPEResult
    {
        public decimal ID_REF_ADDRSS_TYPE { get; set; }
        public string CD_REF_ADDRSS_TYPE { get; set; }
    }
}
