// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_SHELTER_DWELLING_TYPEResult
    {
        public short ID_SHLTR_DWELLNG_TYPE { get; set; }
        public string CD_SHLTR_DWELLING_TYPE { get; set; }
    }
}
