// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetbyIdEmplymnt_StrikerEmploymentResult
    {
        public int ID_STRKR { get; set; }
        public int ID_EMPLYMNT { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public decimal? AM_STRKPAY_MNTHLY { get; set; }
        public decimal? AM_STRK_PAY { get; set; }
        public DateTime? DT_STRK_END { get; set; }
        public DateTime? DT_STRK_STRT { get; set; }
        public string FL_ELGBL_FS_PRIOR_STRK { get; set; }
        public decimal? ID_FRQNCY_PAY_STRK { get; set; }
        public short? ID_VRFCTN_STRK { get; set; }
        public string CD_MONTH { get; set; }
        public string CD_MONTH_TRANSLATED { get; set; }
    }
}
