// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbr_STUDENTResult
    {
        public int ID_STDNT { get; set; }
        public int? ID_MMBR { get; set; }
        public string CD_MONTH { get; set; }
        public string FL_CHILD_CARE_PRVDR { get; set; }
        public string FL_ELGBL_STDNT { get; set; }
        public string FL_EMPLYD_PRTTM { get; set; }
        public string FL_FIT { get; set; }
        public string FL_HGHR_LRNNG { get; set; }
        public string FL_JOBS_TRNNG { get; set; }
        public string FL_MEAL_TCKT { get; set; }
        public string FL_OJT { get; set; }
        public string FL_PLUS_50_MEALS_CVRD { get; set; }
        public string FL_PRNT_OF_CHLD { get; set; }
        public string FL_RCVNG_TANF { get; set; }
        public string FL_SNGL_PRNT_STDNT { get; set; }
        public string FL_TITLE_IV { get; set; }
        public string FL_WORK_STDY_PRGRM { get; set; }
        public short? ID_VRFCTN_STUDENT { get; set; }
        public string TX_VRFCTN_STUDENT { get; set; }
    }
}
