// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_MEDICAL_NOTESResult
    {
        public int ID_MDCL_NOTES { get; set; }
        public int ID_MDCL_EXPNS { get; set; }
        public short ID_REF_MDCL_NOTE_TYPE { get; set; }
        public string TX_MDCL_NOTES_DSCR { get; set; }
    }
}
