// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_MEDICAL_EXPENSE_OTHER_PAYERResult
    {
        public short ID_ME_OTHR_PAYER { get; set; }
        public int? ID_MMBR { get; set; }
        public int ID_MDCL_EXPNS { get; set; }
        public decimal? AM_ME_OTHR_PAY { get; set; }
        public DateTime? DT_ME_OTHR_PAYER { get; set; }
        public string FL_ME_PAY_MMBR { get; set; }
        public short? ID_VRFCTN_ME_OTHR_PAYER { get; set; }
    }
}
