// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_DEPENDENT_CAREResult
    {
        public int ID_DPNDNT_CARE { get; set; }
        public int? ID_DPNDNT { get; set; }
        public decimal? AM_DPNDNT_CARE_EXPNS { get; set; }
        public decimal? AM_PAID { get; set; }
        public decimal? AM_PAID_MNTHLY { get; set; }
        public string FL_ASSSTD_BY_OTHR { get; set; }
        public decimal? ID_FRQNCY_DC_EXPNS { get; set; }
        public decimal? ID_FRQNCY_DC_PAID { get; set; }
        public short? ID_VRFCTN_DC { get; set; }
    }
}
