// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_FREQUENCYResult
    {
        public decimal ID_FRQNCY_REF { get; set; }
        public string CD_FRQNCY_DSCR { get; set; }
        public decimal? NO_FRQNCY_FACTOR { get; set; }
    }
}
