// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByCertElig_REF_CERT_ELIGResult
    {
        public short ID_REF_CERT_ELIG { get; set; }
        public string CD_CERT_ELIG { get; set; }
        public string TX_CERT_ELIG_DSCR { get; set; }
    }
}
