// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbr_OUTSIDE_DEPENDENTResult
    {
        public int ID_DPNDNT { get; set; }
        public int ID_MMBR { get; set; }
        public DateTime? DT_DPNDNT_DOB { get; set; }
        public string FL_CHILD { get; set; }
        public string NM_DPNDNT_LST { get; set; }
        public string NM_DPNDNT_FRST { get; set; }
        public string NM_DPNDNT_MDL { get; set; }
        public string NM_DPNDNT_SFX { get; set; }
        public string DEPENDENT_NAME { get; set; }
    }
}
