// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_INCOME_LIMITResult
    {
        public decimal ID_REF_INCM_LIMIT { get; set; }
        public decimal? AM_INCM_LIMIT { get; set; }
        public decimal? NO_HH_SIZE { get; set; }
    }
}
