// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetBySearchCaseResult
    {
        public int ID_CASE_NMBR { get; set; }
        public short ID_CNTY_STATE { get; set; }
        public decimal? CD_CTY_RESIDING { get; set; }
        public decimal? CD_TRCKNG_OFFC { get; set; }
        public DateTime? DT_EXPRTN { get; set; }
        public string ID_WRKR_SSN { get; set; }
        public decimal NO_CASE { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        //public decimal NO_CASE { get; set; }
        public DateTime? DT_APPLD { get; set; }
        public decimal? NO_CASE_CHCKDGT { get; set; }
        public decimal? CD_PRCSSN_STNDRD { get; set; }
        //public DateTime? DT_APPLD { get; set; }
        public string FL_BTRW { get; set; }
        public int? ID_DISASTER { get; set; }
        public string MYDHR_PIN { get; set; }
    }
}
