// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByText_UnearnedIncTypeResult
    {
        public int ID_REF_UNERND_SUBTYPE { get; set; }
        public int ID_REF_UNERND_TYPE { get; set; }
        public string CD_UNERND_SUBTYPE { get; set; }
        public string TX_UNERND_SUBTYPE { get; set; }
    }
}
