// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_IEVS_TRAKResult
    {
        public string ID_SSN { get; set; }
        public string CASENBR { get; set; }
        public string CASENBRAPP { get; set; }
        public string COUNTYCD { get; set; }
        public string COUNTYCDAPP { get; set; }
        public string CERTEND { get; set; }
        public string RECERTFLAG { get; set; }
        public string CD_SOURCE { get; set; }
    }
}
