// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_WELCOME_MESSAGEResult
    {
        public short ID_WLCM_MSSG { get; set; }
        public string ID_MSSG_CNTY { get; set; }
        public DateTime? DT_MSSG { get; set; }
        public string TX_WLCM_MSSG_DSCR { get; set; }
        public DateTime? DT_START { get; set; }
        public DateTime? DT_END { get; set; }
    }
}
