// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdCaseNmbr_RESTORATIONResult
    {
        public int ID_RSTRTN { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public decimal ID_RSTRTN_RSN { get; set; }
        public decimal? AM_RSTRTN { get; set; }
        public DateTime? DT_RSTRTN { get; set; }
    }
}
