// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbr_MEAL_RoomerBoarderResult
    {
        public int ID_MEAL { get; set; }
        public int? ID_MMBR { get; set; }
        public short? ID_MEAL_OTHER { get; set; }
        public decimal? AM_MEAL_MMBR_PAY { get; set; }
        public decimal? NO_MEALS { get; set; }
    }
}
