// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbr_MEMBER_TRNSFR_RSRCResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public string MEMBER_NAME { get; set; }
        public int ID_MMBR_RSRC { get; set; }
        public short ID_RSRC_CODE { get; set; }
        //public int ID_MMBR { get; set; }
        public decimal? AM_TRNSFR_RSRC_RCVD { get; set; }
        public decimal? AM_VALUE { get; set; }
        public DateTime? DT_ACTN_TRNSFR_RSRC { get; set; }
        public string FL_EXCLD { get; set; }
        public string FL_TRNSFR_QLFY_FA { get; set; }
        public string TX_DSPSL_RSN { get; set; }
        public string CD_MONTH { get; set; }
        public string CD_MONTH_TRANSLATED { get; set; }
    }
}
