// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_CS_PAYER_RECIPIENTResult
    {
        public int ID_CS_PAYER_RCPNT { get; set; }
        public int ID_OBLGTN_RSN { get; set; }
        public string FL_PAYER { get; set; }
        public string NM_PAYER_RCPNT_LST { get; set; }
        public string NM_PAYER_RCPNT_FRST { get; set; }
        public string NM_PAYER_RCPNT_MDL { get; set; }
        public string NM_PAYER_RCPNT_SFX { get; set; }
    }
}
