// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByCode_REF_SPCL_REOPEN_RSNResult
    {
        public short ID_SPCL_REOPEN_RSN { get; set; }
        public string CD_SPCL_REOPEN_RSN { get; set; }
        public string TX_SPCL_REOPEN_RSN { get; set; }
    }
}
