// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class getByCaseAndFlow_CASE_WORKFLOWResult
    {
        public decimal NO_CASE { get; set; }
        public string CD_REF_MODULE { get; set; }
        public string FL_INTRVW { get; set; }
        public string FL_CMPLTD { get; set; }
        public DateTime DT_CRTD { get; set; }
        public DateTime DT_MDFD { get; set; }
    }
}
