// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetbyIdMmbrDpndnt_DEPENDENTS_allResult
    {
        public int ID_MMBR_OR_OUTDPNDNT { get; set; }
        public int PARENT_MMBR_ID { get; set; }
        public int ID_MMBR { get; set; }
        public int ID_DPNDNT { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
        public string FL_NON_MMBR { get; set; }
        public string HOUSEHOLD_MMBR { get; set; }
        public string OUTSIDE_DPNDNT { get; set; }
    }
}
