// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetbyIdCaseNmbr_CASEResult
    {
        public int ID_CASE_NMBR { get; set; }
        public short ID_CNTY_STATE { get; set; }
        public string CD_INTRVWEE_DSGNTN { get; set; }
        public decimal? CD_HH_TYPE { get; set; }
        public string CD_MTHD_INTRVW { get; set; }
        public decimal? CD_PRCSSN_STNDRD { get; set; }
        public decimal? CD_TRCKNG_OFFC { get; set; }
        public DateTime? DT_ADVRS_ACTN { get; set; }
        public DateTime? DT_APPLD { get; set; }
        public DateTime? DT_APPNTMNT { get; set; }
        public DateTime? DT_APPRVL { get; set; }
        public DateTime? DT_EXPRTN { get; set; }
        public DateTime? DT_RQRD_VRCTN { get; set; }
        public DateTime? DT_SPCL_DUE { get; set; }
        public string EM_HOH { get; set; }
        public string FL_ADVRS_WV { get; set; }
        public string FL_AR_FORM_SGND { get; set; }
        public string FL_CNTNUE_FA_SCRN { get; set; }
        public string FL_CNTNUE_VOLQUIT_SCRN { get; set; }
        public string FL_EMPLYD { get; set; }
        public string FL_EXPCT_STRT_WRK { get; set; }
        public string FL_EXPCT_VAC_HOL_BNUS_PAY { get; set; }
        public string FL_HH_CMPSTN_QSTNBL { get; set; }
        public string FL_HH_HMLS { get; set; }
        public string FL_JOBS_CHILD_SNCTN { get; set; }
        public string FL_NEW_EBT_CARD { get; set; }
        public string FL_ON_STRK { get; set; }
        public string FL_ONE_PRSN_HH { get; set; }
        public string FL_PAY_CS_NON_RSDNT { get; set; }
        public string FL_PAY_DC_BABYSIT { get; set; }
        public string FL_PAY_DC_BILL_NONHH { get; set; }
        public string FL_PAY_ROOM_MEAL { get; set; }
        public string FL_RSDNCY_QSTNBL { get; set; }
        public string FL_WRK_TRMNTD { get; set; }
        public string ID_WRKR_SSN { get; set; }
        public short? ID_VRFCTN_ATHRZD_RPRSNTTV { get; set; }
        public short? ID_VRFCTN_HH { get; set; }
        public short? ID_VRFCTN_HH_CMPSTN { get; set; }
        public short? ID_VRFCTN_HH_RSDNCY { get; set; }
        public short? ID_VRFCTN_INTRVWEE { get; set; }
        public short? ID_VRFCTN_RSDNCY { get; set; }
        public decimal NO_CASE { get; set; }
        public string NO_HOME_TEL { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        public string TX_HOME_DRCTNS { get; set; }
    }
}
