// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_RELATIONResult
    {
        public short ID_RLTN { get; set; }
        public string TX_RLTN_DSCR { get; set; }
    }
}
