// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_CASE_NOTESResult
    {
        public int ID_CASE_NOTE { get; set; }
        public int ID_MMBR { get; set; }
        public DateTime? DT_CASE_NOTE { get; set; }
        public DateTime? DT_CRTD { get; set; }
        public DateTime? DT_MDFD { get; set; }
        public string NM_CRTD { get; set; }
        public string NM_MDFD { get; set; }
        public string TX_CASE_NOTE_DSCR { get; set; }
    }
}
