// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetBySourceActiveCompletedRegisteredSmallResult
    {
        public string NO_CASE { get; set; }
        public string COUNTY_SUBMIT { get; set; }
        public string COUNTY_OFFICE { get; set; }
        public string SCI_CASENO { get; set; }
        public string SCI_NAME { get; set; }
        public string SCI_CITY { get; set; }
        public string SCI_WORKER { get; set; }
    }
}
