// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByNoCase_AU_CASELOGResult
    {
        public int ID_NMBR { get; set; }
        public string ID_USER { get; set; }
        public DateTime DT_LOGIN { get; set; }
        public string NO_CASE { get; set; }
        public int? ID_NMBR_LOGIN { get; set; }
        public string NM_FULL_NAME { get; set; }
    }
}
