// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetBySearchMemberResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public short ID_RACE_CODE { get; set; }
        public string CD_CASE_CRTD { get; set; }
        public string CD_SEX { get; set; }
        public string DPNDNT_NMBR { get; set; }
        public DateTime? DT_BRTH { get; set; }
        public string FL_DHR_EMPL { get; set; }
        public string FL_HOH { get; set; }
        public string NO_SSN { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public string AGE { get; set; }
        public string MEMBER_NAME { get; set; }
        public string FL_NON_MMBR { get; set; }
    }
}
