// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByVrfctnSubtype_REF_VERIFICATION_DETAILResult
    {
        public short ID_VRFCTN_DETAIL { get; set; }
        public decimal ID_REF_VRFCTN_SUBTYPE { get; set; }
        public string CD_VRFCTN_DETAIL_DSCR { get; set; }
        public string FL_OTHR_VRFCTN_RCVD { get; set; }
        public string TX_OTHR_VRFCTN { get; set; }
    }
}
