// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByName_MEMBERResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public short ID_RACE_CODE { get; set; }
        public string CD_SEX { get; set; }
        public DateTime? DT_BRTH { get; set; }
        public string FL_HOH { get; set; }
        public string NO_SSN { get; set; }
        public string MEMBER_NAME { get; set; }
        public decimal NO_CASE { get; set; }
        public string TX_CASE_STTS_DSCR { get; set; }
    }
}
