// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbr_SumUnearnedIncomeData_SSISSAResult
    {
        public int ID_MMBR { get; set; }
        public decimal? AM_UNERND_VALUE1 { get; set; }
        public decimal? AM_UNERND_VALUE2 { get; set; }
        public decimal? TOTAL_SSI_INC_AMNT { get; set; }
        public decimal? TOTAL_SSA_INC_AMNT { get; set; }
        public decimal? TOTAL_MNTHLY_AMT { get; set; }
        public string MEMBER_NAME { get; set; }
        public string CD_UNERND_SUBTYPE { get; set; }
        public string TX_UNERND_SUBTYPE { get; set; }
        public string INC_TYPE { get; set; }
    }
}
