// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_CASE_STATUS_TYPEResult
    {
        public decimal ID_REF_CASE_STATUS_TYPE { get; set; }
        public string TX_CASE_STTS_DSCR { get; set; }
    }
}
