// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_RACEResult
    {
        public short ID_RACE_CODE { get; set; }
        public decimal? CD_RACE { get; set; }
        public string TX_RACE_DSCR { get; set; }
    }
}
