// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetbyPrimaryKey_CS_PAYMENTSResult
    {
        public int ID_CS_PYMNT { get; set; }
        public int ID_CS_AMNT { get; set; }
        public decimal? AM_CS_PYMNT { get; set; }
        public DateTime? DT_CS_PYMNT { get; set; }
    }
}
