// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbr_EMPLOYMENT_VRFYTXTResult
    {
        public int ID_MMBR { get; set; }
        public string TX_VRFCTN_EMPLYMNT { get; set; }
    }
}
