// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbrAndMonth_REF_CERT_ELIGResult
    {
        public string CD_CERT_ELIG { get; set; }
    }
}
