// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetBYIDNEWMBR_REGISTER_CHILD_SUPPORTResult
    {
        public int ID_CHILD_SUPPORT { get; set; }
        public string PAIDTO_FULLNAME { get; set; }
        public decimal? PAID_AMOUNT { get; set; }
        public string PAY_FREQUENCY { get; set; }
        public string CHILDREN { get; set; }
    }
}
