// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_DEPENDENT_CARE_OTHER_PAYERResult
    {
        public short ID_DC_OTHR_PAY { get; set; }
        public int ID_DPNDNT_CARE { get; set; }
        public int ID_MMBR { get; set; }
        public decimal? AM_DC_OTHR_PAY { get; set; }
        public DateTime? DT_DC_OTHR_PAYER { get; set; }
        public string FL_DC_PAY_MMBR { get; set; }
        public decimal? ID_FRQNCY_DC_OTHR_PAYER { get; set; }
        public short? ID_VRFCTN_DC_OTHR_PAYER { get; set; }
    }
}
