// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_RESOURCE_LIMITResult
    {
        public short ID_RSRC_LIMIT { get; set; }
        public decimal? AM_RSRC_LIMIT { get; set; }
        public string CD_RSRC_DSCR { get; set; }
    }
}
