// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetbyIdCaseNmbr_AR_RPRSNTTV_INTRVWResult
    {
        public int ID_CASE_NMBR { get; set; }
        public string INTVWREP_NAME { get; set; }
    }
}
