// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetbyIdMmbrandType_SumEarnedIncomeDataResult
    {
        public decimal? TOTAL_RB_INC { get; set; }
        public decimal? TOTAL_SELF_INC { get; set; }
        public decimal? TOTAL_PROP_INC { get; set; }
        public decimal? TOT_HOURS_MAN_PROP { get; set; }
        public decimal? TOTAL_INC_NEXT_MNTH { get; set; }
        public decimal? TOTAL_INC_PREV_MNTH { get; set; }
        public string INC_TYPE { get; set; }
    }
}
