// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByMmbrs_EmployVQPlusResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string CD_CASE_CRTD { get; set; }
        public DateTime? DT_BRTH { get; set; }
        public string FL_DHR_EMPL { get; set; }
        public string FL_NON_MMBR { get; set; }
        public string FL_SNCTN { get; set; }
        public string FL_WRKNG { get; set; }
        public string MEMBER_NAME { get; set; }
        public decimal? ID_REF_SNCTN_RSN { get; set; }
        public DateTime? DT_SNCTN_END { get; set; }
        public DateTime? DT_SNCTN_STRT { get; set; }
        public decimal? NO_SNCTN { get; set; }
        public string FL_WRK_RGSTRTN_EXMPT { get; set; }
        public string FL_GOOD_RSN_QUIT { get; set; }
    }
}
