// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetbyIdCaseNmbr_AR_RPRSNTTV_AwardDenyResult
    {
        public int ID_CASE_NMBR { get; set; }
        public string NM_RPRSNTTV_FRST { get; set; }
        public string NM_RPRSNTTV_LAST { get; set; }
        public string NM_RPRSNTTV_MDL { get; set; }
        public string NM_RPRSNTTV_SFX { get; set; }
        public string FL_EBT_RPRSNTTV { get; set; }
    }
}
