// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIDCaseNmbr_UnearnedIncomeTotalResult
    {
        public int ID_MMBR { get; set; }
        public Nullable<int> ID_CASE_NMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public string CD_CASE_CRTD { get; set; }
        public string UNEARNED_TYPE { get; set; }
        public Nullable<int> TOTAL_UNEARNED_INCOME { get; set; }
        public Nullable<decimal> TOTAL_UNEARNED_INCOME2 { get; set; }
        public string CD_VRFCTN_DETAIL_DSCR { get; set; }
    }
}
