// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdDisaster_DISASTER_COUNTIESResult
    {
        public int ID_DISASTER_CNTY { get; set; }
        public int ID_DISASTER { get; set; }
        public string CD_CNTY { get; set; }
        public string CD_CNTY_DSCR { get; set; }
    }
}
