// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdCrtOrdrdAmnt_ARREARS_CSResult
    {
        public int ID_ARRRS_CS { get; set; }
        public int ID_CRT_ORDRD_AMNT { get; set; }
        public decimal? AM_OWED_ARRRS { get; set; }
        public decimal? AM_PAID_ARRRS { get; set; }
        public decimal? ID_FRQNCY_ARRRS { get; set; }
    }
}
