// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_PAST_DUE_RSNResult
    {
        public string CD_PAST_DUE_RSN { get; set; }
        public string TX_PAST_DUE_RSN { get; set; }
    }
}
