// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdCaseNo_MDCL_INSURANCE_BY_CDMNTHResult
    {
        public string MEMBER_NAME { get; set; }
        public string TX_PRVDR_DSCR { get; set; }
        public string NM_PRVDR { get; set; }
        public string CD_MNTH { get; set; }
        public int ID_INSRNC { get; set; }
        public decimal? AM_TTL_PREMIUM_PAID { get; set; }
        public string CD_VRFCTN_DETAIL_DSCR { get; set; }
    }
}
