// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_WAIVE_ADVERSE_ACTIONResult
    {
        public int ID_WAIVE_ADVRS_ACTN { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public DateTime? DT_ADVRS_ACTN { get; set; }
    }
}
