// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetBySearchARResult
    {
        public int ID_AR_RPRSNTTV { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string FL_EBT_RPRSNTTV { get; set; }
        public string AUTHREP_NAME { get; set; }
    }
}
