// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_WORK_REG_CODEResult
    {
        public short ID_WORK_CODE { get; set; }
        public string CD_WORK { get; set; }
        public string TX_WORK_DSCR { get; set; }
    }
}
