// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_UPDATE_NOTICE_TYPEResult
    {
        public int ID_UPDT_NTC { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public short? ID_REF_NTC_TYPE { get; set; }
        public DateTime? DT_UPDT_NTC { get; set; }
        public string CD_LANGUAGE_INDCTR { get; set; }
    }
}
