// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByPrimaryKey_REF_MESSAGEResult
    {
        public short ID_MESSAGES { get; set; }
        public string CD_MSSG_TYPE { get; set; }
        public string TX_MSSG_DSCR { get; set; }
    }
}
