// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdCaseNmbr_StudentResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public short ID_REF_CERT_ELIG { get; set; }
        public short ID_WORK_CODE { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
        public short? ID_WORK_CODE_MNTH2 { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public int? Age { get; set; }
        public string MEMBER_NAME { get; set; }
        public int ID_STDNT { get; set; }
        public string CD_MONTH { get; set; }
        public string FL_CHILD_CARE_PRVDR { get; set; }
        public string FL_ELGBL_STDNT { get; set; }
        public string FL_EMPLYD_PRTTM { get; set; }
        public string FL_FIT { get; set; }
        public string FL_HGHR_LRNNG { get; set; }
        public string FL_JOBS_TRNNG { get; set; }
        public string FL_MEAL_TCKT { get; set; }
        public string FL_OJT { get; set; }
        public string FL_PLUS_50_MEALS_CVRD { get; set; }
        public string FL_PRNT_OF_CHLD { get; set; }
        public string FL_RCVNG_TANF { get; set; }
        public string FL_SNGL_PRNT_STDNT { get; set; }
        public string FL_TITLE_IV { get; set; }
        public string FL_WORK_STDY_PRGRM { get; set; }
        public short? ID_VRFCTN_STUDENT { get; set; }
        public string TX_VRFCTN_STUDENT { get; set; }
    }
}
