// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbr_EmploymentForMedicareResult
    {
        public string NM_EMPLYR { get; set; }
        public string NO_EMPLYR_PHONE { get; set; }
        public string AD_STREET1 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_STATE { get; set; }
        public string AD_ZIP { get; set; }
        public decimal ID_INCM_TYPE { get; set; }
    }
}
