// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByTxIncmDscr_REF_EARNED_INCOME_TYPEResult
    {
        public decimal ID_INCM_TYPE { get; set; }
        public string TX_INCM_DSCR { get; set; }
    }
}
