// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetBySSNMemberMedResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public DateTime? DT_BRTH { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public decimal NO_CASE { get; set; }
        public decimal? AM_AWRD_ALLTMNT { get; set; }
        public DateTime? DT_CERT_STRT { get; set; }
        public DateTime? DT_CERT_END { get; set; }
        public DateTime? DT_STRT_ISSNC { get; set; }
        public string NO_SSN { get; set; }
        public int? ID_UNERND_INCM { get; set; }
    }
}
