// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetByIdMmbr_RESOURCEResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public string MEMBER_NAME { get; set; }
        public short ID_RSRC { get; set; }
        //public int ID_MMBR { get; set; }
        public short ID_RSRC_CODE { get; set; }
        public decimal? AM_RSRC_INCM { get; set; }
        public decimal? AM_RSRC_VALUE { get; set; }
        public decimal? AM_TRST_INTRST { get; set; }
        public decimal? AM_WTHDRWL_PNLTY { get; set; }
        public string FL_CHLD_TRUST_FUND { get; set; }
        public string FL_CRT_ORDRD { get; set; }
        public string FL_EXCLD_RSRC { get; set; }
        public string FL_JNT_ACCT { get; set; }
        public string FL_RCVNG_TRUST_INTRST { get; set; }
        public string FL_TRUST_ACCSSBL { get; set; }
        public string FL_WTHDRWL_PNLTY { get; set; }
        public decimal? ID_FRQNCY_INTRST { get; set; }
        public short? ID_VRFCTN_RSRC { get; set; }
        public string NM_BANK_INSTTTN { get; set; }
        public string NM_JNT_MMBR_LST { get; set; }
        public string NM_JNT_MMBR_FRST { get; set; }
        public string NM_JNT_MMBR_MDL { get; set; }
        public string NM_JNT_MMBR_SFX { get; set; }
        public string NM_SRC_LCTN { get; set; }
        public string NO_ACCT { get; set; }
        public string CD_MONTH { get; set; }
        public string CD_MONTH_TRANSLATED { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        //public short ID_RSRC_CODE { get; set; }
        public string CD_RSRC_CODE { get; set; }
        public string TX_RSRC_DSCR { get; set; }
    }
}
