// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetCountofCountableHouseholdMembersResult
    {
        public int ID_CASE_NMBR { get; set; }
        public int? HH_MMBR_COUNT { get; set; }
    }
}
