// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetDisqualifiedMmbrByIDCaseNmbrResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public short ID_REF_CERT_ELIG { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
        public string CD_CNVCTD_FLN { get; set; }
        public string CD_DSQLFD_PRTCPNT { get; set; }
        public string CD_FLEEING_VLTR { get; set; }
        public string CD_FRDLNT_MSRPRSNTTN { get; set; }
        public string CD_QLTY_SLLNG { get; set; }
        public string CD_RSDNT_TRTMNT { get; set; }
        public string CD_STMPS_MISUSE { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
