// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetIndividualCSAmountsResult
    {
        public int? ID_CRT_ORDRD_AMNT { get; set; }
        public int? MMBR_PAYING { get; set; }
        public int? ID_CASE_NMBR { get; set; }
        public string CD_CRT_ORDRD { get; set; }
        public string MEMBER_NAME { get; set; }
        public decimal? AMT_BILLED { get; set; }
        public decimal? ARRRS_PAID { get; set; }
        public decimal? AMT_PAID { get; set; }
        public decimal? CS_PAID_MNTHLY_AMNT { get; set; }
        public decimal? OTHER_CS_EXP_AMNT { get; set; }
        public string CD_MONTH { get; set; }
        public string CD_CASE_CRTD { get; set; }
        public string CD_VRFCTN_DETAIL_DSCR { get; set; }
    }
}
