// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetLifeline_CASESResult
    {
        public int ID_CASE_NMBR { get; set; }
        public decimal NO_CASE { get; set; }
        public string NO_HOME_TEL { get; set; }
        public string MEM_SSN { get; set; }
        public string MEM_NAME { get; set; }
        public string MEM_ADDRESS { get; set; }
    }
}
