// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetMmbrsBilledforDepCareResult
    {
        public int? MMBR_BILLED { get; set; }
        public int ID_PRVDR_NAME { get; set; }
    }
}
