// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetNVRA_AddressChangePopupResult
    {
        public string AU_NO_CASE { get; set; }
        public DateTime? POPUP_DATE { get; set; }
        public string ID_USER { get; set; }
        public int? ID_NMBR_LOGIN { get; set; }
        public string MEMBER_NAME { get; set; }
        public string CD_CNTY_DSCR { get; set; }
        public string WORKER_NAME { get; set; }
    }
}
