// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetPendingVerificationsResult
    {
        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public int ID_VRFCTN_ALIEN_STTS { get; set; }
        public string FLGALIEN { get; set; }
        public int FAVER { get; set; }
        public int FAID { get; set; }
        public string FLGLSTMNTH { get; set; }
        public int IDEMPLMNT { get; set; }
        public decimal INCTYP { get; set; }
        public string FLGSELFEMP { get; set; }
        public string FLGRPR { get; set; }
        public int? IDVRFEMP { get; set; }
        public string EMPLYERNM { get; set; }
        public int STRIKEID { get; set; }
        public int? STRIKEVRF { get; set; }
        public int UNCSUPRTID { get; set; }
        public int? UNCSUPRTVRF { get; set; }
        public int DCID { get; set; }
        public int? DCVRFCTN { get; set; }
        public int SHLTRID { get; set; }
        public int? SHLTRVRF { get; set; }
        public int UTLYID { get; set; }
        public int? UTLYVRF { get; set; }
        public int INSRID { get; set; }
        public int? INSRVRF { get; set; }
        public int MEID { get; set; }
        public int? MEVRF { get; set; }
        public int UNERNID { get; set; }
        public int UNERNTYP { get; set; }
        public int? UNERNVRF { get; set; }
        public int UNERNREFTYP { get; set; }
        public int IDRSCR { get; set; }
        public int RSCRCD { get; set; }
        public int? RSCRVRF { get; set; }
        public string RSCD { get; set; }
        public int? CRTORDVRF { get; set; }
        public int IDCRTORD { get; set; }
        public int DPNDNTID { get; set; }
        public int? DPNDNTVRF { get; set; }
        public int UTLTYID { get; set; }
        public int? UTLTYVRF { get; set; }
        public int IDSHLTR { get; set; }
        public int? VRFSHLTR { get; set; }
        public string SHLTREXPTYP { get; set; }
        public int INSRNCID { get; set; }
        public int? INSRNCVRF { get; set; }
        public int MEDID { get; set; }
        public int? MEDVRFEXP { get; set; }
        public int? MEDVRFRMNNG { get; set; }
    }
}
