// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetReopenVfcnCasesLessTwelveMonthCertResult
    {
        public int ID_CASE_NMBR { get; set; }
        public DateTime? DT_CERT_STRT { get; set; }
        public DateTime? DT_CERT_END { get; set; }
        public DateTime? AU_DT_CASE_STTS { get; set; }
        public DateTime? CS_DT_CASE_STTS { get; set; }
        public string CD_CASE_STTS_TYPE { get; set; }
        public string CS_CD_RJCTN_CLSR { get; set; }
        public decimal? NO_CASE { get; set; }
        public DateTime? DT_APPLD { get; set; }
        public DateTime? DT_APPRVL { get; set; }
        public string AU_CD_RJCTN_CLSR { get; set; }
        public string UPDATE_NOTICE_TYPE { get; set; }
        public string CD_RPRTNG_RQRMNT { get; set; }
        public string WORKER_NAME { get; set; }
        public string CD_CNTY_DSCR { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
