// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetSRCasesSixMonthCerts_TotalsOnlyResult
    {
        public string DT_AWARD { get; set; }
        public DateTime? DT_AWARD_MONTH { get; set; }
        public string CD_CNTY_DSCR { get; set; }
    }
}
