// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetSRCasesSixMonthCertsResult
    {
        public int ID_CASE_NMBR { get; set; }
        public decimal ID_REF_CASE_STATUS_TYPE { get; set; }
        public string CD_CASE_STTS_TYPE { get; set; }
        public string CD_RJCTN_CLSR { get; set; }
        public DateTime? DT_CERT_STRT { get; set; }
        public DateTime? DT_CERT_END { get; set; }
        public DateTime? DT_CASE_STTS { get; set; }
        public decimal? NO_CASE { get; set; }
        public DateTime? DT_APPLD { get; set; }
        public DateTime? DT_APPRVL { get; set; }
        public string NM_FULL_NAME { get; set; }
        public string CD_CNTY_DSCR { get; set; }
        public string CD_RJCTN_CLSR_SYNC { get; set; }
        public string TX_CASE_NOTE_DSCR { get; set; }
        public DateTime? DT_CASE_NOTE { get; set; }
        public string CD_RPRTNG_RQRMNT { get; set; }
        public string MEMBER_NAME { get; set; }
    }
}
