// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class GetVQSanctionsResult
    {
        public int ID_CASE_NMBR { get; set; }
        public string VQLast { get; set; }
        public string VQFirst { get; set; }
        public string VQMiddle { get; set; }
        public string FL_VLNTRY_QUIT { get; set; }
        public DateTime? DT_SNCTN_END { get; set; }
    }
}
