// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class IMPORT_GetAppStatusResult
    {
        public string APPLICATION_ID { get; set; }
        public string STATUS { get; set; }
    }
}
