// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class INSURANCE
    {
        public INSURANCE()
        {
            AU_INSURANCE = new HashSet<AU_INSURANCE>();
            INSURANCE_OTHER_PAYER = new HashSet<INSURANCE_OTHER_PAYER>();
            ID_MMBR = new HashSet<MEMBER>();
        }

        public int ID_INSRNC { get; set; }
        public decimal ID_INSRNC_PAYER { get; set; }
        public int ID_PRVDR_NAME { get; set; }
        public decimal? AM_PREMIUM { get; set; }
        public decimal? AM_PREMIUM_MNTHLY { get; set; }
        public decimal? AM_TTL_PREMIUM_PAID { get; set; }
        public string CD_MONTH { get; set; }
        public DateTime? DT_PREMIUM_PAID { get; set; }
        public decimal? ID_FRQNCY_PREMIUM { get; set; }
        public short? ID_VRFCTN_INSRNC { get; set; }
        public decimal? NO_HH_MMBR { get; set; }
        public string TX_VRFCTN_INSRNC { get; set; }
        public string TX_VRFCTN_INSRNC_OTHER { get; set; }

        public virtual REF_INSRNC_PAYER ID_INSRNC_PAYERNavigation { get; set; }
        public virtual REF_PROVIDER_NAME ID_PRVDR_NAMENavigation { get; set; }
        public virtual ICollection<AU_INSURANCE> AU_INSURANCE { get; set; }
        public virtual ICollection<INSURANCE_OTHER_PAYER> INSURANCE_OTHER_PAYER { get; set; }

        public virtual ICollection<MEMBER> ID_MMBR { get; set; }
    }
}