// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class INSURANCE_OTHER_PAYER
    {
        public INSURANCE_OTHER_PAYER()
        {
            UNEARNED_INCOME = new HashSet<UNEARNED_INCOME>();
        }

        public short ID_INSRNC_OTHR_PAYER { get; set; }
        public int ID_INSRNC { get; set; }
        public int? ID_MMBR { get; set; }
        public decimal? AM_PREMIUM_OTHR_PAYER { get; set; }
        public DateTime? DT_INSRNC_OTHR_PAYER { get; set; }
        public string FL_INSRNC_PAY_MMBR { get; set; }
        public string FL_INSRNC_PAY_ONGOING { get; set; }
        public string FL_PAY_HH_MMBR_MNTHLY { get; set; }
        public string FL_PAY_PREMIUM_CRRNT_MNTH { get; set; }
        public decimal? ID_FRQNCY_INSRNC_OTHR_PAYER { get; set; }
        public short? ID_VRFCTN_INSRNC_OTHR_PAYER { get; set; }
        public string TX_VRFCTN_INSRNC_OTHR_PAYER { get; set; }

        public virtual INSURANCE ID_INSRNCNavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual ICollection<UNEARNED_INCOME> UNEARNED_INCOME { get; set; }
    }
}