// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class MEAL_OTHER
    {
        public MEAL_OTHER()
        {
            MEAL = new HashSet<MEAL>();
        }

        public short ID_MEAL_OTHER { get; set; }
        public int? ID_CASE_NMBR { get; set; }
        public string CD_MONTH { get; set; }
        public string NM_MEAL_OTHR_LST { get; set; }
        public string NM_MEAL_OTHR_FRST { get; set; }
        public string NM_MEAL_OTHR_MDL { get; set; }
        public string NM_MEAL_OTHR_SFX { get; set; }

        public virtual CASE ID_CASE_NMBRNavigation { get; set; }
        public virtual ICollection<MEAL> MEAL { get; set; }
    }
}