// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class MEAL
    {
        public MEAL()
        {
            AU_MEAL = new HashSet<AU_MEAL>();
        }

        public int ID_MEAL { get; set; }
        public int? ID_EMPLYMNT { get; set; }
        public int? ID_MMBR { get; set; }
        public short? ID_MEAL_OTHER { get; set; }
        public short? ID_RSRC { get; set; }
        public decimal? AM_MEAL_COST_HOH { get; set; }
        public decimal? AM_MEAL_MMBR_PAY { get; set; }
        public string CD_MONTH { get; set; }
        public decimal? ID_FRQNCY_MEAL_COST { get; set; }
        public decimal? ID_FRQNCY_MEAL_PAY { get; set; }
        public short? ID_VRFCTN_MEAL { get; set; }
        public decimal? NO_MEALS { get; set; }
        public string TX_VRFCTN_MEAL { get; set; }

        public virtual EMPLOYMENT ID_EMPLYMNTNavigation { get; set; }
        public virtual MEAL_OTHER ID_MEAL_OTHERNavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual RESOURCE ID_RSRCNavigation { get; set; }
        public virtual ICollection<AU_MEAL> AU_MEAL { get; set; }
    }
}