// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class MEDICAL_EXPENSE_OTHER_PAYER
    {
        public MEDICAL_EXPENSE_OTHER_PAYER()
        {
            UNEARNED_INCOME = new HashSet<UNEARNED_INCOME>();
        }

        public short ID_ME_OTHR_PAYER { get; set; }
        public int? ID_MMBR { get; set; }
        public int ID_MDCL_EXPNS { get; set; }
        public decimal? AM_ME_OTHR_PAY { get; set; }
        public DateTime? DT_ME_OTHR_PAYER { get; set; }
        public string FL_ME_ONETIME { get; set; }
        public string FL_ME_PAID_BFR_AMNT_DTRMND { get; set; }
        public string FL_ME_PAY_CRRNT_MNTH { get; set; }
        public string FL_ME_PAY_MMBR { get; set; }
        public short? ID_VRFCTN_ME_OTHR_PAYER { get; set; }

        public virtual MEDICAL_EXPENSE ID_MDCL_EXPNSNavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual ICollection<UNEARNED_INCOME> UNEARNED_INCOME { get; set; }
    }
}