// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class MEDICAL_EXPENSE
    {
        public MEDICAL_EXPENSE()
        {
            AU_MEDICAL_EXPENSE = new HashSet<AU_MEDICAL_EXPENSE>();
            MEDICAL_EXPENSE_ONGOING = new HashSet<MEDICAL_EXPENSE_ONGOING>();
            MEDICAL_EXPENSE_OTHER_PAYER = new HashSet<MEDICAL_EXPENSE_OTHER_PAYER>();
            MEDICAL_NOTES = new HashSet<MEDICAL_NOTES>();
        }

        public int ID_MDCL_EXPNS { get; set; }
        public int ID_MMBR { get; set; }
        public int? ID_MDCTN_APPLNC { get; set; }
        public int? ID_TRIPS { get; set; }
        public int ID_PRVDR_NAME { get; set; }
        public short? ID_SMRY_MDCL_EXPNS { get; set; }
        public decimal? AM_AGREED_MNTHLY { get; set; }
        public decimal? AM_CALCLTD_MNTHLY { get; set; }
        public decimal? AM_UNERND_INCM { get; set; }
        public decimal? AM_PAY_MNTHLY { get; set; }
        public decimal? AM_RECALCLTD_MNTHLY { get; set; }
        public decimal? AM_RMNNG_OWED { get; set; }
        public decimal? AM_ME_TTL_ALLWBL { get; set; }
        public decimal? AM_TTL_ONETIME_RX { get; set; }
        public decimal? AM_TTL_ONGOING_RX { get; set; }
        public string CD_MONTH { get; set; }
        public DateTime? DT_SRVC { get; set; }
        public string FL_ASSSTD_BY_OTHR { get; set; }
        public string FL_AVG_ONETIME { get; set; }
        public string FL_INSRNC_PAID_ALL { get; set; }
        public string FL_ONETIME { get; set; }
        public string FL_ONETIME_USE { get; set; }
        public string FL_PAY_BILL_MNTHLY { get; set; }
        public string FL_RPYMNT_AGRMNT { get; set; }
        public decimal? ID_FRQNCY_ME_DETAIL { get; set; }
        public short? ID_VRFCTN_MDCL_EXPNS { get; set; }
        public short? ID_VRFCTN_RMNNG { get; set; }
        public string NO_ACCT_MDCL { get; set; }
        public decimal? NO_MEALS_MNTHLY { get; set; }
        public decimal? NO_MNTHS_OWED { get; set; }
        public decimal? NO_MNTHS_RMNNG { get; set; }

        public virtual REF_MEDICATION_APPLIANCE ID_MDCTN_APPLNCNavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual REF_PROVIDER_NAME ID_PRVDR_NAMENavigation { get; set; }
        public virtual SMRY_MEDICAL_EXPENSE ID_SMRY_MDCL_EXPNSNavigation { get; set; }
        public virtual TRIP ID_TRIPSNavigation { get; set; }
        public virtual ICollection<AU_MEDICAL_EXPENSE> AU_MEDICAL_EXPENSE { get; set; }
        public virtual ICollection<MEDICAL_EXPENSE_ONGOING> MEDICAL_EXPENSE_ONGOING { get; set; }
        public virtual ICollection<MEDICAL_EXPENSE_OTHER_PAYER> MEDICAL_EXPENSE_OTHER_PAYER { get; set; }
        public virtual ICollection<MEDICAL_NOTES> MEDICAL_NOTES { get; set; }
    }
}