// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class MEMBER_TRNSFR_RSRC
    {
        public MEMBER_TRNSFR_RSRC()
        {
            AU_MEMBER_TRNSFR_RSRC = new HashSet<AU_MEMBER_TRNSFR_RSRC>();
        }

        public int ID_MMBR_RSRC { get; set; }
        public short ID_RSRC_CODE { get; set; }
        public int ID_MMBR { get; set; }
        public decimal? AM_TRNSFR_RSRC_RCVD { get; set; }
        public decimal? AM_VALUE { get; set; }
        public string CD_MONTH { get; set; }
        public DateTime? DT_ACTN_TRNSFR_RSRC { get; set; }
        public string FL_EXCLD { get; set; }
        public string FL_TRNSFR_QLFY_FA { get; set; }
        public string TX_DSPSL_RSN { get; set; }

        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual REF_RESOURCE_TYPE ID_RSRC_CODENavigation { get; set; }
        public virtual ICollection<AU_MEMBER_TRNSFR_RSRC> AU_MEMBER_TRNSFR_RSRC { get; set; }
    }
}