// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class MEMBER
    {
        public MEMBER()
        {
            ADDRESS = new HashSet<ADDRESS>();
            ALIEN_STATUS = new HashSet<ALIEN_STATUS>();
            AU_MEMBER = new HashSet<AU_MEMBER>();
            CASE_NOTES = new HashSet<CASE_NOTES>();
            CS_AMOUNT = new HashSet<CS_AMOUNT>();
            CS_DPNDNTS = new HashSet<CS_DPNDNTS>();
            DEPENDENT_CAREID_MMBR1Navigation = new HashSet<DEPENDENT_CARE>();
            DEPENDENT_CAREID_MMBRNavigation = new HashSet<DEPENDENT_CARE>();
            DEPENDENT_CARE_OTHER_PAYER = new HashSet<DEPENDENT_CARE_OTHER_PAYER>();
            EMPLOYMENT = new HashSet<EMPLOYMENT>();
            FA_STATUS = new HashSet<FA_STATUS>();
            INSURANCE_OTHER_PAYER = new HashSet<INSURANCE_OTHER_PAYER>();
            MEAL = new HashSet<MEAL>();
            MEDICAL_EXPENSE = new HashSet<MEDICAL_EXPENSE>();
            MEDICAL_EXPENSE_OTHER_PAYER = new HashSet<MEDICAL_EXPENSE_OTHER_PAYER>();
            MEMBER_TRNSFR_RSRC = new HashSet<MEMBER_TRNSFR_RSRC>();
            OUTSIDE_DEPENDENT = new HashSet<OUTSIDE_DEPENDENT>();
            PIV_MMBR_RLTNID_MMBR1Navigation = new HashSet<PIV_MMBR_RLTN>();
            PIV_MMBR_RLTNID_MMBR2Navigation = new HashSet<PIV_MMBR_RLTN>();
            RESOURCE = new HashSet<RESOURCE>();
            ROOM = new HashSet<ROOM>();
            SANCTION = new HashSet<SANCTION>();
            SHELTER_EXPENSEID_MMBR1Navigation = new HashSet<SHELTER_EXPENSE>();
            SHELTER_EXPENSEID_MMBR2Navigation = new HashSet<SHELTER_EXPENSE>();
            SHELTER_EXPENSE_OTHER_PAYER = new HashSet<SHELTER_EXPENSE_OTHER_PAYER>();
            STUDENT = new HashSet<STUDENT>();
            TANF_MMBR_INCLUDED = new HashSet<TANF_MMBR_INCLUDED>();
            UNEARNED_INCOME = new HashSet<UNEARNED_INCOME>();
            UTILITY_EXPENSEID_MMBR1Navigation = new HashSet<UTILITY_EXPENSE>();
            UTILITY_EXPENSEID_MMBR2Navigation = new HashSet<UTILITY_EXPENSE>();
            UTILITY_EXPENSE_OTHER_PAYER = new HashSet<UTILITY_EXPENSE_OTHER_PAYER>();
            ID_INSRNC = new HashSet<INSURANCE>();
        }

        public int ID_MMBR { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public short ID_RACE_CODE { get; set; }
        public short ID_REF_CERT_ELIG { get; set; }
        public short ID_WORK_CODE { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
        public short? ID_WORK_CODE_MNTH2 { get; set; }
        public string CD_CASE_CRTD { get; set; }
        public decimal? CD_EDCTN_LVL { get; set; }
        public string CD_MMBR_ELIG { get; set; }
        public string CD_SEX { get; set; }
        public string DPNDNT_NMBR { get; set; }
        public DateTime? DT_BRTH { get; set; }
        public string FL_ABAWD { get; set; }
        public string FL_CLOSE_RLTN { get; set; }
        public string CD_CNVCTD_FLN { get; set; }
        public string FL_CTGRCLLY_ELGBL { get; set; }
        public string FL_CRRNT_FS_CRTFD { get; set; }
        public string FL_DHR_EMPL { get; set; }
        public string CD_DSQLFD_PRTCPNT { get; set; }
        public string FL_ELGBL_ALIEN { get; set; }
        public string CD_FLEEING_VLTR { get; set; }
        public string FL_FRMR_HH_MMBR { get; set; }
        public string CD_FRDLNT_MSRPRSNTTN { get; set; }
        public string FL_GIVE_FA_MONEY { get; set; }
        public string FL_GROUP_HOME { get; set; }
        public string FL_HOH { get; set; }
        public string FL_IN_SCHOOL { get; set; }
        public string FL_MGRNT_SSNL { get; set; }
        public string FL_NON_MMBR { get; set; }
        public string FL_NON_MMBR_RSDNT { get; set; }
        public string FL_PAYS_BILLS { get; set; }
        public string FL_PAYS_MEAL { get; set; }
        public string FL_PAYS_ROOM { get; set; }
        public string FL_PRNTL_GDNC { get; set; }
        public string FL_PRCHS_PRPRS { get; set; }
        public string CD_QLTY_SLLNG { get; set; }
        public string FL_RM { get; set; }
        public string CD_RSDNT_TRTMNT { get; set; }
        public string FL_SNCTN { get; set; }
        public string CD_STMPS_MISUSE { get; set; }
        public string FL_US_CTZN { get; set; }
        public string FL_WRK_RGSTRTN_EXMPT { get; set; }
        public string FL_WRKNG { get; set; }
        public short? ID_VRFCTN_ALIEN_STTS { get; set; }
        public short? ID_VRFCTN_EXPDT { get; set; }
        public decimal? NO_BRDR_HH { get; set; }
        public string NO_CELLPHONE { get; set; }
        public string NO_SSN { get; set; }
        public string NM_MMBR_LST { get; set; }
        public string NM_MMBR_FRST { get; set; }
        public string NM_MMBR_MDL { get; set; }
        public string NM_MMBR_SFX { get; set; }
        public int? SCI_DEPENDENT_NBR { get; set; }
        public string TX_VRFCTN_ALIEN_STTS { get; set; }
        public string TX_VRFCTN_EXPDT { get; set; }
        public DateTime? DT_VQEXEMPTORCOMPLY { get; set; }
        public string VOTER_ANS { get; set; }
        public string VOTER_TXT { get; set; }
        public string FullName { get; set; }

        public virtual CASE ID_CASE_NMBRNavigation { get; set; }
        public virtual REF_RACE ID_RACE_CODENavigation { get; set; }
        public virtual REF_CERT_ELIG ID_REF_CERT_ELIGNavigation { get; set; }
        public virtual REF_CERT_ELIG ID_REF_CERT_ELIG_MNTH2Navigation { get; set; }
        public virtual REF_WORK_REG_CODE ID_WORK_CODENavigation { get; set; }
        public virtual REF_WORK_REG_CODE ID_WORK_CODE_MNTH2Navigation { get; set; }
        public virtual ICollection<ADDRESS> ADDRESS { get; set; }
        public virtual ICollection<ALIEN_STATUS> ALIEN_STATUS { get; set; }
        public virtual ICollection<AU_MEMBER> AU_MEMBER { get; set; }
        public virtual ICollection<CASE_NOTES> CASE_NOTES { get; set; }
        public virtual ICollection<CS_AMOUNT> CS_AMOUNT { get; set; }
        public virtual ICollection<CS_DPNDNTS> CS_DPNDNTS { get; set; }
        public virtual ICollection<DEPENDENT_CARE> DEPENDENT_CAREID_MMBR1Navigation { get; set; }
        public virtual ICollection<DEPENDENT_CARE> DEPENDENT_CAREID_MMBRNavigation { get; set; }
        public virtual ICollection<DEPENDENT_CARE_OTHER_PAYER> DEPENDENT_CARE_OTHER_PAYER { get; set; }
        public virtual ICollection<EMPLOYMENT> EMPLOYMENT { get; set; }
        public virtual ICollection<FA_STATUS> FA_STATUS { get; set; }
        public virtual ICollection<INSURANCE_OTHER_PAYER> INSURANCE_OTHER_PAYER { get; set; }
        public virtual ICollection<MEAL> MEAL { get; set; }
        public virtual ICollection<MEDICAL_EXPENSE> MEDICAL_EXPENSE { get; set; }
        public virtual ICollection<MEDICAL_EXPENSE_OTHER_PAYER> MEDICAL_EXPENSE_OTHER_PAYER { get; set; }
        public virtual ICollection<MEMBER_TRNSFR_RSRC> MEMBER_TRNSFR_RSRC { get; set; }
        public virtual ICollection<OUTSIDE_DEPENDENT> OUTSIDE_DEPENDENT { get; set; }
        public virtual ICollection<PIV_MMBR_RLTN> PIV_MMBR_RLTNID_MMBR1Navigation { get; set; }
        public virtual ICollection<PIV_MMBR_RLTN> PIV_MMBR_RLTNID_MMBR2Navigation { get; set; }
        public virtual ICollection<RESOURCE> RESOURCE { get; set; }
        public virtual ICollection<ROOM> ROOM { get; set; }
        public virtual ICollection<SANCTION> SANCTION { get; set; }
        public virtual ICollection<SHELTER_EXPENSE> SHELTER_EXPENSEID_MMBR1Navigation { get; set; }
        public virtual ICollection<SHELTER_EXPENSE> SHELTER_EXPENSEID_MMBR2Navigation { get; set; }
        public virtual ICollection<SHELTER_EXPENSE_OTHER_PAYER> SHELTER_EXPENSE_OTHER_PAYER { get; set; }
        public virtual ICollection<STUDENT> STUDENT { get; set; }
        public virtual ICollection<TANF_MMBR_INCLUDED> TANF_MMBR_INCLUDED { get; set; }
        public virtual ICollection<UNEARNED_INCOME> UNEARNED_INCOME { get; set; }
        public virtual ICollection<UTILITY_EXPENSE> UTILITY_EXPENSEID_MMBR1Navigation { get; set; }
        public virtual ICollection<UTILITY_EXPENSE> UTILITY_EXPENSEID_MMBR2Navigation { get; set; }
        public virtual ICollection<UTILITY_EXPENSE_OTHER_PAYER> UTILITY_EXPENSE_OTHER_PAYER { get; set; }

        public virtual ICollection<INSURANCE> ID_INSRNC { get; set; }
    }
}