// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class NAC_MATCH
    {
        public int ID_MMBR { get; set; }
        public int? ID_CASE_NMBR { get; set; }
        public string NO_SSN { get; set; }
        public string FullName { get; set; }
        public short? ID_REF_CERT_ELIG { get; set; }
        public short? ID_REF_CERT_ELIG_MNTH2 { get; set; }
        public string FL_NAC_MATCH { get; set; }
        public DateTime? DT_NAC_MATCH { get; set; }
        public string LEX_ID_SCORE { get; set; }
        public string MATCH_CD { get; set; }
        public string SRCH_BENE_MM { get; set; }
    }
}