// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class OACIS_ERRORS
    {
        public int ID_ERROR { get; set; }
        public string CD_REF_MODULE { get; set; }
        public string ID_USER { get; set; }
        public DateTime? DT_ERROR { get; set; }
        public string TX_ERROR { get; set; }
        public string TX_TARGET { get; set; }
    }
}