// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class OACIS_OIL_EXTRACTResult
    {
        public string No_Case { get; set; }
        public string Dt_Apprvl { get; set; }
        public string Case_Status { get; set; }
    }
}
