// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class OACIS_CASE_BEING_WORKED
    {
        public decimal NO_CASE { get; set; }
        public string ID_USER { get; set; }
        public DateTime DT_CRTD { get; set; }
    }
}