// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class OUTSIDE_DEPENDENT
    {
        public OUTSIDE_DEPENDENT()
        {
            AU_DEPENDENT = new HashSet<AU_DEPENDENT>();
            CS_DPNDNTS = new HashSet<CS_DPNDNTS>();
            DEPENDENT_CARE = new HashSet<DEPENDENT_CARE>();
            ID_CRT_ORDRD_AMNT = new HashSet<COURT_ORDERED_AMOUNT>();
        }

        public int ID_DPNDNT { get; set; }
        public int ID_MMBR { get; set; }
        public DateTime? DT_DPNDNT_DOB { get; set; }
        public string FL_CHILD { get; set; }
        public string NM_DPNDNT_LST { get; set; }
        public string NM_DPNDNT_FRST { get; set; }
        public string NM_DPNDNT_MDL { get; set; }
        public string NM_DPNDNT_SFX { get; set; }

        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual ICollection<AU_DEPENDENT> AU_DEPENDENT { get; set; }
        public virtual ICollection<CS_DPNDNTS> CS_DPNDNTS { get; set; }
        public virtual ICollection<DEPENDENT_CARE> DEPENDENT_CARE { get; set; }

        public virtual ICollection<COURT_ORDERED_AMOUNT> ID_CRT_ORDRD_AMNT { get; set; }
    }
}