// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class Query
    {
        public decimal? no_case { get; set; }
        public string em_hoh { get; set; }
        public DateTime? DT_APPRVL { get; set; }
        public string TX_CASE_STTS_DSCR { get; set; }
    }
}