// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_PROVIDER_TYPE
    {
        public REF_PROVIDER_TYPE()
        {
            REF_PROVIDER_NAME = new HashSet<REF_PROVIDER_NAME>();
        }

        public short ID_PRVDR_TYPE { get; set; }
        public string CD_PRVDR_TYPE { get; set; }
        public string TX_PRVDR_DSCR { get; set; }

        public virtual ICollection<REF_PROVIDER_NAME> REF_PROVIDER_NAME { get; set; }
    }
}