// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_INSRNC_PAYER
    {
        public REF_INSRNC_PAYER()
        {
            INSURANCE = new HashSet<INSURANCE>();
        }

        public decimal ID_INSRNC_PAYER { get; set; }
        public string CD_PAYER_DSCR { get; set; }

        public virtual ICollection<INSURANCE> INSURANCE { get; set; }
    }
}