// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_NOTICE_TYPE
    {
        public REF_NOTICE_TYPE()
        {
            UPDATE_NOTICE_TYPE = new HashSet<UPDATE_NOTICE_TYPE>();
        }

        public short ID_REF_NTC_TYPE { get; set; }
        public string CD_REF_NTC_TYPE { get; set; }
        public string TX_REF_NTC_DSCR { get; set; }

        public virtual ICollection<UPDATE_NOTICE_TYPE> UPDATE_NOTICE_TYPE { get; set; }
    }
}