// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_DEPENDENT_CARE_LIMIT
    {
        public decimal ID_DPNDNT_CARE_LIMIT { get; set; }
        public decimal? AM_DPNDNT_LIMIT { get; set; }
        public string CD_DPNDNT_CARE { get; set; }
        public string CD_DPNDNT_CARE_DSCR { get; set; }
    }
}