// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_ADDRESS_TYPE
    {
        public REF_ADDRESS_TYPE()
        {
            ADDRESS = new HashSet<ADDRESS>();
        }

        public decimal ID_REF_ADDRSS_TYPE { get; set; }
        public string CD_REF_ADDRSS_TYPE { get; set; }

        public virtual ICollection<ADDRESS> ADDRESS { get; set; }
    }
}