// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_VERIFICATION_SUBTYPE
    {
        public REF_VERIFICATION_SUBTYPE()
        {
            REF_VERIFICATION_DETAIL = new HashSet<REF_VERIFICATION_DETAIL>();
        }

        public decimal ID_REF_VRFCTN_SUBTYPE { get; set; }
        public decimal ID_REF_VRFCTN_TYPE { get; set; }
        public string CD_REF_VRFCTN_SUBTYPE { get; set; }
        public string TX_REF_VRFCTN_SUBTYPE_DSCR { get; set; }

        public virtual REF_VERIFICATION_TYPE ID_REF_VRFCTN_TYPENavigation { get; set; }
        public virtual ICollection<REF_VERIFICATION_DETAIL> REF_VERIFICATION_DETAIL { get; set; }
    }
}