// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_INACTIVE_SCIII
    {
        public string ID_SSN { get; set; }
        public decimal? CD_CHCK_DIGIT { get; set; }
        public decimal? CD_CNTY_SCIII { get; set; }
        public decimal? NO_INACTV_CASE { get; set; }
    }
}