// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_COURT_ORDERED_TYPE
    {
        public REF_COURT_ORDERED_TYPE()
        {
            COURT_ORDERED_AMOUNT = new HashSet<COURT_ORDERED_AMOUNT>();
        }

        public decimal ID_CRT_ORDRD { get; set; }
        public string CD_CRT_ORDRD { get; set; }
        public string TX_CRT_ORDRD_DSCR { get; set; }

        public virtual ICollection<COURT_ORDERED_AMOUNT> COURT_ORDERED_AMOUNT { get; set; }
    }
}