// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_SHELTER_DWELLING_TYPE
    {
        public REF_SHELTER_DWELLING_TYPE()
        {
            SHELTER_EXPENSE = new HashSet<SHELTER_EXPENSE>();
        }

        public short ID_SHLTR_DWELLNG_TYPE { get; set; }
        public string CD_SHLTR_DWELLING_TYPE { get; set; }

        public virtual ICollection<SHELTER_EXPENSE> SHELTER_EXPENSE { get; set; }
    }
}