// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_PAY_TYPE
    {
        public int ID_PAY_TYPE { get; set; }
        public string CD_PAY_TYPE { get; set; }
    }
}