// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_UNEARNED_SUBTYPE
    {
        public REF_UNEARNED_SUBTYPE()
        {
            UNEARNED_INCOME = new HashSet<UNEARNED_INCOME>();
        }

        public int ID_REF_UNERND_SUBTYPE { get; set; }
        public int ID_REF_UNERND_TYPE { get; set; }
        public string CD_UNERND_SUBTYPE { get; set; }
        public string TX_UNERND_SUBTYPE { get; set; }

        public virtual REF_UNEARNED_TYPE ID_REF_UNERND_TYPENavigation { get; set; }
        public virtual ICollection<UNEARNED_INCOME> UNEARNED_INCOME { get; set; }
    }
}