// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_OACIS_MODULE
    {
        public string CD_REF_MODULE { get; set; }
        public string CD_MODULE_PRED { get; set; }
        public string TX_REF_MODULE { get; set; }
        public string CD_MODULE_ORDER { get; set; }
        public string CD_MODULE_NEXT { get; set; }
        public string CD_MODULE_LCTN { get; set; }
    }
}