// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_SANCTION_REASON
    {
        public REF_SANCTION_REASON()
        {
            SANCTION = new HashSet<SANCTION>();
        }

        public decimal ID_REF_SNCTN_RSN { get; set; }
        public short ID_REF_SNCTN_TYPE { get; set; }
        public string CD_SNCTN_RSN { get; set; }
        public string TX_SNCTN_RSN { get; set; }

        public virtual REF_SANCTION_TYPE ID_REF_SNCTN_TYPENavigation { get; set; }
        public virtual ICollection<SANCTION> SANCTION { get; set; }
    }
}