// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_SCI2_ERRORS
    {
        public REF_SCI2_ERRORS()
        {
            SCI2_ERRORS = new HashSet<SCI2_ERRORS>();
        }

        public short ID_REF_SCI2_ERROR { get; set; }
        public string CD_SCI2_ERROR { get; set; }
        public string TX_SCI2_ERROR_DSCR { get; set; }

        public virtual ICollection<SCI2_ERRORS> SCI2_ERRORS { get; set; }
    }
}