// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_RJCTN_DNL_TERM
    {
        public REF_RJCTN_DNL_TERM()
        {
            CASE_STATUS = new HashSet<CASE_STATUS>();
        }

        public string CD_RJCTN_CLSR { get; set; }
        public string CD_DENIAL { get; set; }
        public string CD_TRMNTN { get; set; }
        public string TX_RJCTN_DNL_TERM { get; set; }

        public virtual ICollection<CASE_STATUS> CASE_STATUS { get; set; }
    }
}