// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_VERIFICATION_TYPE
    {
        public REF_VERIFICATION_TYPE()
        {
            REF_VERIFICATION_SUBTYPE = new HashSet<REF_VERIFICATION_SUBTYPE>();
        }

        public decimal ID_REF_VRFCTN_TYPE { get; set; }
        public string CD_REF_VRFCTN_TYPE { get; set; }
        public string TX_REF_VRFCTN_DSCR { get; set; }

        public virtual ICollection<REF_VERIFICATION_SUBTYPE> REF_VERIFICATION_SUBTYPE { get; set; }
    }
}