// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_HOLIDAY_DATES
    {
        public short ID_HLDY_DATES { get; set; }
        public DateTime? DT_HLDY { get; set; }
        public string TX_HLDY_DSCR { get; set; }
    }
}