// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_RESTORATION_REASON_TYPE
    {
        public REF_RESTORATION_REASON_TYPE()
        {
            RESTORATION = new HashSet<RESTORATION>();
        }

        public decimal ID_RSTRTN_RSN { get; set; }
        public string CD_RSTRTN_RSN { get; set; }
        public string TX_RSTRTN_RSN_DSCR { get; set; }

        public virtual ICollection<RESTORATION> RESTORATION { get; set; }
    }
}