// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_PROVIDER_NAME
    {
        public REF_PROVIDER_NAME()
        {
            ADDRESS = new HashSet<ADDRESS>();
            DEPENDENT_CARE = new HashSet<DEPENDENT_CARE>();
            INSURANCE = new HashSet<INSURANCE>();
            MEDICAL_EXPENSE = new HashSet<MEDICAL_EXPENSE>();
            REF_MEDICATION_APPLIANCE = new HashSet<REF_MEDICATION_APPLIANCE>();
            TRIP = new HashSet<TRIP>();
        }

        public int ID_PRVDR_NAME { get; set; }
        public short ID_PRVDR_TYPE { get; set; }
        public string NM_PRVDR { get; set; }
        public string NO_PRVDR_PHONE { get; set; }

        public virtual REF_PROVIDER_TYPE ID_PRVDR_TYPENavigation { get; set; }
        public virtual ICollection<ADDRESS> ADDRESS { get; set; }
        public virtual ICollection<DEPENDENT_CARE> DEPENDENT_CARE { get; set; }
        public virtual ICollection<INSURANCE> INSURANCE { get; set; }
        public virtual ICollection<MEDICAL_EXPENSE> MEDICAL_EXPENSE { get; set; }
        public virtual ICollection<REF_MEDICATION_APPLIANCE> REF_MEDICATION_APPLIANCE { get; set; }
        public virtual ICollection<TRIP> TRIP { get; set; }
    }
}