// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_INSTRUCTIONS
    {
        public short ID_INSTRCTN { get; set; }
        public string CD_INSTRCTN_TYPE { get; set; }
        public string TX_INSTRCTN_TYPE { get; set; }
    }
}