// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_CNTY_ADDRESS
    {
        public short ID_CNTY_ADDRESS { get; set; }
        public short ID_CNTY_STATE { get; set; }
        public short OFFICE_CODE { get; set; }
        public string AD_STREET1 { get; set; }
        public string AD_STREET2 { get; set; }
        public string AD_CITY { get; set; }
        public string AD_ZIP { get; set; }
        public string AD_ZIP4 { get; set; }
        public string NO_OFFICE_PHONE { get; set; }
        public string NO_OFFICE_FAX { get; set; }
    }
}