// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_TFP_LIMIT
    {
        public decimal ID_REF_TFP_LIMIT { get; set; }
        public decimal? AM_TFP_LIMIT { get; set; }
        public decimal? NO_HH_SIZE { get; set; }
    }
}