// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_CASE_CTGRY
    {
        public REF_CASE_CTGRY()
        {
            CASE_NOTES = new HashSet<CASE_NOTES>();
        }

        public short ID_CASE_CTGRY { get; set; }
        public string CD_CASE_CTGRY { get; set; }
        public string CD_CASE_CTGRY_DSCR { get; set; }

        public virtual ICollection<CASE_NOTES> CASE_NOTES { get; set; }
    }
}