// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_RACE
    {
        public REF_RACE()
        {
            MEMBER = new HashSet<MEMBER>();
        }

        public short ID_RACE_CODE { get; set; }
        public decimal? CD_RACE { get; set; }
        public string TX_RACE_DSCR { get; set; }

        public virtual ICollection<MEMBER> MEMBER { get; set; }
    }
}