// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_FREQUENCY
    {
        public decimal ID_FRQNCY_REF { get; set; }
        public string CD_FRQNCY { get; set; }
        public string CD_FRQNCY_DSCR { get; set; }
        public decimal? NO_FRQNCY_FACTOR { get; set; }
    }
}