// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_CASE_STATUS_TYPE
    {
        public REF_CASE_STATUS_TYPE()
        {
            CASE_STATUS = new HashSet<CASE_STATUS>();
        }

        public decimal ID_REF_CASE_STATUS_TYPE { get; set; }
        public string CD_CASE_STTS_TYPE { get; set; }
        public string TX_CASE_STTS_DSCR { get; set; }

        public virtual ICollection<CASE_STATUS> CASE_STATUS { get; set; }
    }
}