// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_DHR_EMPLOYEE
    {
        public string ID_SSN_DHREMP { get; set; }
    }
}