// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_EARNED_INCOME_TYPE
    {
        public REF_EARNED_INCOME_TYPE()
        {
            EMPLOYMENT = new HashSet<EMPLOYMENT>();
        }

        public decimal ID_INCM_TYPE { get; set; }
        public string CD_INCM_TYPE { get; set; }
        public string TX_INCM_DSCR { get; set; }

        public virtual ICollection<EMPLOYMENT> EMPLOYMENT { get; set; }
    }
}