// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_IEVS_TRAK
    {
        public string ID_SSN_IEVS { get; set; }
        public string IEVS_CASE { get; set; }
        public string CD_SSN_VRFY { get; set; }
        public string CERT_END_DATE { get; set; }
    }
}