// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_MESSAGE
    {
        public short ID_MESSAGES { get; set; }
        public string CD_MSSG_TYPE { get; set; }
        public string TX_MSSG_DSCR { get; set; }
        public string FL_SEARCH { get; set; }
    }
}