// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_RESOURCE_TYPE
    {
        public REF_RESOURCE_TYPE()
        {
            MEMBER_TRNSFR_RSRC = new HashSet<MEMBER_TRNSFR_RSRC>();
            RESOURCE = new HashSet<RESOURCE>();
        }

        public short ID_RSRC_CODE { get; set; }
        public string CD_RSRC_CODE { get; set; }
        public string TX_RSRC_DSCR { get; set; }

        public virtual ICollection<MEMBER_TRNSFR_RSRC> MEMBER_TRNSFR_RSRC { get; set; }
        public virtual ICollection<RESOURCE> RESOURCE { get; set; }
    }
}