// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_COUNTY_GROUP_EMAIL
    {
        public short ID_CNTY_STATE { get; set; }
        public short CD_TRCKNG_OFFC { get; set; }
        public string TX_EMAIL { get; set; }
    }
}