// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_UTILITY_DEDUCTION
    {
        public REF_UTILITY_DEDUCTION()
        {
            REGISTER_UTILITY_EXPENSE = new HashSet<REGISTER_UTILITY_EXPENSE>();
            UTILITY_EXPENSE = new HashSet<UTILITY_EXPENSE>();
        }

        public decimal ID_UTLTY_DDCTN { get; set; }
        public decimal? AM_UTLTY_DDCTN { get; set; }
        public string CD_UTLTY_DDCTN { get; set; }
        public string TX_UTLTY_DDCTN_DSCR { get; set; }

        public virtual ICollection<REGISTER_UTILITY_EXPENSE> REGISTER_UTILITY_EXPENSE { get; set; }
        public virtual ICollection<UTILITY_EXPENSE> UTILITY_EXPENSE { get; set; }
    }
}