// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_OBLIGATION_REASON
    {
        public int ID_OBLGTN_RSN { get; set; }
        public string CD_OBLGTN_RSN { get; set; }
    }
}