// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_EXCESS_RESOURCE_LIMIT
    {
        public short ID_EXCSS_RSRC_LIMIT { get; set; }
        public string AM_MIN_EXCSS_RSRC_LIMIT { get; set; }
        public string AM_MAX_EXCSS_RSRC_LIMIT { get; set; }
        public string NO_MNTHS_DSQLFCTN { get; set; }
    }
}