// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_EBT_CHCK
    {
        public string ID_SSN_EBT { get; set; }
    }
}