// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_PAY_DATES
    {
        public int ID_PAY_DATES { get; set; }
        public int ID_UNERND_INCM { get; set; }
        public decimal? AM_GROSS_MNTHLY { get; set; }
        public decimal? AM_GROSS_PER_PAY { get; set; }
        public decimal? AM_HRLY_PAY { get; set; }
        public decimal? AM_NET_MNTHLY { get; set; }
        public DateTime? DT_PAY_DATE { get; set; }
        public string FL_INCM_NXT_MNTH { get; set; }
        public string FL_RPRSNTTV_PAY { get; set; }
        public decimal? ID_FRQNCY_PAY { get; set; }
        public decimal? NO_HOURS { get; set; }

        public virtual UNEARNED_INCOME ID_UNERND_INCMNavigation { get; set; }
    }
}