// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_ERR_CODE
    {
        public short ID_ERR_CODE { get; set; }
        public string CD_ERR_CODE { get; set; }
        public string ERR_DESC { get; set; }
    }
}