// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_UNEARNED_TYPE
    {
        public REF_UNEARNED_TYPE()
        {
            REF_UNEARNED_SUBTYPE = new HashSet<REF_UNEARNED_SUBTYPE>();
        }

        public int ID_REF_UNERND_TYPE { get; set; }
        public string TX_UNERND_TYPE_DSCR { get; set; }

        public virtual ICollection<REF_UNEARNED_SUBTYPE> REF_UNEARNED_SUBTYPE { get; set; }
    }
}