// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_VOTER_ANS
    {
        public int ID_REF_VOTER_ANS { get; set; }
        public string CD_YESORNO { get; set; }
        public int CD_SORT { get; set; }
        public string TXT_ANSWER { get; set; }
    }
}