// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_COUNTY_STATE
    {
        public REF_COUNTY_STATE()
        {
            ADDRESS = new HashSet<ADDRESS>();
            CASE = new HashSet<CASE>();
            FA_STATUS = new HashSet<FA_STATUS>();
        }

        public short ID_CNTY_STATE { get; set; }
        public string ID_REF_STATE { get; set; }
        public decimal? CD_CNTY { get; set; }
        public string CD_CNTY_DSCR { get; set; }

        public virtual REF_STATE ID_REF_STATENavigation { get; set; }
        public virtual ICollection<ADDRESS> ADDRESS { get; set; }
        public virtual ICollection<CASE> CASE { get; set; }
        public virtual ICollection<FA_STATUS> FA_STATUS { get; set; }
    }
}