// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_MEDICAL_LIMIT
    {
        public decimal ID_MDCL_LMT { get; set; }
        public decimal? AM_MDCL_LIMIT { get; set; }
        public string CD_MDCL_DSCR { get; set; }
    }
}