// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_SHELTER_NOTES_OTHER
    {
        public short ID_REF_SHLTR_OTHR { get; set; }
        public int? ID_SHLTR_EXPNS { get; set; }
        public string TX_SHLTR_OTHR { get; set; }

        public virtual SHELTER_EXPENSE ID_SHLTR_EXPNSNavigation { get; set; }
    }
}