// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REF_SANCTION_TYPE
    {
        public REF_SANCTION_TYPE()
        {
            REF_SANCTION_REASON = new HashSet<REF_SANCTION_REASON>();
        }

        public short ID_REF_SNCTN_TYPE { get; set; }
        public string CD_SNCTN_TYPE { get; set; }

        public virtual ICollection<REF_SANCTION_REASON> REF_SANCTION_REASON { get; set; }
    }
}