// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_DONOTAPPLY_OLD
    {
        public string ID_SSN { get; set; }
        public string CASENBR { get; set; }
        public string CASENBRAPP { get; set; }
        public string COUNTYCD { get; set; }
        public string COUNTYCDAPP { get; set; }
        /// <summary>
        /// CCYYMM
        /// </summary>
        public string CERTEND { get; set; }
        public string RECERTFLAG { get; set; }
        public string CD_SOURCE { get; set; }
    }
}