// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_CHILD_SUPPORT
    {
        public int ID_CHILD_SUPPORT { get; set; }
        public int? ID_NEWMBR { get; set; }
        public string PAIDTO_FULLNAME { get; set; }
        public decimal? PAID_AMOUNT { get; set; }
        public string PAY_FREQUENCY { get; set; }
        public string CHILDREN { get; set; }

        public virtual REGISTER_MEMBERS ID_NEWMBRNavigation { get; set; }
    }
}