// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_MEMBERS
    {
        public REGISTER_MEMBERS()
        {
            REGISTER_CHILD_SUPPORT = new HashSet<REGISTER_CHILD_SUPPORT>();
            REGISTER_DEPENDENT_CARE = new HashSet<REGISTER_DEPENDENT_CARE>();
            REGISTER_EMPLOYMENT = new HashSet<REGISTER_EMPLOYMENT>();
            REGISTER_FELON = new HashSet<REGISTER_FELON>();
            REGISTER_LIQUIDRESOURCE = new HashSet<REGISTER_LIQUIDRESOURCE>();
            REGISTER_MEDICAL_EXP = new HashSet<REGISTER_MEDICAL_EXP>();
            REGISTER_MIGRANTWORKER = new HashSet<REGISTER_MIGRANTWORKER>();
            REGISTER_MULTIPLEHH = new HashSet<REGISTER_MULTIPLEHH>();
            REGISTER_PAROLE = new HashSet<REGISTER_PAROLE>();
            REGISTER_ROOMERBOARDER = new HashSet<REGISTER_ROOMERBOARDER>();
            REGISTER_SELF_EMPLOYMENT = new HashSet<REGISTER_SELF_EMPLOYMENT>();
            REGISTER_SHELTER_EXP = new HashSet<REGISTER_SHELTER_EXP>();
            REGISTER_SOU = new HashSet<REGISTER_SOU>();
            REGISTER_STAMPSFRAUD = new HashSet<REGISTER_STAMPSFRAUD>();
            REGISTER_STAMPSTRAFFICKING = new HashSet<REGISTER_STAMPSTRAFFICKING>();
            REGISTER_STAMPSWEAPONS = new HashSet<REGISTER_STAMPSWEAPONS>();
            REGISTER_STRIKER = new HashSet<REGISTER_STRIKER>();
            REGISTER_STUDENT = new HashSet<REGISTER_STUDENT>();
            REGISTER_UNEARNED_INC = new HashSet<REGISTER_UNEARNED_INC>();
            REGISTER_UTILITY_EXP = new HashSet<REGISTER_UTILITY_EXP>();
            REGISTER_UTILITY_EXPENSE = new HashSet<REGISTER_UTILITY_EXPENSE>();
            REGISTER_VOLUNTARYQUIT = new HashSet<REGISTER_VOLUNTARYQUIT>();
        }

        public int ID_NEWMBR { get; set; }
        public int ID_NEWCASE { get; set; }
        public int? DEPENDENT_NMBR { get; set; }
        public string FL_HOH { get; set; }
        public string FL_INVALID_MEMBER { get; set; }
        public string CD_INVALID_MEMBER { get; set; }
        public string DHR_APPLICATION_ID { get; set; }
        public int? DHR_PERSON_ID { get; set; }
        public string DHR_RELATIONSHIP { get; set; }
        public string DHR_ETHNICITY { get; set; }
        public string DHR_USCITIZEN { get; set; }
        public string DHR_MEMBER_SSN { get; set; }
        public string DHR_MEMBER_FIRST_NAME { get; set; }
        public string DHR_MEMBER_MIDDLE_NAME { get; set; }
        public string DHR_MEMBER_LAST_NAME { get; set; }
        public string DHR_MEMBER_SUFFIX_NAME { get; set; }
        public string DHR_DOB { get; set; }
        public string DHR_SEX { get; set; }
        public string DHR_RACE { get; set; }
        public string SCI_DEPNUM { get; set; }
        public string SCI_SSN { get; set; }
        public string SCI_VERIND { get; set; }
        /// <summary>
        /// LAST,SUFFIX/FIRST/MIDDLE (28 CHAR) 
        /// </summary>
        public string SCI_DEPNAM { get; set; }
        public string SCI_SEX { get; set; }
        public string SCI_RACE { get; set; }
        /// <summary>
        /// MMDDYYYY
        /// </summary>
        public string SCI_DOB { get; set; }
        public string SCI_PACASE { get; set; }
        public string SCI_ELIG { get; set; }
        public string SCI_ERRMSG { get; set; }
        public string SCI_REG_MATCH { get; set; }

        public virtual REGISTER_DUPLICATEBENEFITS REGISTER_DUPLICATEBENEFITS { get; set; }
        public virtual ICollection<REGISTER_CHILD_SUPPORT> REGISTER_CHILD_SUPPORT { get; set; }
        public virtual ICollection<REGISTER_DEPENDENT_CARE> REGISTER_DEPENDENT_CARE { get; set; }
        public virtual ICollection<REGISTER_EMPLOYMENT> REGISTER_EMPLOYMENT { get; set; }
        public virtual ICollection<REGISTER_FELON> REGISTER_FELON { get; set; }
        public virtual ICollection<REGISTER_LIQUIDRESOURCE> REGISTER_LIQUIDRESOURCE { get; set; }
        public virtual ICollection<REGISTER_MEDICAL_EXP> REGISTER_MEDICAL_EXP { get; set; }
        public virtual ICollection<REGISTER_MIGRANTWORKER> REGISTER_MIGRANTWORKER { get; set; }
        public virtual ICollection<REGISTER_MULTIPLEHH> REGISTER_MULTIPLEHH { get; set; }
        public virtual ICollection<REGISTER_PAROLE> REGISTER_PAROLE { get; set; }
        public virtual ICollection<REGISTER_ROOMERBOARDER> REGISTER_ROOMERBOARDER { get; set; }
        public virtual ICollection<REGISTER_SELF_EMPLOYMENT> REGISTER_SELF_EMPLOYMENT { get; set; }
        public virtual ICollection<REGISTER_SHELTER_EXP> REGISTER_SHELTER_EXP { get; set; }
        public virtual ICollection<REGISTER_SOU> REGISTER_SOU { get; set; }
        public virtual ICollection<REGISTER_STAMPSFRAUD> REGISTER_STAMPSFRAUD { get; set; }
        public virtual ICollection<REGISTER_STAMPSTRAFFICKING> REGISTER_STAMPSTRAFFICKING { get; set; }
        public virtual ICollection<REGISTER_STAMPSWEAPONS> REGISTER_STAMPSWEAPONS { get; set; }
        public virtual ICollection<REGISTER_STRIKER> REGISTER_STRIKER { get; set; }
        public virtual ICollection<REGISTER_STUDENT> REGISTER_STUDENT { get; set; }
        public virtual ICollection<REGISTER_UNEARNED_INC> REGISTER_UNEARNED_INC { get; set; }
        public virtual ICollection<REGISTER_UTILITY_EXP> REGISTER_UTILITY_EXP { get; set; }
        public virtual ICollection<REGISTER_UTILITY_EXPENSE> REGISTER_UTILITY_EXPENSE { get; set; }
        public virtual ICollection<REGISTER_VOLUNTARYQUIT> REGISTER_VOLUNTARYQUIT { get; set; }
    }
}