// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_UTILITY_EXP
    {
        public int ID_UTILITY_EXP { get; set; }
        public int? ID_NEWMBR { get; set; }
        public decimal? PHONE_AMOUNT { get; set; }
        public decimal? ELECTRICITY_AMOUNT { get; set; }
        public decimal? GAS_AMOUNT { get; set; }
        public decimal? OIL_AMOUNT { get; set; }
        public decimal? WATER { get; set; }
        public decimal? GARBAGE_AMOUNT { get; set; }
        public string AIR_CONDITIONING { get; set; }
        public string LHEAP_PAYMENT { get; set; }
        public string LHEAP_ANTICIPATED { get; set; }

        public virtual REGISTER_MEMBERS ID_NEWMBRNavigation { get; set; }
    }
}