// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_ROOMERBOARDER
    {
        public int ID_ROOMERORBOARDER { get; set; }
        public int? ID_NEWMBR { get; set; }
        public decimal? AMOUNT_PAID { get; set; }
        public string PAY_FREQUENCY { get; set; }
        public short? MEALS_PROVIDED { get; set; }

        public virtual REGISTER_MEMBERS ID_NEWMBRNavigation { get; set; }
    }
}