// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_UNEARNED_INC
    {
        public int ID_UNEARNED_INC { get; set; }
        public int? ID_NEWMBR { get; set; }
        public string INCOME_TYPE { get; set; }
        public decimal? UNEARNED_AMOUNT { get; set; }
        public string UNEARNED_FREQUENCY { get; set; }

        public virtual REGISTER_MEMBERS ID_NEWMBRNavigation { get; set; }
    }
}