// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_STRIKER
    {
        public int ID_STRIKER { get; set; }
        public int? ID_NEWMBR { get; set; }
        public string COMPANY_NAME { get; set; }

        public virtual REGISTER_MEMBERS ID_NEWMBRNavigation { get; set; }
    }
}