// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_UTILITY_EXPENSE
    {
        public int ID_UTILITY_EXP { get; set; }
        public int ID_NEWCASE { get; set; }
        public decimal? ID_DEDUCTION { get; set; }
        public int? ID_HAC_MEMBER { get; set; }
        public string FL_HEAT_AC { get; set; }
        public string FL_LIHEAP { get; set; }
        public string FL_PHONE { get; set; }
        public string FL_ELECTRICITY { get; set; }
        public string FL_GAS { get; set; }
        public string FL_OIL { get; set; }
        public string FL_WATER { get; set; }
        public string FL_GARBAGE { get; set; }
        public string FL_OTHER_UTILITY { get; set; }
        public string FL_OUTSIDE_PAY { get; set; }
        public string OUTSIDE_PAY_NAME { get; set; }

        public virtual REF_UTILITY_DEDUCTION ID_DEDUCTIONNavigation { get; set; }
        public virtual REGISTER_MEMBERS ID_HAC_MEMBERNavigation { get; set; }
        public virtual REGISTER_APPLICATION ID_NEWCASENavigation { get; set; }
    }
}