// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REGISTER_MEDICAL_EXP
    {
        public int ID_MEDICAL_EXP { get; set; }
        public int? ID_NEWMBR { get; set; }
        public string EXPENSE_TYPE { get; set; }
        public decimal? EXP_AMOUNT { get; set; }

        public virtual REGISTER_MEMBERS ID_NEWMBRNavigation { get; set; }
    }
}