// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class REQUEST_AUTHORIZITION
    {
        public string ID_USER_NAME { get; set; }
        public string CD_CNTY { get; set; }
        public string CD_PAYROLL { get; set; }
        public string NM_FIRST { get; set; }
        public string NM_LAST { get; set; }
        public string NO_PHONE { get; set; }
        public string FL_SUPERVISOR { get; set; }
        public string CD_DSPSTN { get; set; }
        public string TX_DSPSTN { get; set; }
    }
}