// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class RESTORATION
    {
        public int ID_RSTRTN { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public decimal ID_RSTRTN_RSN { get; set; }
        public decimal? AM_RSTRTN { get; set; }
        public DateTime? DT_RSTRTN { get; set; }

        public virtual CASE ID_CASE_NMBRNavigation { get; set; }
        public virtual REF_RESTORATION_REASON_TYPE ID_RSTRTN_RSNNavigation { get; set; }
    }
}