// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class ROOM
    {
        public ROOM()
        {
            AU_ROOM = new HashSet<AU_ROOM>();
        }

        public int ID_ROOM { get; set; }
        public int? ID_EMPLYMNT { get; set; }
        public int ID_MMBR { get; set; }
        public short? ID_RSRC { get; set; }
        public decimal? AM_ROOM_PAY { get; set; }
        public string CD_MONTH { get; set; }
        public decimal? ID_FRQNCY_ROOM_PAY { get; set; }
        public short? ID_VRFCTN_ROOM { get; set; }
        public string TX_VRFCTN_ROOM { get; set; }

        public virtual EMPLOYMENT ID_EMPLYMNTNavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual RESOURCE ID_RSRCNavigation { get; set; }
        public virtual ICollection<AU_ROOM> AU_ROOM { get; set; }
    }
}