// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class SANCTION
    {
        public int ID_SNCTN { get; set; }
        public decimal ID_REF_SNCTN_RSN { get; set; }
        public int ID_MMBR { get; set; }
        public DateTime? DT_SNCTN_END { get; set; }
        public DateTime? DT_SNCTN_STRT { get; set; }
        public decimal? NO_SNCTN { get; set; }
        public int? ID_WRKR_RMNDR { get; set; }
        public DateTime? DT_COMPLYOREXEMPT { get; set; }

        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual REF_SANCTION_REASON ID_REF_SNCTN_RSNNavigation { get; set; }
    }
}