// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class SCI2_CASE_DATA
    {
        public int ID_SCI2_CASE_DATA { get; set; }
        public int ID_NMBR_CASELOG { get; set; }
        public int ID_AUDIT_CASEACTION { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public string CD_REC_TYPE { get; set; }
        public decimal NO_CASE { get; set; }
        public decimal NO_CASE_CHKDGT { get; set; }
        public string CD_CTY_OFF { get; set; }
        public string CD_CTY_OFF_RESIDING { get; set; }
        public string NM_HOH { get; set; }
        public string TX_ADDRESS { get; set; }
        public string TX_CITY_STATE { get; set; }
        public string TXT_ZIP { get; set; }
        public string NO_HOME_TEL { get; set; }
        public string FL_EBT { get; set; }
        public string NM_AUTH_REP { get; set; }
        public string NM_EBT_REP { get; set; }
        public string CD_TRANSACTION { get; set; }
        public string CD_PRCSSN_STNDRD { get; set; }
        public string CD_EXPEDITE { get; set; }
        public string CD_RJCTN_CLSR { get; set; }
        public string CD_NTC_TYPE_IND { get; set; }
        public string DT_APPLD { get; set; }
        public string DT_CERT_STRT { get; set; }
        public string DT_CERT_END { get; set; }
        public string DT_STRT_ISSNC { get; set; }
        public string CD_ISSUE_TYPE { get; set; }
        public string CD_ADVRS_GUARD { get; set; }
        public string CD_RTR_RST_REASON { get; set; }
        public string CD_CLAIM { get; set; }
        public string AM_RESOURCE { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        public string NO_TMP_WRKR_NMBR { get; set; }
        public string AM_DEP_CARE { get; set; }
        public string AM_MED_EXP { get; set; }
        public string AM_RENT_MORT { get; set; }
        public string AM_PROP_TAX { get; set; }
        public string AM_PROP_INS { get; set; }
        public string AM_OTHER_EXP { get; set; }
        public string CD_UTIL_TYPE { get; set; }
        public string AM_UTILITY { get; set; }
        public string CD_HH_TYPE { get; set; }
        public string CD_LANGUAGE_INDCTR { get; set; }
        public string CD_RPRTNG_RQRMNT { get; set; }
        public string CD_PAST_DUE_RSN { get; set; }
        public int? NO_HH_MMBRS { get; set; }
        public int? NO_HH_MMBR_BUD { get; set; }
        public string CASE_XREF { get; set; }
        public string GROSS_INCOME_TESTED { get; set; }
        public string NET_INCOME_TESTED { get; set; }
        public string EXC_2040 { get; set; }
        public string STND_DED { get; set; }
        public string ADJ_INC { get; set; }
        public string SHL_DED { get; set; }
        public string NET_INC { get; set; }
        public string TFP { get; set; }
        public string RATE_REDUC { get; set; }
        public string TOT_SHL { get; set; }
        public string AM_RETRO_RESTORE { get; set; }
        public string AM_RECOUP { get; set; }
        public string AM_COMBINED { get; set; }
        public string AM_ALLOTMENT { get; set; }
        public string AM_EARNED { get; set; }
        public string AM_UNEARND { get; set; }
        public string AM_CS_EXPENSE { get; set; }
        public string CASE_REVIEW_RSN { get; set; }
        public string DT_CASE_REVIEW { get; set; }
        public string DT_ISSUE { get; set; }
        public string AM_ISSUE { get; set; }
        public string DT_TRANSACTION { get; set; }
        public string DT_TRIAL_BUDGET { get; set; }
    }
}