// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class SCI2_ERRORS
    {
        public int ID_SCI2_ERROR { get; set; }
        public string CD_SCI2_ERROR { get; set; }
        public decimal? NO_CASE { get; set; }
        public DateTime? DT_ERROR { get; set; }
        public string NO_WRKR_NMBR { get; set; }
        public string FL_CASE_LVL { get; set; }
        public string NO_SSN { get; set; }
        public string CD_RJCTN_CLSR { get; set; }
        public int? ID_MMBR { get; set; }
        public string MEMBER_NAME { get; set; }
        public string CD_ERROR { get; set; }

        public virtual REF_SCI2_ERRORS CD_SCI2_ERRORNavigation { get; set; }
    }
}