// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class SCI2_ISSUNCE
    {
        public Guid ISS_ID { get; set; }
        public string ISS_COUNTY { get; set; }
        public string ISS_NO_CASE { get; set; }
        public string ISS_WORKER_NO { get; set; }
        public string ISS_TRAN_DT { get; set; }
        public string ISS_SEQUENCE_NO { get; set; }
        public string ISS_AMT { get; set; }
        public string ISS_TIME { get; set; }
        public string ISS_TYPE { get; set; }
        public string ISS_HH_MEM_INCLUDED { get; set; }
        public string ISS_MAIL_ISSUE_CODE { get; set; }
        public string ISS_OPERATOR_ID { get; set; }
        public string ISS_INITIAL_AMT { get; set; }
        public string ISS_RECOUP_AMT { get; set; }
        public string ISS_RESTOR_AMT { get; set; }
        public string ISS_RESTOR_REASON { get; set; }
        public string ISS_OFF_CD { get; set; }
        public string ISS_ST_ISS_ID { get; set; }
        public string ISS_PPI_SITE { get; set; }
        public string ISS_BEN_AVAIL_DT { get; set; }
        public string ISS_AGED_CENTS { get; set; }
        public string NEW_FIELDS { get; set; }
    }
}