// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class SHELTER_EXPENSE_OTHER_PAYER
    {
        public SHELTER_EXPENSE_OTHER_PAYER()
        {
            UNEARNED_INCOME = new HashSet<UNEARNED_INCOME>();
        }

        public short ID_SHLTR_EXPNS_OTHR_PAYER { get; set; }
        public int ID_MMBR { get; set; }
        public int ID_SHLTR_EXPNS { get; set; }
        public decimal? AM_SHLTR_EXPNS_OTHR_PAYER { get; set; }
        public DateTime? DT_SHLTR_EXPNS_OTHR_PAYER { get; set; }
        public string FL_OUTSIDE_RSDNT { get; set; }
        public string FL_PAY_ALL_SHLTR { get; set; }
        public string FL_SHLTR_EXPNS_PAY_MMBR { get; set; }
        public decimal? ID_FRQNCY_SHLTR_EXPNS_OP { get; set; }
        public short? ID_VRFCTN_SHLTR_EXPNS_OP { get; set; }
        public string TX_VRFCTN_SHLTR_EXPNS_OP { get; set; }

        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual SHELTER_EXPENSE ID_SHLTR_EXPNSNavigation { get; set; }
        public virtual ICollection<UNEARNED_INCOME> UNEARNED_INCOME { get; set; }
    }
}