// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class SHELTER_EXPENSE
    {
        public SHELTER_EXPENSE()
        {
            AU_SHELTER_EXPENSE = new HashSet<AU_SHELTER_EXPENSE>();
            REF_SHELTER_NOTES_OTHER = new HashSet<REF_SHELTER_NOTES_OTHER>();
            SHELTER_EXPENSE_OTHER_PAYER = new HashSet<SHELTER_EXPENSE_OTHER_PAYER>();
        }

        public int ID_SHLTR_EXPNS { get; set; }
        public int ID_MMBR1 { get; set; }
        public int? ID_MMBR2 { get; set; }
        public short ID_OWNRSHP { get; set; }
        public short ID_SHLTR_DWELLNG_TYPE { get; set; }
        public short ID_SHLTR_EXPNS_TYPE { get; set; }
        public decimal? AM_ACTL_SHLTR_EXPNS { get; set; }
        public decimal? AM_SHLTR_EXPNS_MNTHLY { get; set; }
        public string CD_MONTH { get; set; }
        public string FL_ASSSTD_BY_OTHR { get; set; }
        public string FL_NM_OUTSIDE_HH { get; set; }
        public string FL_SHLTR_PASSTHRU { get; set; }
        public decimal? ID_FRQNCY_SHLTR_EXPNS { get; set; }
        public short? ID_VRFCTN_SHLTR_EXPNS { get; set; }
        public string TX_VRFCTN_SHLTR_EXPNS { get; set; }

        public virtual MEMBER ID_MMBR1Navigation { get; set; }
        public virtual MEMBER ID_MMBR2Navigation { get; set; }
        public virtual REF_SHELTER_OWNERSHIP ID_OWNRSHPNavigation { get; set; }
        public virtual REF_SHELTER_DWELLING_TYPE ID_SHLTR_DWELLNG_TYPENavigation { get; set; }
        public virtual REF_SHELTER_EXPENSE_TYPE ID_SHLTR_EXPNS_TYPENavigation { get; set; }
        public virtual ICollection<AU_SHELTER_EXPENSE> AU_SHELTER_EXPENSE { get; set; }
        public virtual ICollection<REF_SHELTER_NOTES_OTHER> REF_SHELTER_NOTES_OTHER { get; set; }
        public virtual ICollection<SHELTER_EXPENSE_OTHER_PAYER> SHELTER_EXPENSE_OTHER_PAYER { get; set; }
    }
}