// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class SMRY_MEDICAL_EXPENSE
    {
        public SMRY_MEDICAL_EXPENSE()
        {
            MEDICAL_EXPENSE = new HashSet<MEDICAL_EXPENSE>();
        }

        public short ID_SMRY_MDCL_EXPNS { get; set; }
        public decimal? AM_MDCL_DDCTN { get; set; }
        public decimal? AM_TTL_MDCL_EXPNS { get; set; }
        public decimal? NO_TTL_MEALS { get; set; }

        public virtual ICollection<MEDICAL_EXPENSE> MEDICAL_EXPENSE { get; set; }
    }
}