// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Split_sync_nameResult
    {
        public string LAST { get; set; }
        public string SUFFIX { get; set; }
        public string FIRST { get; set; }
        public string MIDDLE { get; set; }
        public string SSN { get; set; }
        public DateTime? DOB { get; set; }
        public string SEX { get; set; }
        public int? RACE { get; set; }
    }
}
