// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class TRIP
    {
        public TRIP()
        {
            AU_TRIPS = new HashSet<AU_TRIPS>();
            MEDICAL_EXPENSE = new HashSet<MEDICAL_EXPENSE>();
        }

        public int ID_TRIPS { get; set; }
        public int ID_PRVDR_NAME { get; set; }
        public short? ID_REF_FDRL_MLG_RATE { get; set; }
        public decimal? AM_FLAT_FEE { get; set; }
        public decimal? AM_PAY_MILES_MNTHLY { get; set; }
        public string FL_DRVS_SELF { get; set; }
        public string FL_PAY_FLAT_FEE { get; set; }
        public string FL_PAY_PER_MILE { get; set; }
        public short? ID_VRFCTN_TRIP { get; set; }
        public decimal? NO_MILES_PER_MNTH { get; set; }

        public virtual REF_PROVIDER_NAME ID_PRVDR_NAMENavigation { get; set; }
        public virtual REF_FEDERAL_MILEAGE_RATE ID_REF_FDRL_MLG_RATENavigation { get; set; }
        public virtual ICollection<AU_TRIPS> AU_TRIPS { get; set; }
        public virtual ICollection<MEDICAL_EXPENSE> MEDICAL_EXPENSE { get; set; }
    }
}