// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class UA_EarnedIncomeByCase
    {
        public int? ID_CASE_NMBR { get; set; }
        public decimal? TOTAL_EARNED_INCOME { get; set; }
    }
}