// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class UNEARNED_INCOME
    {
        public UNEARNED_INCOME()
        {
            AU_UNEARNED_INCOME = new HashSet<AU_UNEARNED_INCOME>();
            REF_PAY_DATES = new HashSet<REF_PAY_DATES>();
            TANF_MMBR_INCLUDED = new HashSet<TANF_MMBR_INCLUDED>();
            UNEARNED_PAYER = new HashSet<UNEARNED_PAYER>();
        }

        public int ID_UNERND_INCM { get; set; }
        public int? ID_CS_AMNT { get; set; }
        public short? ID_DC_OTHR_PAY { get; set; }
        public short? ID_INSRNC_OTHR_PAYER { get; set; }
        public short? ID_ME_OTHR_PAYER { get; set; }
        public int ID_MMBR { get; set; }
        public int ID_REF_UNERND_SUBTYPE { get; set; }
        public short? ID_SHLTR_EXPNS_OTHR_PAYER { get; set; }
        public short? ID_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public decimal? AM_UNERND_MNTHLY { get; set; }
        public decimal? AM_UNERND_VALUE1 { get; set; }
        public decimal? AM_UNERND_VALUE2 { get; set; }
        public string CD_MONTH { get; set; }
        public DateTime? DT_RCVD { get; set; }
        public string FL_DSBLTY { get; set; }
        public decimal? ID_FRQNCY_RECPT { get; set; }
        public short? ID_VRFCTN_UNERND_INCM { get; set; }
        public int? NO_PYMNT_MNTHS { get; set; }
        public string TX_VRFCTN_UNERND_INCM { get; set; }

        public virtual CS_AMOUNT ID_CS_AMNTNavigation { get; set; }
        public virtual DEPENDENT_CARE_OTHER_PAYER ID_DC_OTHR_PAYNavigation { get; set; }
        public virtual INSURANCE_OTHER_PAYER ID_INSRNC_OTHR_PAYERNavigation { get; set; }
        public virtual MEDICAL_EXPENSE_OTHER_PAYER ID_ME_OTHR_PAYERNavigation { get; set; }
        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual REF_UNEARNED_SUBTYPE ID_REF_UNERND_SUBTYPENavigation { get; set; }
        public virtual SHELTER_EXPENSE_OTHER_PAYER ID_SHLTR_EXPNS_OTHR_PAYERNavigation { get; set; }
        public virtual UTILITY_EXPENSE_OTHER_PAYER ID_UTLTY_EXPNS_OTHR_PAYERNavigation { get; set; }
        public virtual ICollection<AU_UNEARNED_INCOME> AU_UNEARNED_INCOME { get; set; }
        public virtual ICollection<REF_PAY_DATES> REF_PAY_DATES { get; set; }
        public virtual ICollection<TANF_MMBR_INCLUDED> TANF_MMBR_INCLUDED { get; set; }
        public virtual ICollection<UNEARNED_PAYER> UNEARNED_PAYER { get; set; }
    }
}