// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class UNEARNED_PAYER
    {
        public int ID_UNERND_PAYER { get; set; }
        public int? ID_UNERND_INCM { get; set; }
        public short ID_REF_UNERND_PAYER_TYPE { get; set; }
        public string NM_UNERND_PAYER { get; set; }

        public virtual REF_UNEARNED_PAYER_TYPE ID_REF_UNERND_PAYER_TYPENavigation { get; set; }
        public virtual UNEARNED_INCOME ID_UNERND_INCMNavigation { get; set; }
    }
}