// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Oacis
{
    public partial class Updt_MDCL_INSURANCEResult
    {
        public decimal? ID_INSRNC_OTHR_PAYER { get; set; }
    }
}
