// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class UTILITY_EXPENSE
    {
        public UTILITY_EXPENSE()
        {
            AU_UTILITY_EXPENSE = new HashSet<AU_UTILITY_EXPENSE>();
            UTILITY_EXPENSE_OTHER_PAYER = new HashSet<UTILITY_EXPENSE_OTHER_PAYER>();
        }

        public int ID_UTLTY_EXPNS { get; set; }
        public int ID_MMBR1 { get; set; }
        public int? ID_MMBR2 { get; set; }
        public decimal? ID_UTLTY_DDCTN { get; set; }
        public int ID_UTLTY_TYPE { get; set; }
        public decimal? AM_ACTL_UTLTY_AVG { get; set; }
        public decimal? AM_UTLTY_EXPNS { get; set; }
        public decimal? AM_UTLTY_EXPNS_MNTHLY { get; set; }
        public decimal? AM_UTLTY_EXPNS_TTL_ALLWBL { get; set; }
        public string CD_MONTH { get; set; }
        public DateTime? DT_LIHEAP_RCVD { get; set; }
        public string FL_AC_BLLD { get; set; }
        public string FL_ASSSTD_BY_OTHR { get; set; }
        public string FL_BUA { get; set; }
        public string FL_HTNG_BLLD { get; set; }
        public string FL_LIHEAP { get; set; }
        public string FL_NM_OUTSIDE_HH_UE { get; set; }
        public string FL_PHONE_STNDRD { get; set; }
        public string FL_SUA_ELGBL { get; set; }
        public string FL_UTLTY_PASSTHRU { get; set; }
        public decimal? ID_FRQNCY_UTLTY_EXPNS { get; set; }
        public short? ID_VRFCTN_UTLTY_EXPNS { get; set; }
        public string TX_VRFCTN_UTLTY_EXPNS { get; set; }

        public virtual MEMBER ID_MMBR1Navigation { get; set; }
        public virtual MEMBER ID_MMBR2Navigation { get; set; }
        public virtual REF_UTILITY_DEDUCTION ID_UTLTY_DDCTNNavigation { get; set; }
        public virtual REF_UTILITY_TYPE ID_UTLTY_TYPENavigation { get; set; }
        public virtual ICollection<AU_UTILITY_EXPENSE> AU_UTILITY_EXPENSE { get; set; }
        public virtual ICollection<UTILITY_EXPENSE_OTHER_PAYER> UTILITY_EXPENSE_OTHER_PAYER { get; set; }
    }
}