// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class UTILITY_EXPENSE_OTHER_PAYER
    {
        public UTILITY_EXPENSE_OTHER_PAYER()
        {
            UNEARNED_INCOME = new HashSet<UNEARNED_INCOME>();
        }

        public short ID_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public int ID_UTLTY_EXPNS { get; set; }
        public int ID_MMBR { get; set; }
        public decimal? AM_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public DateTime? DT_UTLTY_EXPNS_OTHR_PAYER { get; set; }
        public string FL_ALLPART_PAY_UTLTY_EXPNS { get; set; }
        public string FL_OUTSIDE_RSDNT_UE { get; set; }
        public string FL_UTLTY_PAY_MMBR { get; set; }
        public decimal? ID_FRQNCY_UTLTY_EXPNS_OP { get; set; }
        public short? ID_VRFCTN_UTLTY_EXPNS_OP { get; set; }
        public string TX_VRFCTN_UTLTY_EXPNS_OP { get; set; }

        public virtual MEMBER ID_MMBRNavigation { get; set; }
        public virtual UTILITY_EXPENSE ID_UTLTY_EXPNSNavigation { get; set; }
        public virtual ICollection<UNEARNED_INCOME> UNEARNED_INCOME { get; set; }
    }
}