// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Oacis
{
    public partial class WAIVE_ADVERSE_ACTION
    {
        public int ID_WAIVE_ADVRS_ACTN { get; set; }
        public short? ID_REF_WAIVE_ADVRS_ACTN { get; set; }
        public int ID_CASE_NMBR { get; set; }
        public DateTime? DT_ADVRS_ACTN { get; set; }
        public string FL_WAIVE_ADVRS_ACTN_10DAY { get; set; }

        public virtual CASE ID_CASE_NMBRNavigation { get; set; }
        public virtual REF_WAIVE_ADVERSE_ACTION ID_REF_WAIVE_ADVRS_ACTNNavigation { get; set; }
    }
}