// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Dhr
{
    public partial class AttachmentFile
    {
        public Guid Id { get; set; }
        public Guid EmailId { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }

        public virtual Email Email { get; set; }
    }
}