// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Dhr
{
    public partial class Email
    {
        public Email()
        {
            AttachmentFile = new HashSet<AttachmentFile>();
        }

        public Guid Id { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Guid? UserId { get; set; }
        public DateTime? Date { get; set; }

        public virtual ICollection<AttachmentFile> AttachmentFile { get; set; }
    }
}