// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Dhr
{
    public partial class GetIPsWithMultipleApplicationsResult
    {
        public byte[] IPAddress { get; set; }
        public int? TotalCount { get; set; }
    }
}
