// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Dhr
{
    public partial class GetSubmittedAppsByIPAddressResult
    {
        public Guid WorkflowId { get; set; }
        public DateTime CompletedDate { get; set; }
        public DateTime? SubmittedDate { get; set; }
        public bool Submitted { get; set; }
        public Guid UserId { get; set; }
        public string CaseNumber { get; set; }
    }
}