// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Dhr
{
    public partial class LexisNexis
    {
        public Guid UserId { get; set; }
        public string AppId { get; set; }
        public string RequestData { get; set; }
        public string ResponseData { get; set; }
        public int? Cvi { get; set; }
        public string RiskData { get; set; }
        public bool? PotentiallyFraudulent { get; set; }
        public DateTime? AppStartDate { get; set; }
        public string AccountEmail { get; set; }
        public string AccountTelephone { get; set; }
        public string AccountAddressStreet1 { get; set; }
        public string AccountAddressStreet2 { get; set; }
        public string AccountAddressCity { get; set; }
        public string AccountAddressZip { get; set; }
        public string AccountAddressState { get; set; }
        public string AccountAddressCountry { get; set; }
        public DateTime? AccountDateOfBirth { get; set; }
        public string AccountFirstName { get; set; }
        public string AccountLastName { get; set; }
        public string SsnRaw { get; set; }
        public bool? Submitted { get; set; }
        public bool? Approved { get; set; }
    }
}