// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Dhr
{
    public partial class MyDhrRole
    {
        public MyDhrRole()
        {
            User = new HashSet<MyDhrUser>();
        }

        public Guid Id { get; set; }
        public string Role { get; set; }
        public string Description { get; set; }

        public virtual ICollection<MyDhrUser> User { get; set; }
    }
}