// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Dhr
{
    public partial class MyDhrSession
    {
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime ExpireDate { get; set; }
        public Guid? AccountRepId { get; set; }
        public string CaseNumber { get; set; }
        public byte[] IpAddress { get; set; }

        public virtual MyDhrUser User { get; set; }
    }
}