// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities.Dhr
{
    public partial class MyDhrUser
    {
        public MyDhrUser()
        {
            CompletedApplication = new HashSet<CompletedApplication>();
            MyDhrSession = new HashSet<MyDhrSession>();
            PasswordToken = new HashSet<PasswordToken>();
            Role = new HashSet<MyDhrRole>();
        }

        public Guid Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public Guid? MyAlabamaUserId { get; set; }
        public string MyAlabamaUserName { get; set; }
        public DateTime? MyAlabamaLinkDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public DateTime? Dob { get; set; }
        public string Ssn { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string Ssnhash { get; set; }
        public string SecurityQuestion1 { get; set; }
        public string SecurityQuestion2 { get; set; }
        public string SecurityQuestion3 { get; set; }
        public string SecurityAnswer1 { get; set; }
        public string SecurityAnswer2 { get; set; }
        public string SecurityAnswer3 { get; set; }
        public DateTime? PasswordLastReset { get; set; }
        public int? PasswordAttempts { get; set; }

        public virtual ICollection<CompletedApplication> CompletedApplication { get; set; }
        public virtual ICollection<MyDhrSession> MyDhrSession { get; set; }
        public virtual ICollection<PasswordToken> PasswordToken { get; set; }

        public virtual ICollection<MyDhrRole> Role { get; set; }
    }
}